# Notice

To run this notebook, you need to install pipenv via

```
pipenv install --dev
```

In [3]:
from rdkit import Chem

gt = r"NC(=O)OCC1=C(C(=O)OC(c2ccccc2)c2ccccc2)N2C(=O)[C@@H](NC(=O)/C(=N\OCC3CC3)c3csc(NC(c4ccccc4)(c4ccccc4)c4ccccc4)n3)[C@H]2SC1"

pred = r"NC(=O)OCC1=C(C(=O)OC(C2=CC=CC=C2)C3=CC=CC=C3)N4C(=O)[C@@H](NC(=O)/C(=N\OCC5CC5)C6=CSC(NC(C7=CC=CC=C7)(C8=CC=CC=C8)C9=CC=CC=C9)=N6)[C@H]4SC1"

m1 = Chem.MolFromSmiles(gt)
m2 = Chem.MolFromSmiles(pred)

if m1 is None or m2 is None:
    print("至少一个 SMILES 无法解析，不能判定结构等价")
else:
    print("GT canonical:", Chem.MolToSmiles(m1, isomericSmiles=True))
    print("Pred canonical:", Chem.MolToSmiles(m2, isomericSmiles=True))
    print("Exact isomeric match:",
          Chem.MolToSmiles(m1, isomericSmiles=True)
          == Chem.MolToSmiles(m2, isomericSmiles=True))

GT canonical: NC(=O)OCC1=C(C(=O)OC(c2ccccc2)c2ccccc2)N2C(=O)[C@@H](NC(=O)/C(=N\OCC3CC3)c3csc(NC(c4ccccc4)(c4ccccc4)c4ccccc4)n3)[C@H]2SC1
Pred canonical: NC(=O)OCC1=C(C(=O)OC(c2ccccc2)c2ccccc2)N2C(=O)[C@@H](NC(=O)/C(=N\OCC3CC3)c3csc(NC(c4ccccc4)(c4ccccc4)c4ccccc4)n3)[C@H]2SC1
Exact isomeric match: True

In [1]:
import sys
import os
current_dir = os.getcwd()
REPO_BASE_DIR = os.path.dirname(os.path.abspath(current_dir))
sys.path.append(REPO_BASE_DIR)
print(REPO_BASE_DIR)
from dotenv import load_dotenv
load_dotenv(os.path.join(REPO_BASE_DIR, ".env"))

/home/data4/xiangyu

False

In [4]:
from swift import get_processor, get_template

tokenizer = get_processor('/home/data4/xiangyu/models/Qwen3.5-9B')
# template = get_template(tokenizer)  # 使用默认agent模板
template = get_template(tokenizer, agent_template='qwen3_5')
print(f'agent_template: {template._agent_template}')

print(template)
# data = {...}
# template.set_mode('train')
# encoded = template.encode(data)
# print(f'[INPUT_IDS] {template.safe_decode(encoded["input_ids"])}\n')
# print(f'[LABELS] {template.safe_decode(encoded["labels"])}')

[WARNING:swift] Loading model from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. This will execute custom Python code shipped in the model repository (e.g. configuration_*.py, modeling_*.py, tokenization_*.py). Only proceed if you trust the source of this model.
[INFO:swift] Setting torch_dtype: torch.bfloat16
[WARNING:swift] Loading config from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. Custom Python code from the model repository will be executed. Only use models from sources you trust.
[WARNING:swift] Loading tokenizer/processor from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. Custom Python code from the model repository will be executed. Only use models from sources you trust.
[INFO:swift] default_system: None
[INFO:swift] max_length: 262144
[INFO:swift] response_prefix: None
[INFO:swift] agent_template: qwen3_5
[INFO:swift] norm_bbox: norm1000

agent_template: qwen3_5
<swift.template.templates.qwen.Qwen3_5Template object at 0x7f51d333d1c0>

In [5]:
import os
import sys

sys.path.insert(0, "/home/data4/xiangyu/BioDSA")

os.environ["SWISSPROT_XML_PATH"] = (
    "/home/data4/xiangyu/dataset/protein_knowledgebase/"
    "uniport/uniprot_sprot.xml.gz"
)

os.environ["PFAM_HMM_PATH"] = (
    "/home/data4/xiangyu/dataset/protein_knowledgebase/"
    "pfam/Pfam-A.hmm"
)

from biodsa.tools.protein.xml_index import iter_uniprot_annotations
from biodsa.tools.protein import (
    build_protein_annotation_index,
    query_protein,
)

In [2]:
import gzip
import time
from pathlib import Path

xml_path = Path(
    "/home/data4/xiangyu/dataset/protein_knowledgebase/"
    "uniport/uniprot_sprot.xml.gz"
)

print("文件存在:", xml_path.is_file())
print("压缩文件大小 GB:", round(xml_path.stat().st_size / 1024**3, 3))

start = time.perf_counter()

with gzip.open(xml_path, "rb") as handle:
    head = handle.read(4096)

print("读取前 4KB 耗时:", round(time.perf_counter() - start, 3), "秒")
print(head.decode("utf-8", errors="replace"))

文件存在: True
压缩文件大小 GB: 0.877
读取前 4KB 耗时: 0.001 秒
<?xml version="1.0" encoding="UTF-8"?>
<uniprot xmlns="https://uniprot.org/uniprot"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://uniprot.org/uniprot http://www.uniprot.org/docs/uniprot.xsd">
<entry dataset="Swiss-Prot" created="2009-05-05" modified="2026-06-10" version="14" xmlns="https://uniprot.org/uniprot">
    <accession>P0C9F0</accession>
    <name>1001R_ASFK5</name>
    <protein>
        <recommendedName>
            <fullName>Protein MGF 100-1R</fullName>
        </recommendedName>
    </protein>
    <gene>
        <name type="ordered locus">Ken-018</name>
    </gene>
    <organism>
        <name type="scientific">African swine fever virus (isolate Pig/Kenya/KEN-50/1950)</name>
        <name type="common">ASFV</name>
        <dbReference type="NCBI Taxonomy" id="561445"/>
        <lineage>
            <taxon>Viruses</taxon>
            <taxon>Varidnaviria</taxon>
            <taxon>Bamfordvirae</taxon>
            <taxon>Nucleocytoviricota</taxon>
            <taxon>Pokkesviricetes</taxon>
            <taxon>Asfuvirales</taxon>
            <taxon>Asfarviridae</taxon>
            <taxon>Asfivirus</taxon>
            <taxon>Asfivirus haemorrhagiae</taxon>
            <taxon>African swine fever virus</taxon>
        </lineage>
    </organism>
    <organismHost>
        <name type="scientific">Ornithodoros</name>
        <name type="common">relapsing fever ticks</name>
        <dbReference type="NCBI Taxonomy" id="6937"/>
    </organismHost>
    <organismHost>
        <name type="scientific">Phacochoerus aethiopicus</name>
        <name type="common">Warthog</name>
        <dbReference type="NCBI Taxonomy" id="85517"/>
    </organismHost>
    <organismHost>
        <name type="scientific">Phacochoerus africanus</name>
        <name type="common">Warthog</name>
        <dbReference type="NCBI Taxonomy" id="41426"/>
    </organismHost>
    <organismHost>
        <name type="scientific">Potamochoerus larvatus</name>
        <name type="common">Bushpig</name>
        <dbReference type="NCBI Taxonomy" id="273792"/>
    </organismHost>
    <organismHost>
        <name type="scientific">Sus scrofa</name>
        <name type="common">Pig</name>
        <dbReference type="NCBI Taxonomy" id="9823"/>
    </organismHost>
    <reference key="1">
        <citation type="submission" date="2003-03" db="EMBL/GenBank/DDBJ databases">
            <title>African swine fever virus genomes.</title>
            <authorList>
                <person name="Kutish G.F."/>
                <person name="Rock D.L."/>
            </authorList>
        </citation>
        <scope>NUCLEOTIDE SEQUENCE [LARGE SCALE GENOMIC DNA]</scope>
    </reference>
    <comment type="function">
        <text evidence="1">Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.</text>
    </comment>
    <comment type="similarity">
        <text evidence="2">Belongs to the asfivirus MGF 100 family.</text>
    </comment>
    <dbReference type="EMBL" id="AY261360">
        <property type="status" value="NOT_ANNOTATED_CDS"/>
        <property type="molecule type" value="Genomic_DNA"/>
    </dbReference>
    <dbReference type="SMR" id="P0C9F0"/>
    <dbReference type="Proteomes" id="UP000000861">
        <property type="component" value="Segment"/>
    </dbReference>
    <proteinExistence type="inferred from homology"/>
    <keyword id="KW-1185">Reference proteome</keyword>
    <feature type="chain" id="PRO_0000373170" description="Protein MGF 100-1R">
        <location>
            <begin position="1"/>
            <end position="122"/>
        </location>
    </feature>
    <evidence type="ECO:0000250" key="1"/>
    <evidence type="ECO:0000305" key="2"/>
    <sequence length="122" mass="14969" checksum="C5E63C34B941711C" modified="2009-05-05" version="1">MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLENAPGGTYFITENMTNELIMIAKDPVDKKIKSVKLYLTGNYIKINQHYYINIYMYLMRYNQIYKYPLICFSKYSKIL</sequence>
</entry>
<entry dataset="Swiss-Prot" created="2009-05-05" modified="2026-06-10" version="22" xmlns="htt

In [3]:
import gzip
import time
import xml.etree.ElementTree as ET

from biodsa.tools.protein.xml_index import (
    uniprot_xml_entry_to_dict,
    NS_URI,
)

def local_name(tag):
    return tag.rsplit("}", 1)[-1]


def inspect_xml_entries(xml_path, count=3, max_bytes=8 * 1024 * 1024):
    parser = ET.XMLPullParser(events=("start", "end"))

    bytes_read = 0
    found = 0
    root_seen = False
    start = time.perf_counter()

    with gzip.open(xml_path, "rb") as handle:
        while bytes_read < max_bytes:
            chunk = handle.read(
                min(64 * 1024, max_bytes - bytes_read)
            )

            if not chunk:
                break

            bytes_read += len(chunk)
            parser.feed(chunk)

            for event, element in parser.read_events():
                if event == "start" and not root_seen:
                    root_seen = True
                    print("实际根标签:", repr(element.tag), flush=True)

                if event != "end" or local_name(element.tag) != "entry":
                    continue

                found += 1

                print(
                    f"\n找到第 {found} 条，"
                    f"已读取 {bytes_read / 1024:.1f} KiB，"
                    f"耗时 {time.perf_counter() - start:.2f} 秒",
                    flush=True,
                )
                print("实际 entry 标签:", repr(element.tag), flush=True)

                expected_tag = f"{{{NS_URI}}}entry"

                if element.tag != expected_tag:
                    print(
                        "命名空间与现有解析器不一致，需要修改 NS_URI。",
                        flush=True,
                    )
                    return

                annotation = uniprot_xml_entry_to_dict(element)

                print("Accession:", annotation["accession"], flush=True)
                print("Name:", annotation["protein_name"], flush=True)
                print("Length:", annotation["sequence_length"], flush=True)
                print("Function:", annotation["function"][:1], flush=True)

                # 不打印完整 raw XML，避免 Notebook 输出过大
                print(
                    "Reaction equations:",
                    [
                        reaction["equation"]
                        for reaction in annotation["catalytic_activity"][:2]
                    ],
                    flush=True,
                )

                element.clear()

                if found >= count:
                    return

    print(
        f"\n测试结束：读取 {bytes_read / 1024**2:.2f} MiB，"
        f"找到 {found} 条 entry。",
        flush=True,
    )

    if found == 0:
        print("没有找到 entry，请检查文件内容或 XML 格式。")


inspect_xml_entries(str(xml_path))

实际根标签: '{https://uniprot.org/uniprot}uniprot'

找到第 1 条，已读取 64.0 KiB，耗时 0.01 秒
实际 entry 标签: '{https://uniprot.org/uniprot}entry'
Accession: P0C9F0
Name: Protein MGF 100-1R
Length: 122
Function: ['Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.']
Reaction equations: []

找到第 2 条，已读取 64.0 KiB，耗时 0.01 秒
实际 entry 标签: '{https://uniprot.org/uniprot}entry'
Accession: P0C9F1
Name: Protein MGF 100-1R
Length: 126
Function: ['Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.']
Reaction equations: []

找到第 3 条，已读取 64.0 KiB，耗时 0.02 秒
实际 entry 标签: '{https://uniprot.org/uniprot}entry'
Accession: P0C9F2
Name: Protein MGF 100-1R
Length: 124
Function: ['Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.']
Reaction equations: []

In [6]:
from itertools import islice

iterator = iter_uniprot_annotations(
    os.environ["SWISSPROT_XML_PATH"]
)

try:
    examples = list(islice(iterator, 3))
finally:
    iterator.close()

for annotation in examples:
    print("Accession:", annotation["accession"])
    print("Name:", annotation["protein_name"])
    print("Length:", annotation["sequence_length"])
    print("Function:", annotation["function"][:1])
    print("Reactions:", annotation["catalytic_activity"][:1])
    print()

Accession: P0C9F0
Name: Protein MGF 100-1R
Length: 122
Function: ['Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.']
Reactions: []

Accession: P0C9F1
Name: Protein MGF 100-1R
Length: 126
Function: ['Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.']
Reactions: []

Accession: P0C9F2
Name: Protein MGF 100-1R
Length: 124
Function: ['Plays a role in virus cell tropism, and may be required for efficient virus replication in macrophages.']
Reactions: []

In [7]:
result = build_protein_annotation_index(
    xml_path=os.environ["SWISSPROT_XML_PATH"],
    index_path=(
        "/home/data4/xiangyu/dataset/protein_knowledgebase/"
        "indexes/protein_annotations.sqlite"
    ),
    rhea_mapping_path=(
        "/home/data4/xiangyu/dataset/protein_knowledgebase/"
        "Rhea/rhea2uniprot_sprot.tsv"
    ),
)

print(result)

{'index_path': '/home/data4/xiangyu/dataset/protein_knowledgebase/indexes/protein_annotations.sqlite', 'proteins': 575748, 'rhea_mapping_rows_processed': 400643, 'warnings': []}

In [2]:
import sqlite3
import pandas as pd

DB_PATH = "/home/data4/xiangyu/dataset/chemistry_knowledgebase/ORD/ord-data/ord_nlp_lite.db"

def main():
    # 连接到刚才生成的精简版数据库
    conn = sqlite3.connect(DB_PATH)

    print("==================================================")
    print(" 验证 1：基本数据量统计")
    print("==================================================")
    
    total_rxns = pd.read_sql("SELECT COUNT(*) as count FROM reaction_conditions", conn).iloc[0]['count']
    total_comps = pd.read_sql("SELECT COUNT(*) as count FROM reaction_components", conn).iloc[0]['count']
    
    print(f"总反应数量 (reaction_conditions): {total_rxns:,}")
    print(f"总组件数量 (reaction_components): {total_comps:,}\n")

    print("==================================================")
    print(" 验证 2：产率预测任务 (Yield Prediction)")
    print(" (目标：需要反应SMILES和产率)")
    print("==================================================")
    
    # 随机抽取 3 条带有产率的反应
    query_yield = """
        SELECT reaction_id, reaction_smiles, yield_percent, temperature_celsius
        FROM reaction_conditions 
        WHERE yield_percent IS NOT NULL AND reaction_smiles IS NOT NULL
        ORDER BY RANDOM() LIMIT 3
    """
    df_yield = pd.read_sql(query_yield, conn)
    for _, row in df_yield.iterrows():
        print(f"[ID]: {row['reaction_id']}")
        print(f"[SMILES]: {row['reaction_smiles']}")
        print(f"[Yield]: {row['yield_percent']}% | [Temp]: {row['temperature_celsius']}°C\n")


    print("==================================================")
    print(" 验证 3：溶剂推断任务 (Solvent Prediction)")
    print(" (目标：需要反应SMILES和对应的溶剂集合)")
    print("==================================================")
    
    # 随机抽取 3 条记录了明确溶剂的反应
    query_solvent = """
        SELECT reaction_id, reaction_smiles, solvents 
        FROM reaction_conditions 
        WHERE solvents IS NOT NULL 
        ORDER BY RANDOM() LIMIT 3
    """
    df_solvent = pd.read_sql(query_solvent, conn)
    for _, row in df_solvent.iterrows():
        print(f"[ID]: {row['reaction_id']}")
        print(f"[SMILES]: {row['reaction_smiles']}")
        print(f"[Solvents]: {row['solvents']}\n")


    print("==================================================")
    print(" 验证 4：角色分布统计与强制包含 Reagent 的反应")
    print("==================================================")
    
    # 1. 看看整个数据库里各种 Role 的数量分布
    query_roles = """
        SELECT reaction_role, COUNT(*) as count 
        FROM reaction_components 
        GROUP BY reaction_role
        ORDER BY count DESC
    """
    df_roles = pd.read_sql(query_roles, conn)
    print("【全局组件角色分布】:")
    print(df_roles.to_markdown(index=False))
    print("\n")

    # 2. 强制随机找一个明确打上了 'REAGENT' 标签的反应
    query_target = """
        SELECT reaction_id FROM reaction_components 
        WHERE reaction_role = 'REAGENT'
        LIMIT 1
    """
    target_id = pd.read_sql(query_target, conn).iloc[0]['reaction_id']
    
    query_components = f"""
        SELECT component_type, reaction_role, compound_name, smiles 
        FROM reaction_components 
        WHERE reaction_id = '{target_id}'
    """
    df_components = pd.read_sql(query_components, conn)
    
    print(f"【明确包含 REAGENT 的反应】 ID: {target_id}")
    print(df_components.to_markdown(index=False))
    print("\n==================================================")

    conn.close()

if __name__ == "__main__":
    main()

==================================================
 验证 1：基本数据量统计
==================================================
总反应数量 (reaction_conditions): 2,428,291
总组件数量 (reaction_components): 14,623,074

==================================================
 验证 2：产率预测任务 (Yield Prediction)
 (目标：需要反应SMILES和产率)
==================================================

[ID]: ord-5331468a6058469da2ed47b1a2d2e692
[SMILES]: [OH:1][C@H:2]([CH2:28][OH:29])[CH2:3][O:4][C:5]1[CH:6]=[CH:7][C:8]2[C:20](=[O:21])[C:19]3[C:18]4[C:13](=[C:14]([OH:24])[C:15]([C:22]#[N:23])=[CH:16][CH:17]=4)[NH:12][C:11]=3[C:10]([CH3:26])([CH3:25])[C:9]=2[CH:27]=1.[CH3:30][Si](C=[N+]=[N-])(C)C.C(N(C(C)C)CC)(C)C>CO.C(Cl)(Cl)Cl>[OH:1][C@H:2]([CH2:28][OH:29])[CH2:3][O:4][C:5]1[CH:6]=[CH:7][C:8]2[C:20](=[O:21])[C:19]3[C:18]4[C:13](=[C:14]([O:24][CH3:30])[C:15]([C:22]#[N:23])=[CH:16][CH:17]=4)[NH:12][C:11]=3[C:10]([CH3:26])([CH3:25])[C:9]=2[CH:27]=1
[Yield]: 62.0% | [Temp]: nan°C

[ID]: ord-c1ad5c00b3a348949d0c7eaebc0ce91a
[SMILES]: [CH3:1][O:2][C:3]1[CH:8]=[CH:7][C:6]([NH:9][NH:10][C:11](=[S:13])[NH2:12])=[CH:5][CH:4]=1.[C:14](OC(=O)C)(=[O:16])[CH3:15].CC1C=CC=CC=1C.O(C(C)C)C(C)C>O>[NH2:12][C:11](=[S:13])[NH:10][N:9]([C:6]1[CH:5]=[CH:4][C:3]([O:2][CH3:1])=[CH:8][CH:7]=1)[C:14](=[O:16])[CH3:15]
[Yield]: 89.0% | [Temp]: nan°C

[ID]: ord-34381962d4704566b53793a0e3e06cd3
[SMILES]: CC1=CC=C(N)N=C1.[C-]#[N+]C1CCCCC1.ClC1=CC(Br)=CC(C=O)=C1>>CC1=CN2C(C=C1)=NC(=C2NC1CCCCC1)C1=CC(Br)=CC(Cl)=C1
[Yield]: 21.196064% | [Temp]: 22.0°C

==================================================
 验证 3：溶剂推断任务 (Solvent Prediction)
 (目标：需要反应SMILES和对应的溶剂集合)
==================================================
[ID]: ord-1fc8670a0d31472081fb55a151a34e4a
[SMILES]: CC1(C)[O:9][CH2:8][CH2:7][C@H:6]2[N:3]1[C:4](=[O:15])[C@@H:5]2[C:10]([O:13][CH3:14])([CH3:12])[CH3:11]>C(O)(=O)C.O>[OH:9][CH2:8][CH2:7][C@H:6]1[NH:3][C:4](=[O:15])[C@@H:5]1[C:10]([O:13][CH3:14])([CH3:12])[CH3:11]
[Solvents]: ["acetic acid","water"]

[ID]: ord-52e162d3dbb344d8a4b8be5ad45ff782
[SMILES]: [NH2:1][C:2]1[C:7]([NH2:8])=[CH:6][CH:5]=[CH:4][C:3]=1[CH3:9].[CH2:10]([O:12][C:13](OCC)(OCC)OCC)[CH3:11]>C(OCC)(=O)C>[CH2:10]([O:12][C:13]1[NH:1][C:2]2[C:3]([CH3:9])=[CH:4][CH:5]=[CH:6][C:7]=2[N:8]=1)[CH3:11]
[Solvents]: ["ethyl acetate"]

[ID]: ord-dd6036040f93487aa0036fabe3c69aef
[SMILES]: [H-].[Al+3].[Li+].[H-].[H-].[H-].[CH3:7][C:8]1([CH3:15])[C@@H:13]([OH:14])[C:11](=[O:12])[O:10][CH2:9]1>C1COCC1>[CH3:7][C:8]([CH3:15])([CH2:9][OH:10])[C@@H:13]([OH:14])[CH2:11][OH:12] |f:0.1.2.3.4.5|
[Solvents]: ["THF"]

==================================================
 验证 4：角色分布统计与强制包含 Reagent 的反应
==================================================
【全局组件角色分布】:
| reaction_role     |   count |
|:------------------|--------:|
| REACTANT          | 8329983 |
| SOLVENT           | 2845181 |
| product           | 2499989 |
| CATALYST          |  478131 |
| REAGENT           |  243492 |
| desired_product   |  173048 |
| INTERNAL_STANDARD |   50364 |
|                   |    2116 |
| WORKUP            |     770 |


【明确包含 REAGENT 的反应】 ID: ord-56b1f4bfeebc4b8ab990b9804e798aa7
| component_type   | reaction_role   | compound_name   | smiles                                                                                                                            |
|:-----------------|:----------------|:----------------|:----------------------------------------------------------------------------------------------------------------------------------|
| input            | REAGENT         |                 | C(=O)([O-])[O-].[Cs+].[Cs+]                                                                                                       |
| input            | CATALYST        |                 | C1=CC=C(C=C1)P(C2=CC=CC=C2)C3=C(C4=CC=CC=C4C=C3)C5=C(C=CC6=CC=CC=C65)P(C7=CC=CC=C7)C8=CC=CC=C8                                    |
| input            | CATALYST        |                 | C1=CC=C(C=C1)/C=C/C(=O)/C=C/C2=CC=CC=C2.C1=CC=C(C=C1)/C=C/C(=O)/C=C/C2=CC=CC=C2.C1=CC=C(C=C1)/C=C/C(=O)/C=C/C2=CC=CC=C2.[Pd].[Pd] |
| input            | REACTANT        |                 | CCOC1=C(C=C2C(=C1)N=CC(=C2NC3=C(C=C(C=C3)F)F)C(=O)OCC)Br                                                                          |
| input            | REACTANT        |                 | CC(C)N1CCNCC1                                                                                                                     |
| product          | desired_product |                 | CCOC1=C(C=C2C(=C1)N=CC(=C2NC3=C(C=C(C=C3)F)F)C(=O)OCC)N4CCN(CC4)C(C)C                                                             |

==================================================

In [19]:
annotation = load_local_annotation(
    first_accession,
    index_path=str(INDEX_PATH),
)

assert annotation is not None
assert annotation.get("sequence")

print("Name:", annotation["protein_name"])
print("Source:", annotation["source"])
print("Sequence length:", annotation["sequence"])
print("Function:", annotation["function"][:2])
print("EC:", annotation["ec_numbers"])

Name: 2' cyclic ADP-D-ribose synthase AbTIR
Source: local_uniprot_swissprot_xml
Sequence length: MSLEQKKGADIISKILQIQNSIGKTTSPSTLKTKLSEISRKEQENARIQSKLSDLQKKKIDIDNKLLKEKQNLIKEEILERKKLEVLTKKQQKDEIEHQKKLKREIDAIKASTQYITDVSISSYNNTIPETEPEYDLFISHASEDKEDFVRPLAETLQQLGVNVWYDEFTLKVGDSLRQKIDSGLRNSKYGTVVLSTDFIKKDWTNYELDGLVAREMNGHKMILPIWHKITKNDVLDYSPNLADKVALNTSVNSIEEIAHQLADVILNR
Function: ["NAD(+) hydrolase (NADase) that catalyzes cleavage of NAD(+) into ADP-D-ribose (ADPR) and nicotinamide (PubMed:29395922). In addition to ADPR, also generates a cyclization variant of cyclic ADPR (cADPR), termed 2'cADPR (v-cADPR) (PubMed:29395922, PubMed:36048923). Cleaves NADP(+), but does not cyclize the product (PubMed:36048923)."]
EC: ['3.2.2.-', '3.2.2.6']

In [10]:
lookup_details, lookup_report = query_protein(
    accession=first_accession,
    query="查询该蛋白的基本性质和已知功能",
    analysis_topics=[
        "sequence_properties",
        "function",
        "catalytic_activity",
        "cofactor",
        "localization",
        "go",
    ],
    allow_online=False,
    save_path=str(OUTPUT_DIR / "accession_lookup.json"),
)

print(lookup_report)

# Protein query and analysis
- Status: ok
- Query mode: accession
- Functional annotation evidence grade: direct_annotation_lookup
- User question: 查询该蛋白的基本性质和已知功能
- Accession: A0A009IHW8
- Sequence length: 269
- Full evidence JSON: /home/data4/xiangyu/BioDSA/workdir/notebook_protein_test/accession_lookup.json

## Sequence-derived properties
- length: 269
- molecular_weight_da: 30921.906
- theoretical_isoelectric_point: 6.99
- aromaticity: 0.052045
- instability_index: 44.952
- gravy: -0.6673
- charge_at_ph7: -0.0178
- Caveat: Sequence-derived estimates assume an unmodified protein and do not account for processing, PTMs, bound ligands, or oligomers.

## Reference-protein evidence

### A0A009IHW8 — 2' cyclic ADP-D-ribose synthase AbTIR
- Organism: Acinetobacter baumannii (strain 1295743)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- function: NAD(+) hydrolase (NADase) that catalyzes cleavage of NAD(+) into ADP-D-ribose (ADPR) and nicotinamide (PubMed:29395922). In addition to ADPR, also generates a cyclization variant of cyclic ADPR (cADPR), termed 2'cADPR (v-cADPR) (PubMed:29395922, PubMed:36048923). Cleaves NADP(+), but does not cyclize the product (PubMed:36048923).
- EC: 3.2.2.-, 3.2.2.6
- Rhea mapping: RHEA:16301, master=16301, direction=UN
- Rhea mapping: RHEA:16302, master=16301, direction=LR
- Rhea mapping: RHEA:19849, master=19849, direction=UN
- Rhea mapping: RHEA:19850, master=19849, direction=LR
- Rhea mapping: RHEA:75299, master=75299, direction=UN
- Rhea mapping: RHEA:75300, master=75299, direction=LR
- GO: GO:0003953 | F:NAD+ nucleosidase activity | evidence=ECO:0000314
- GO: GO:0061809 | F:NAD+ nucleosidase activity, cyclic ADP-ribose generating | evidence=ECO:0000501
- GO: GO:0050135 | F:NADP+ nucleosidase activity | evidence=ECO:0000269
- GO: GO:0019677 | P:NAD+ catabolic process | evidence=ECO:0000314
- GO: GO:0007165 | P:signal transduction | evidence=ECO:0000501

## Candidate catalytic reactions
- NAD(+) = 2'cADPR + nicotinamide + H(+)
  Rhea: RHEA:75299
  Reference accessions: A0A009IHW8
- NAD(+) + H2O = ADP-D-ribose + nicotinamide + H(+)
  Rhea: RHEA:16301
  Reference accessions: A0A009IHW8
- NADP(+) + H2O = ADP-D-ribose 2'-phosphate + nicotinamide + H(+)
  Rhea: RHEA:19849
  Reference accessions: A0A009IHW8

## Module status
- sequence_properties: ok
- homology: not_requested
- annotation: ok
- pfam: not_requested

## Limitations
- Homology-based annotations are predictions for a query, not experimental measurements.
- Reviewed status does not mean every annotation is experimentally validated. Inspect original evidence codes.
- Conserved domains and EC classes may not resolve substrate specificity or distinguish closely related paralogs.
- Reference-protein feature coordinates are not mapped to the query sequence. UniProt/Biopython reference location strings must not be interpreted as query positions.
- Reaction equations alone do not establish detailed mechanisms, kinetic constants, or optimal reaction conditions.
- Rhea TSV files provide mappings; reaction equations here come from UniProt catalytic annotations, not full Rhea RDF parsing.
- Multiple reaction candidates were retrieved. Counts are not independent experimental support; do not choose exact substrates solely by majority vote.
- The text report is truncated for readability. The full JSON contains all retrieved evidence.

In [25]:
self_details, self_report = query_protein(
    sequence='MALVQALPVPCDRPKSSVDIQLCHATSHSPLVPTGGTMGSVSSLISGRTYQERHCCAASDFSGKSRKPTAVAAATSCFRQRDGTLRSTSSQEQLLIHPPAPPTKGRTSALVAAGNGNYSYVGEDVVCDWSDHHAAVCSPCSDSEEPRDNRTVNGNLGGPPPKLIPVSGRLEKNMEKVVIRPTAFKPVVPKNRTSVQYLSPRPGGSLSESQGSLNLLLPGGGAGLVSAEKRNSYSSGRNARSSQSCTMSDSGRNSLSSLPTYSSTGYSLAQSDAPSGHAEPTRAAGSHGHSNSDSGRSSSSKSTGSLSGRGQPLSDTGSCGRSPAPQEGYEVVIRELEEKLRERDLELQQLRDNLDENEAAICQVRNSPSWLQTECWLYVQVYEEKQKRCEQELEELRQTCASRMKLAQQKAQRTQQVLQLQVFQLQQEKKKLQEDFSQLLQERETLEKRCASIEREQTQLGPRLEETKWEVCQKSGEISLLKQQLKDVQAELGQKAAEIVALKAQLREVRSELQANQVCTQEAHAAARTRTLELEVCENELQRRKSEAELLREKVGRLEQESNRLRDALTLPAAAQAALPYSKGQCMSLPLPIGQGRGGGGIARLHSPAHIHSAALRDSEEQLLAYESDEAKAQRQSTDTLHALRQQAERLRAELMYERRRSEEQLEAFDEERRVWQEEKDKVIRYQKQLQQNYIQMYRRNRELERVMRELSLELENRDMEEFDTRNNDIHFEEITATEI\n',
    query="验证序列检索和本地注释关联",
    analysis_topics=[
        "homology",
        "function",
    ],
    allow_online=False,
    max_hits=10,
    max_annotations=3,
    threads=8,
    save_path=str(OUTPUT_DIR / "sequence_self_test.json"),
)

print(self_report)

# Protein query and analysis
- Status: ok
- Query mode: sequence
- Functional annotation evidence grade: moderate_homology_support
- User question: 验证序列检索和本地注释关联
- Sequence length: 740
- Full evidence JSON: /home/data4/xiangyu/BioDSA/workdir/notebook_protein_test/sequence_self_test.json

## Reference-protein evidence

### Q6DIS8 — Leucine zipper putative tumor suppressor 2 homolog
- Organism: Xenopus tropicalis
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=50.0%, query coverage=100.0%, target coverage=100.0%, E-value=5.29e-158
- function: Negative regulator of katanin-mediated microtubule severing and release from the centrosome. Required for central spindle formation and the completion of cytokinesis. Negative regulator of the Wnt signaling pathway. Represses beta-catenin-mediated transcriptional activation by promoting the nuclear exclusion of beta-catenin.

### Q5U4W1 — Leucine zipper putative tumor suppressor 2 homolog
- Organism: Xenopus laevis
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=50.0%, query coverage=100.0%, target coverage=100.0%, E-value=1.22e-154
- function: Negative regulator of katanin-mediated microtubule severing and release from the centrosome. Required for central spindle formation and the completion of cytokinesis. Negative regulator of the Wnt signaling pathway. Represses beta-catenin-mediated transcriptional activation by promoting the nuclear exclusion of beta-catenin.

### Q3LUD4 — Leucine zipper putative tumor suppressor 2
- Organism: Rattus norvegicus
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=42.6%, query coverage=100.0%, target coverage=100.0%, E-value=9.37e-92
- function: Negative regulator of katanin-mediated microtubule severing and release from the centrosome. Required for central spindle formation and the completion of cytokinesis. May negatively regulate axonal outgrowth by preventing the formation of microtubule bundles that are necessary for transport within the elongating axon. Negative regulator of the Wnt signaling pathway. Represses beta-catenin-mediated transcriptional activation by promoting the nuclear exclusion of beta-catenin.

## Module status
- sequence_properties: not_requested
- homology: ok
- annotation: ok
- pfam: not_requested

## Limitations
- Homology-based annotations are predictions for a query, not experimental measurements.
- Reviewed status does not mean every annotation is experimentally validated. Inspect original evidence codes.
- Conserved domains and EC classes may not resolve substrate specificity or distinguish closely related paralogs.
- Reference-protein feature coordinates are not mapped to the query sequence. UniProt/Biopython reference location strings must not be interpreted as query positions.
- Reaction equations alone do not establish detailed mechanisms, kinetic constants, or optimal reaction conditions.
- Rhea TSV files provide mappings; reaction equations here come from UniProt catalytic annotations, not full Rhea RDF parsing.
- The text report is truncated for readability. The full JSON contains all retrieved evidence.

In [12]:
import pandas as pd
from IPython.display import display

HIT_COLUMNS = [
    "accession",
    "identity_percent",
    "query_coverage",
    "target_coverage",
    "evalue",
    "bitscore",
]

hits_df = pd.DataFrame(self_details["search_hits"])

if hits_df.empty:
    print("没有命中，请检查 module_status 和 errors。")
else:
    display(hits_df[HIT_COLUMNS].head(10))

print("Module status:", self_details["module_status"])
print("Errors:", self_details["errors"])

,accession,identity_percent,query_coverage,target_coverage,evalue,bitscore
0,A0A009IHW8,100.0,1.000000,1.000000,4.940000e-159,445.0
1,A0A0P0FGV9,57.2,0.620818,0.602787,1.160000e-61,199.0
2,Q2YPC4,58.7,0.546468,0.600000,2.890000e-50,168.0
3,Q8YF53,58.0,0.546468,0.600000,1.150000e-49,167.0
4,C0RGW8,58.0,0.546468,0.545455,2.310000e-49,167.0
5,A1AY86,48.2,0.624535,0.535117,5.400000e-47,161.0
6,A0A0H2V8B5,56.6,0.501859,0.442997,4.030000e-45,157.0
7,A0A151EH88,51.9,0.494424,0.401216,7.820000e-39,141.0
8,P0DTS9,44.9,0.501859,0.485714,1.190000e-30,118.0
9,A0A1I4KS07,40.6,0.494424,0.387097,4.030000e-29,115.0

Module status: {'sequence_properties': 'not_requested', 'homology': 'ok', 'annotation': 'ok', 'pfam': 'not_requested'}
Errors: []

In [13]:
import json

DATASET_DIR = Path(
    "/home/data4/xiangyu/dataset/Protein-oriented_Instructions"
)


def load_records(path):
    with open(path, encoding="utf-8") as handle:
        try:
            obj = json.load(handle)
        except json.JSONDecodeError:
            handle.seek(0)
            return [
                json.loads(line)
                for line in handle
                if line.strip()
            ]

    if isinstance(obj, list):
        return obj

    if isinstance(obj, dict):
        if "input" in obj:
            return [obj]

        for key in ("data", "train", "examples"):
            if isinstance(obj.get(key), list):
                return obj[key]

    raise ValueError(f"Unsupported dataset structure: {path}")


def find_sample(filename, accession):
    for sample in load_records(DATASET_DIR / filename):
        if (
            sample.get("metadata", {}).get("protein_accession")
            == accession
        ):
            return sample

    raise LookupError(f"Sample not found: {accession}")


catalytic_sample = find_sample(
    "catalytic_activity.json",
    "A0A839SPW3",
)

function_sample = find_sample(
    "general_function.json",
    "B2RXH2",
)

In [14]:
from time import perf_counter

start = perf_counter()

catalytic_details, catalytic_report = query_protein(
    sequence=catalytic_sample["input"],
    query=catalytic_sample["instruction"],
    analysis_topics=[
        "homology",
        "function",
        "catalytic_activity",
        "cofactor",
    ],
    allow_online=False,
    include_pfam=False,
    max_hits=20,
    max_annotations=8,
    threads=8,
    save_path=str(OUTPUT_DIR / "catalytic_activity.json"),
)

print(f"耗时: {perf_counter() - start:.2f} 秒")
print(catalytic_report)

耗时: 14.74 秒
# Protein query and analysis
- Status: ok
- Query mode: sequence
- Functional annotation evidence grade: moderate_homology_support
- User question: Please evaluate the following protein sequence and provide an explanation of the enzyme's catalytic activity, including the chemical reaction it facilitates:
- Sequence length: 495
- Full evidence JSON: /home/data4/xiangyu/BioDSA/workdir/notebook_protein_test/catalytic_activity.json

## Reference-protein evidence

### Q9A595 — UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2,6-diaminopimelate ligase
- Organism: Caulobacter vibrioides (strain ATCC 19089 / CIP 103742 / CB 15)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=54.0%, query coverage=91.9%, target coverage=93.8%, E-value=2.7e-148
- function: Catalyzes the addition of meso-diaminopimelic acid to the nucleotide precursor UDP-N-acetylmuramoyl-L-alanyl-D-glutamate (UMAG) in the biosynthesis of bacterial cell-wall peptidoglycan.
- cofactor: Mg(2+); ChEBI:CHEBI:18420
- EC: 6.3.2.13
- Rhea mapping: RHEA:23676, master=23676, direction=UN

### Q89FU2 — UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2,6-diaminopimelate ligase
- Organism: Bradyrhizobium diazoefficiens (strain JCM 10833 / BCRC 13528 / IAM 13628 / NBRC 14792 / USDA 110)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=53.7%, query coverage=93.3%, target coverage=94.8%, E-value=3.12e-144
- function: Catalyzes the addition of meso-diaminopimelic acid to the nucleotide precursor UDP-N-acetylmuramoyl-L-alanyl-D-glutamate (UMAG) in the biosynthesis of bacterial cell-wall peptidoglycan.
- cofactor: Mg(2+); ChEBI:CHEBI:18420
- EC: 6.3.2.13
- Rhea mapping: RHEA:23676, master=23676, direction=UN

### Q98KA8 — UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2,6-diaminopimelate ligase
- Organism: Mesorhizobium japonicum (strain LMG 29417 / CECT 9101 / MAFF 303099)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=51.9%, query coverage=94.1%, target coverage=95.5%, E-value=3.44e-143
- function: Catalyzes the addition of meso-diaminopimelic acid to the nucleotide precursor UDP-N-acetylmuramoyl-L-alanyl-D-glutamate (UMAG) in the biosynthesis of bacterial cell-wall peptidoglycan.
- cofactor: Mg(2+); ChEBI:CHEBI:18420
- EC: 6.3.2.13
- Rhea mapping: RHEA:23676, master=23676, direction=UN

## Candidate catalytic reactions
- UDP-N-acetyl-alpha-D-muramoyl-L-alanyl-D-glutamate + meso-2,6-diaminopimelate + ATP = UDP-N-acetyl-alpha-D-muramoyl-L-alanyl-gamma-D-glutamyl-meso-2,6-diaminopimelate + ADP + phosphate + H(+)
  Rhea: RHEA:23676
  Reference accessions: Q9A595, Q89FU2, Q98KA8, Q92NL6, Q8UDM3, Q8YI71, Q8FZP0, Q11GS0

## Module status
- sequence_properties: not_requested
- homology: ok
- annotation: ok
- pfam: not_requested

## Limitations
- Homology-based annotations are predictions for a query, not experimental measurements.
- Reviewed status does not mean every annotation is experimentally validated. Inspect original evidence codes.
- Conserved domains and EC classes may not resolve substrate specificity or distinguish closely related paralogs.
- Reference-protein feature coordinates are not mapped to the query sequence. UniProt/Biopython reference location strings must not be interpreted as query positions.
- Reaction equations alone do not establish detailed mechanisms, kinetic constants, or optimal reaction conditions.
- Rhea TSV files provide mappings; reaction equations here come from UniProt catalytic annotations, not full Rhea RDF parsing.
- The text report is truncated for readability. The full JSON contains all retrieved evidence.

In [15]:
for index, reaction in enumerate(
    catalytic_details["reaction_candidates"],
    start=1,
):
    print(f"\n候选反应 {index}")
    print("Equation:", reaction["equation"])
    print("Rhea IDs:", reaction["rhea_ids"])
    print("Reference proteins:", reaction["supporting_accessions"])

if not catalytic_details["reaction_candidates"]:
    print("没有获取到明确反应方程式。")

候选反应 1
Equation: UDP-N-acetyl-alpha-D-muramoyl-L-alanyl-D-glutamate + meso-2,6-diaminopimelate + ATP = UDP-N-acetyl-alpha-D-muramoyl-L-alanyl-gamma-D-glutamyl-meso-2,6-diaminopimelate + ADP + phosphate + H(+)
Rhea IDs: ['23676']
Reference proteins: ['Q9A595', 'Q89FU2', 'Q98KA8', 'Q92NL6', 'Q8UDM3', 'Q8YI71', 'Q8FZP0', 'Q11GS0']

In [16]:
print("参考答案：")
print(catalytic_sample["output"])

参考答案：
By examining the input protein sequence, the enzyme catalyzes the subsequent chemical reaction: ATP + meso-2,6-diaminoheptanedioate + UDP-N-acetyl-alpha-D-   muramoyl-L-alanyl-D-glutamate = ADP + H(+) + phosphate + UDP-N-   acetyl-alpha-D-muramoyl-L-alanyl-gamma-D-glutamyl-meso-2,6-   diaminoheptanedioate.

In [17]:
start = perf_counter()

function_details, function_report = query_protein(
    sequence=function_sample["input"],
    query=function_sample["instruction"],
    analysis_topics=[
        "homology",
        "function",
        "catalytic_activity",
        "cofactor",
        "localization",
        "go",
    ],
    allow_online=False,
    include_pfam=False,
    max_hits=20,
    max_annotations=8,
    threads=8,
    save_path=str(OUTPUT_DIR / "general_function.json"),
)

print(f"耗时: {perf_counter() - start:.2f} 秒")
print(function_report)

耗时: 15.89 秒
# Protein query and analysis
- Status: ok
- Query mode: sequence
- Functional annotation evidence grade: exact_sequence_annotation
- User question: Could you evaluate the protein with this amino acid sequence and present a summary of its features? The sequence is:
- Sequence length: 506
- Full evidence JSON: /home/data4/xiangyu/BioDSA/workdir/notebook_protein_test/general_function.json

## Reference-protein evidence

### B2RXH2 — Lysine-specific demethylase 4E
- Organism: Homo sapiens
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=100.0%, query coverage=100.0%, target coverage=100.0%, E-value=0
- Exact reference sequence hash match: yes
- function: Histone demethylase that demethylates trimethylated 'Lys-9' of histone H3 into monomethylated form, thereby playing a central role in histone code (PubMed:21914792, PubMed:23451023). Also demethylates trimethylated 'Lys-56' of histone H3 (H3K9me3) to generate the monomethylated state (H3K56me1) (PubMed:23451023).
- cofactor: Fe(2+); Binds 1 Fe(2+) ion per subunit.; ChEBI:CHEBI:29033
- localization: Nucleus
- EC: 1.14.11.-, 1.14.11.66
- Rhea mapping: RHEA:60192, master=60192, direction=UN
- Rhea mapping: RHEA:60193, master=60192, direction=LR
- Rhea mapping: RHEA:60200, master=60200, direction=UN
- Rhea mapping: RHEA:60204, master=60204, direction=UN
- Rhea mapping: RHEA:60205, master=60204, direction=LR
- Rhea mapping: RHEA:85927, master=85927, direction=UN
- Rhea mapping: RHEA:85928, master=85927, direction=LR
- Rhea mapping: RHEA:85931, master=85931, direction=UN
- GO: GO:0000785 | C:chromatin | evidence=ECO:0000318
- GO: GO:0005654 | C:nucleoplasm | evidence=ECO:0000304
- GO: GO:0005634 | C:nucleus | evidence=ECO:0000314
- GO: GO:0140760 | F:histone H3K56me2/H3K56me3 demethylase activity | evidence=ECO:0000314
- GO: GO:0032454 | F:histone H3K9 demethylase activity | evidence=ECO:0000318
- GO: GO:0140684 | F:histone H3K9me2/H3K9me3 demethylase activity | evidence=ECO:0000314

### A0A1W2PPD8 — Probable lysine-specific demethylase 4F
- Organism: Homo sapiens
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=83.3%, query coverage=99.4%, target coverage=76.2%, E-value=3.17e-297
- function: Probable histone demethylase that specifically demethylates 'Lys-9' of histone H3, thereby playing a central role in histone code.
- cofactor: Fe(2+); Binds 1 Fe(2+) ion per subunit.; ChEBI:CHEBI:29033
- localization: Nucleus
- EC: 1.14.11.66
- Rhea mapping: RHEA:60200, master=60200, direction=UN
- GO: GO:0000785 | C:chromatin | evidence=ECO:0000318
- GO: GO:0005634 | C:nucleus | evidence=ECO:0000501
- GO: GO:0032454 | F:histone H3K9 demethylase activity | evidence=ECO:0000318
- GO: GO:0140684 | F:histone H3K9me2/H3K9me3 demethylase activity | evidence=ECO:0000250

### Q6B0I6 — Lysine-specific demethylase 4D
- Organism: Homo sapiens
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=67.0%, query coverage=98.6%, target coverage=93.9%, E-value=5.77e-234
- function: Histone demethylase that specifically demethylates 'Lys-9' of histone H3, thereby playing a central role in histone code. Does not demethylate histone H3 'Lys-4', H3 'Lys-27', H3 'Lys-36' nor H4 'Lys-20'. Demethylates both di- and trimethylated H3 'Lys-9' residue, while it has no activity on monomethylated residues. Demethylation of Lys residue generates formaldehyde and succinate.
- cofactor: Fe(2+); Binds 1 Fe(2+) ion per subunit.; ChEBI:CHEBI:29033
- localization: Nucleus
- EC: 1.14.11.66
- Rhea mapping: RHEA:60200, master=60200, direction=UN
- GO: GO:0072562 | C:blood microparticle | evidence=ECO:0007005
- GO: GO:0000785 | C:chromatin | evidence=ECO:0000318
- GO: GO:0005654 | C:nucleoplasm | evidence=ECO:0000304
- GO: GO:0005634 | C:nucleus | evidence=ECO:0000269
- GO: GO:0005721 | C:pericentric heterochromatin | evidence=ECO:0000501
- GO: GO:0035861 | C:site of double-strand break | evidence=ECO:0000314
- GO: GO:0031490 | F:chromatin DNA binding | evidence=ECO:0000501
- GO: GO:0003684 | F:damaged DNA binding | evidence=ECO:0000501
- GO: GO:0032452 | F:histone demethylase activity | evidence=ECO:0000304
- GO: GO:0032454 | F:histone H3K9 demethylase activity | evidence=ECO:0000314
- GO: GO:0140684 | F:histone H3K9me2/H3K9me3 demethylase activity | evidence=ECO:0000314
- GO: GO:0071479 | P:cellular response to ionizing radiation | evidence=ECO:0000315
- GO: GO:0000724 | P:double-strand break repair via homologous recombination | evidence=ECO:0000315
- GO: GO:0006954 | P:inflammatory response | evidence=ECO:0000314
- GO: GO:0035563 | P:positive regulation of chromatin binding | evidence=ECO:0000315

## Candidate catalytic reactions
- N(6),N(6),N(6)-trimethyl-L-lysyl(9)-[histone H3] + 2 2-oxoglutarate + 2 O2 = N(6)-methyl-L-lysyl(9)-[histone H3] + 2 formaldehyde + 2 succinate + 2 CO2
  Rhea: RHEA:15538, RHEA:15542, RHEA:60200
  Reference accessions: B2RXH2, A0A1W2PPD8, Q6B0I6, Q3U2K5, A1A5Q5
- N(6),N(6),N(6)-trimethyl-L-lysyl(9)-[histone H3] + 2-oxoglutarate + O2 = N(6),N(6)-dimethyl-L-lysyl(9)-[histone H3] + formaldehyde + succinate + CO2
  Rhea: RHEA:15538, RHEA:15541, RHEA:60204
  Reference accessions: B2RXH2
- N(6),N(6)-dimethyl-L-lysyl(9)-[histone H3] + 2-oxoglutarate + O2 = N(6)-methyl-L-lysyl(9)-[histone H3] + formaldehyde + succinate + CO2
  Rhea: RHEA:15541, RHEA:15542, RHEA:60192
  Reference accessions: B2RXH2
- N(6),N(6),N(6)-trimethyl-L-lysyl(56)-[histone H3] + 2-oxoglutarate + O2 = N(6),N(6)-dimethyl-L-lysyl(56)-[histone H3] + formaldehyde + succinate + CO2
  Rhea: RHEA:20683, RHEA:20684, RHEA:85927
  Reference accessions: B2RXH2
- N(6),N(6)-dimethyl-L-lysyl(56)-[histone H3] + 2-oxoglutarate + O2 = N(6)-methyl-L-lysyl(56)-[histone H3] + formaldehyde + succinate + CO2
  Rhea: RHEA:20682, RHEA:20684, RHEA:85931
  Reference accessions: B2RXH2

## Module status
- sequence_properties: not_requested
- homology: ok
- annotation: ok
- pfam: not_requested

## Limitations
- Homology-based annotations are predictions for a query, not experimental measurements.
- Reviewed status does not mean every annotation is experimentally validated. Inspect original evidence codes.
- Conserved domains and EC classes may not resolve substrate specificity or distinguish closely related paralogs.
- Reference-protein feature coordinates are not mapped to the query sequence. UniProt/Biopython reference location strings must not be interpreted as query positions.
- Reaction equations alone do not establish detailed mechanisms, kinetic constants, or optimal reaction conditions.
- Rhea TSV files provide mappings; reaction equations here come from UniProt catalytic annotations, not full Rhea RDF parsing.
- Multiple reaction candidates were retrieved. Counts are not independent experimental support; do not choose exact substrates solely by majority vote.
- The text report is truncated for readability. The full JSON contains all retrieved evidence.

In [18]:
rows = []

for evidence in function_details["evidence"]:
    reference = evidence["annotation"]
    alignment = evidence.get("alignment") or {}

    rows.append({
        "accession": reference["accession"],
        "protein_name": reference.get("protein_name"),
        "identity_percent": alignment.get("identity_percent"),
        "query_coverage": alignment.get("query_coverage"),
        "target_coverage": alignment.get("target_coverage"),
        "exact_sequence_match": evidence.get("exact_sequence_match"),
        "function": "\n".join(reference.get("function", [])),
    })

display(pd.DataFrame(rows))

print("\n参考答案：")
print(function_sample["output"])

,accession,protein_name,identity_percent,query_coverage,target_coverage,exact_sequence_match,function
0,B2RXH2,Lysine-specific demethylase 4E,100.0,1.000000,1.000000,True,Histone demethylase that demethylates trimethy...
1,A0A1W2PPD8,Probable lysine-specific demethylase 4F,83.3,0.994071,0.761755,False,Probable histone demethylase that specifically...
2,Q6B0I6,Lysine-specific demethylase 4D,67.0,0.986166,0.938815,False,Histone demethylase that specifically demethyl...
3,Q3U2K5,Lysine-specific demethylase 4D,72.3,0.796443,0.792157,False,Histone demethylase that specifically demethyl...
4,A1A5Q5,Lysine-specific demethylase 4D,77.7,0.709486,0.703922,False,Histone demethylase that specifically demethyl...

参考答案：
A short report on the protein with the given amino acid sequence highlights: Histone demethylase that specifically demethylates 'Lys-9' of histone H3, thereby playing a central role in histone code.

In [20]:
import requests
from time import perf_counter

TEST_ACCESSION = "P69905"  # 人血红蛋白 alpha 链
url = f"https://rest.uniprot.org/uniprotkb/{TEST_ACCESSION}.txt"

start = perf_counter()

try:
    response = requests.get(
        url,
        timeout=(10, 40),
        headers={"User-Agent": "BioDSA-Protein-Network-Test/1.0"},
    )

    print("HTTP status:", response.status_code)
    print("Final URL:", response.url)
    print("Elapsed:", round(perf_counter() - start, 2), "seconds")
    print("Response bytes:", len(response.content))
    print("\nResponse preview:")
    print(response.text[:800])

    response.raise_for_status()

except requests.RequestException as exc:
    print("Network test failed:", type(exc).__name__, str(exc))

HTTP status: 200
Final URL: https://rest.uniprot.org/uniprotkb/P69905.txt
Elapsed: 1.11 seconds
Response bytes: 121015

Response preview:
ID   HBA_HUMAN               Reviewed;         142 AA.
AC   P69905; P01922; Q1HDT5; Q3MIF5; Q53F97; Q96KF1; Q9NYR7; Q9UCM0;
DT   21-JUL-1986, integrated into UniProtKB/Swiss-Prot.
DT   23-JAN-2007, sequence version 2.
DT   02-SEP-2026, entry version 219.
DE   RecName: Full=Hemoglobin subunit alpha;
DE   AltName: Full=Alpha-globin;
DE   AltName: Full=Hemoglobin alpha chain;
DE   Contains:
DE     RecName: Full=Hemopressin {ECO:0000303|PubMed:18077343};
GN   Name=HBA1;
GN   and
GN   Name=HBA2;
OS   Homo sapiens (Human).
OC   Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Euteleostomi; Mammalia;
OC   Eutheria; Euarchontoglires; Primates; Haplorrhini; Catarrhini; Hominidae;
OC   Homo.
OX   NCBI_TaxID=9606;
RN   [1]
RP   NUCLEOTIDE SEQUENCE [GENOMIC DNA] (HBA1).
RX   PubMed=7448866; DOI=10.

In [21]:
from biodsa.tools.protein.protein import fetch_online_annotation

start = perf_counter()

online_annotation = fetch_online_annotation(TEST_ACCESSION)

print("Elapsed:", round(perf_counter() - start, 2), "seconds")

if online_annotation is None:
    print("在线查询失败，请检查上方日志。")
else:
    print("Accession:", online_annotation["accession"])
    print("Name:", online_annotation["protein_name"])
    print("Organism:", online_annotation["organism"])
    print("Source:", online_annotation["source"])
    print("Source URL:", online_annotation.get("source_url"))
    print("Retrieved at:", online_annotation.get("retrieved_at"))
    print("Sequence length:", online_annotation["sequence_length"])
    print("Function:", online_annotation["function"][:2])

Elapsed: 1.1 seconds
Accession: P69905
Name: RecName: Full=Hemoglobin subunit alpha; AltName: Full=Alpha-globin; AltName: Full=Hemoglobin alpha chain; Contains: RecName: Full=Hemopressin {ECO:0000303|PubMed:18077343};
Organism: Homo sapiens (Human).
Source: uniprot_rest
Source URL: https://rest.uniprot.org/uniprotkb/P69905.txt
Retrieved at: 2026-10-12T12:39:41.551381+00:00
Sequence length: 142
Function: ['Involved in oxygen transport from the lung to the various peripheral tissues.', '[Hemopressin]: Hemopressin acts as an antagonist peptide of the cannabinoid receptor CNR1 (PubMed:18077343). Hemopressin-binding efficiently blocks cannabinoid receptor CNR1 and subsequent signaling (PubMed:18077343). {ECO:0000269|PubMed:18077343}.']

In [22]:
sequence = """
MQENFSPDEQFAFNLDARDPLSKYKNKFYIPKNSKGEEIIYFCGNSLGLQPKTVAAAIDQELIDWANLGVEGHTQAKNPWLPYHELLTEKMAEIVGAKPIEVVIMNTLTANLHLMMVSFYQPTKKRHKILIESDAFPSDKFAVASQIKHHGFNPKDSIVYWQPKKGKNLLDYDDFENILKKHGQEIALVMLGSVNYYTGQFFNLKKITRLAHSYGCKVGFDCAHGAGNVNLDLHRSRADFAVWCTYKYLNSGPGSLAGCFVHERHAYNKNLNRFTGWWGHNKQTRFKMRDEFDQLPGAEGWQLSNPPILSMAAIKASLKIFKEAGMKNLINKSNKLTAYFEYLINEINNPKIKIITPSDPKQRGCQLSIQVKNSDKTLFKKLTDSGVITDWREPDVIRCAPVPLYNSYTDIFNMVKKLKNCLHE
"""
from pathlib import Path
from time import perf_counter

from biodsa.tools.protein import query_protein

output_dir = Path(
    "/home/data4/xiangyu/BioDSA/workdir/notebook_protein_test"
)
output_dir.mkdir(parents=True, exist_ok=True)

start = perf_counter()

details, report = query_protein(
    sequence=sequence,
    query="根据序列查询该蛋白的主要功能和催化活性",
    analysis_topics=[
        "homology",
        "function",
        "catalytic_activity",
        "cofactor",
        "pathway",
    ],
    allow_online=False,
    max_hits=20,
    max_annotations=8,
    threads=8,
    save_path=str(output_dir / "kynureninase_test.json"),
)

print(f"耗时：{perf_counter() - start:.2f} 秒")
print(report)

耗时：13.94 秒
# Protein query and analysis
- Status: ok
- Query mode: sequence
- Functional annotation evidence grade: moderate_homology_support
- User question: 根据序列查询该蛋白的主要功能和催化活性
- Sequence length: 424
- Full evidence JSON: /home/data4/xiangyu/BioDSA/workdir/notebook_protein_test/kynureninase_test.json

## Reference-protein evidence

### Q1DDU5 — Kynureninase
- Organism: Myxococcus xanthus (strain DK1622)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=55.7%, query coverage=99.1%, target coverage=98.6%, E-value=1.06e-179
- function: Catalyzes the cleavage of L-kynurenine (L-Kyn) and L-3-hydroxykynurenine (L-3OHKyn) into anthranilic acid (AA) and 3-hydroxyanthranilic acid (3-OHAA), respectively.
- cofactor: pyridoxal 5'-phosphate; ChEBI:CHEBI:597326
- pathway: Amino-acid degradation; L-kynurenine degradation; L-alanine and anthranilate from L-kynurenine: step 1/1.
- pathway: Cofactor biosynthesis; NAD(+) biosynthesis; quinolinate from L-kynurenine: step 2/3.
- EC: 3.7.1.3
- Rhea mapping: RHEA:16813, master=16813, direction=UN
- Rhea mapping: RHEA:25143, master=25143, direction=UN

### Q1ITW5 — Kynureninase
- Organism: Koribacter versatilis (strain Ellin345)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=53.5%, query coverage=97.4%, target coverage=97.4%, E-value=8.99e-171
- function: Catalyzes the cleavage of L-kynurenine (L-Kyn) and L-3-hydroxykynurenine (L-3OHKyn) into anthranilic acid (AA) and 3-hydroxyanthranilic acid (3-OHAA), respectively.
- cofactor: pyridoxal 5'-phosphate; ChEBI:CHEBI:597326
- pathway: Amino-acid degradation; L-kynurenine degradation; L-alanine and anthranilate from L-kynurenine: step 1/1.
- pathway: Cofactor biosynthesis; NAD(+) biosynthesis; quinolinate from L-kynurenine: step 2/3.
- EC: 3.7.1.3
- Rhea mapping: RHEA:16813, master=16813, direction=UN
- Rhea mapping: RHEA:25143, master=25143, direction=UN

### A6H1P7 — Kynureninase
- Organism: Flavobacterium psychrophilum (strain ATCC 49511 / DSM 21280 / CIP 103535 / JIP02/86)
- Reviewed: True
- Source: local_uniprot_swissprot_xml
- Homology: identity=51.2%, query coverage=97.9%, target coverage=98.1%, E-value=2.37e-161
- function: Catalyzes the cleavage of L-kynurenine (L-Kyn) and L-3-hydroxykynurenine (L-3OHKyn) into anthranilic acid (AA) and 3-hydroxyanthranilic acid (3-OHAA), respectively.
- cofactor: pyridoxal 5'-phosphate; ChEBI:CHEBI:597326
- pathway: Amino-acid degradation; L-kynurenine degradation; L-alanine and anthranilate from L-kynurenine: step 1/1.
- pathway: Cofactor biosynthesis; NAD(+) biosynthesis; quinolinate from L-kynurenine: step 2/3.
- EC: 3.7.1.3
- Rhea mapping: RHEA:16813, master=16813, direction=UN
- Rhea mapping: RHEA:25143, master=25143, direction=UN

## Candidate catalytic reactions
- L-kynurenine + H2O = anthranilate + L-alanine + H(+)
  Rhea: RHEA:16813
  Reference accessions: Q1DDU5, Q1ITW5, A6H1P7, B1KJM4, A0M4Y1, A5FMM4, A7SCH8, B2FL97
- 3-hydroxy-L-kynurenine + H2O = 3-hydroxyanthranilate + L-alanine + H(+)
  Rhea: RHEA:25143
  Reference accessions: Q1DDU5, Q1ITW5, A6H1P7, B1KJM4, A0M4Y1, A5FMM4, A7SCH8, B2FL97

## Module status
- sequence_properties: not_requested
- homology: ok
- annotation: ok
- pfam: not_requested

## Limitations
- Homology-based annotations are predictions for a query, not experimental measurements.
- Reviewed status does not mean every annotation is experimentally validated. Inspect original evidence codes.
- Conserved domains and EC classes may not resolve substrate specificity or distinguish closely related paralogs.
- Reference-protein feature coordinates are not mapped to the query sequence. UniProt/Biopython reference location strings must not be interpreted as query positions.
- Reaction equations alone do not establish detailed mechanisms, kinetic constants, or optimal reaction conditions.
- Rhea TSV files provide mappings; reaction equations here come from UniProt catalytic annotations, not full Rhea RDF parsing.
- Multiple reaction candidates were retrieved. Counts are not independent experimental support; do not choose exact substrates solely by majority vote.
- The text report is truncated for readability. The full JSON contains all retrieved evidence.

In [23]:
import json
from pathlib import Path
from pprint import pprint

DATASET_PATH = Path(
    "/home/data4/xiangyu/dataset/Protein-oriented_Instructions/"
    "general_function.json"
)


def load_json_or_jsonl(path):
    with open(path, encoding="utf-8") as f:
        try:
            obj = json.load(f)
        except json.JSONDecodeError:
            f.seek(0)
            return [
                json.loads(line)
                for line in f
                if line.strip()
            ]

    if isinstance(obj, list):
        return obj

    if isinstance(obj, dict):
        if "input" in obj:
            return [obj]

        for key in ["data", "train", "test", "examples"]:
            if isinstance(obj.get(key), list):
                return obj[key]

    raise ValueError(f"Unsupported dataset format: {path}")


records = load_json_or_jsonl(DATASET_PATH)

test_records = [
    record
    for record in records
    if record.get("split") == "test"
    or record.get("metadata", {}).get("split") == "test"
]

print("总样本数:", len(records))
print("test 样本数:", len(test_records))

总样本数: 86572
test 样本数: 2633

In [24]:
if not test_records:
    print("没有找到 split=test 的数据")
else:
    sample = test_records[0]
    pprint(sample, sort_dicts=False)

{'instruction': 'Assess the following protein sequence and provide a brief '
                'report on its primary characteristics: ',
 'input': '```\n'
          'MALVQALPVPCDRPKSSVDIQLCHATSHSPLVPTGGTMGSVSSLISGRTYQERHCCAASDFSGKSRKPTAVAAATSCFRQRDGTLRSTSSQEQLLIHPPAPPTKGRTSALVAAGNGNYSYVGEDVVCDWSDHHAAVCSPCSDSEEPRDNRTVNGNLGGPPPKLIPVSGRLEKNMEKVVIRPTAFKPVVPKNRTSVQYLSPRPGGSLSESQGSLNLLLPGGGAGLVSAEKRNSYSSGRNARSSQSCTMSDSGRNSLSSLPTYSSTGYSLAQSDAPSGHAEPTRAAGSHGHSNSDSGRSSSSKSTGSLSGRGQPLSDTGSCGRSPAPQEGYEVVIRELEEKLRERDLELQQLRDNLDENEAAICQVRNSPSWLQTECWLYVQVYEEKQKRCEQELEELRQTCASRMKLAQQKAQRTQQVLQLQVFQLQQEKKKLQEDFSQLLQERETLEKRCASIEREQTQLGPRLEETKWEVCQKSGEISLLKQQLKDVQAELGQKAAEIVALKAQLREVRSELQANQVCTQEAHAAARTRTLELEVCENELQRRKSEAELLREKVGRLEQESNRLRDALTLPAAAQAALPYSKGQCMSLPLPIGQGRGGGGIARLHSPAHIHSAALRDSEEQLLAYESDEAKAQRQSTDTLHALRQQAERLRAELMYERRRSEEQLEAFDEERRVWQEEKDKVIRYQKQLQQNYIQMYRRNRELERVMRELSLELENRDMEEFDTRNNDIHFEEITATEI\n'
          '```',
 'output': 'A short report on the protein with the given amino acid sequence '
           'highlights: Negative regulator of katanin-mediated microtubule '
           'severing and release from the centrosome. Required for central '
           'spindle formation and the completion of cytokinesis. Negative '
           'regulator of the Wnt signaling pathway. Represses '
           'beta-catenin-mediated transcriptional activation by promoting the '
           'nuclear exclusion of beta-catenin.',
 'metadata': {'protein_accession': 'A0A4W4G411',
              'num_tokens_in_input': 748,
              'seq_len': 740,
              'task': 'general_function',
              'annots': 'Negative regulator of katanin-mediated microtubule '
                        'severing and release from the centrosome. Required '
                        'for central spindle formation and the completion of '
                        'cytokinesis. Negative regulator of the Wnt signaling '
                        'pathway. Represses beta-catenin-mediated '
                        'transcriptional activation by promoting the nuclear '
                        'exclusion of beta-catenin.',
              'split': 'test'}}

In [4]:
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.Chem import Crippen, Descriptors, Lipinski
import json

def predict_esol(smiles: str) -> str:
    """
    Delaney ESOL aqueous solubility prediction.

    Returns:
        {"answer": <predicted LogS>}
    """

    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        return json.dumps({"answer": "Invalid SMILES"})

    # Molecular weight
    mw = Descriptors.MolWt(mol)

    # Wildman-Crippen logP
    logp = Crippen.MolLogP(mol)

    # Rotatable bonds
    rotors = Lipinski.NumRotatableBonds(mol)

    # Aromatic proportion
    heavy_atoms = mol.GetNumHeavyAtoms()

    aromatic_atoms = sum(
        atom.GetIsAromatic()
        for atom in mol.GetAtoms()
    )

    ap = aromatic_atoms / heavy_atoms if heavy_atoms else 0.0

    # Delaney ESOL
    #
    # logS =
    # 0.16
    # - 1.5 * logP
    # - 0.01 * (MW - 40)
    # + 0.066 * RB
    # + 0.066 * AP
    #
    # NOTE:
    # Use the exact implementation/coefficients required
    # by the benchmark if its GT was generated by a
    # particular ESOL implementation.

    logS = (
        0.16
        - 1.5 * logp
        - 0.01 * (mw - 40.0)
        + 0.066 * rotors
        + 0.066 * ap
    )

    return json.dumps({
        "answer": round(logS, 3)
    })

# 测试你题目中的分子 (雌酮)
print(predict_esol("CCCCNC(=O)N1C(NC(=O)OC)=NC2=CC=CC=C21"))
# 输出: {"answer": -3.816}

{"answer": -5.91}

In [1]:
import os
from biodsa.tools.chemical.chemicals import (
    fetch_molecule_profile_fast,
    fetch_chembl_target_bioactivity,
    compute_quantum_properties_slow,
    fetch_reaction_conditions_unified
)

# def run_tests():
#     print("🚀 开始本地测试化学工具链...\n" + "="*50)

#     # ==========================================
#     # 测试 1: 极速分子画像 (测试不规范输入解析、RDKit计算与PubChem安全警告)
#     # ==========================================
#     print("\n[测试 1] 快速分子画像 - 输入: 'Aspirin' (俗名)")
#     # 期望：PubChem自动将Aspirin转为SMILES，算出分子量，提取出羧酸/酯基，并报出GHS警告(如吞食有害)
#     details, output = fetch_molecule_profile_fast(identifier="Aspirin")
#     print(output)
#     print("="*50)

#     # ==========================================
#     # 测试 2: ChEMBL 靶点与药理学检索 (测试生物活性联网 API)
#     # ==========================================
#     print("\n[测试 2] ChEMBL 靶点检索 - 输入: 'Imatinib' (著名抗癌药 伊马替尼/格列卫)")
#     # 期望：识别出处于最高临床阶段 (Approved)，并列出它的主要靶点 (如 BCR-ABL, KIT 激酶抑制剂)
#     details, output = fetch_chembl_target_bioactivity(identifier="Imatinib")
#     print(output)
#     print("="*50)

#     # ==========================================
#     # 测试 3: 量子属性计算 (测试本地 QM9 查询或 PySCF 触发)
#     # ==========================================
#     print("\n[测试 3] 量子属性查询 - 输入: 'c1ccccc1' (苯环 SMILES)")
#     # 期望：由于苯是常见小分子，应瞬间在 QM9 中命中并返回 HOMO/LUMO 能量。
#     # (如果输入的是罕见大分子，则会触发 PySCF 计算，请耐心等待)
#     details, output = compute_quantum_properties_slow(smiles="c1ccccccc1")
#     print(output)
#     print("="*50)

#     print("✅ 全部本地测试执行完毕！")

# if __name__ == "__main__":
#     run_tests()

In [6]:
import sqlite3

# 替换为你的数据库实际路径
ORD_DB_PATH = "/home/data4/xiangyu/dataset/chemistry_knowledgebase/ORD/ord-data/ord_nlp_lite.db"

def inspect_database():
    try:
        with sqlite3.connect(ORD_DB_PATH) as conn:
            conn.row_factory = sqlite3.Row
            cur = conn.cursor()

            # 1. 查看 reaction_conditions 表的字段
            print("========== [reaction_conditions] 表字段 (Schema) ==========")
            cur.execute("PRAGMA table_info(reaction_conditions);")
            for row in cur.fetchall():
                print(f"- {row['name']} ({row['type']})")

            # 2. 查看 reaction_components 表的字段
            print("\n========== [reaction_components] 表字段 (Schema) ==========")
            cur.execute("PRAGMA table_info(reaction_components);")
            for row in cur.fetchall():
                print(f"- {row['name']} ({row['type']})")

            # 3. 抽取 reaction_conditions 的 1 条样例数据
            print("\n========== [reaction_conditions] 样例数据 ==========")
            cur.execute("SELECT * FROM reaction_conditions WHERE reaction_smiles IS NOT NULL LIMIT 1;")
            row = cur.fetchone()
            if row:
                for key in row.keys():
                    # 截断太长的字符串方便查看
                    val = str(row[key])
                    if len(val) > 100: val = val[:100] + "..."
                    print(f"{key}: {val}")
            else:
                print("未找到数据")

            # 4. 抽取同一个反应的 reaction_components 样例数据
            if row:
                reaction_id = row["reaction_id"]
                print(f"\n========== [reaction_components] 样例数据 (Reaction ID: {reaction_id}) ==========")
                cur.execute("SELECT * FROM reaction_components WHERE reaction_id = ? LIMIT 5;", (reaction_id,))
                for c_row in cur.fetchall():
                    print(dict(c_row))

    except Exception as e:
        print(f"数据库连接或查询失败: {e}")

if __name__ == "__main__":
    inspect_database()

========== [reaction_conditions] 表字段 (Schema) ==========
- reaction_id (TEXT)
- reaction_smiles (TEXT)
- reactants_smiles (TEXT)
- target_product_smiles (TEXT)
- yield_percent (REAL)
- temperature_celsius (REAL)
- time_hours (REAL)
- solvents (TEXT)

========== [reaction_components] 表字段 (Schema) ==========
- component_id (INTEGER)
- reaction_id (TEXT)
- component_type (TEXT)
- reaction_role (TEXT)
- compound_name (TEXT)
- smiles (TEXT)

========== [reaction_conditions] 样例数据 ==========
reaction_id: ord-7e752aaa3e064b9982580b386ed1bacf
reaction_smiles: CC1=CC=C(N)N=C1.[C-]#[N+]C1CCCCC1.OC1=CC=C2C=CC=CC2=C1C=O>>CC1=CN2C(C=C1)=NC(=C2NC1CCCCC1)C1=C(O)C=C...
reactants_smiles: Cc1ccc(N)nc1.O=Cc1c(O)ccc2ccccc12.[C-]#[N+]C1CCCCC1
target_product_smiles: Cc1ccc2nc(c3c(ccc4ccccc34)O)c(NC3CCCCC3)n2c1
yield_percent: 0.0
temperature_celsius: 22.0
time_hours: 20.0
solvents: ["isopropyl alcohol","isopropylalcohol"]

========== [reaction_components] 样例数据 (Reaction ID: ord-7e752aaa3e064b9982580b386ed1bacf) ==========
{'component_id': 8800, 'reaction_id': 'ord-7e752aaa3e064b9982580b386ed1bacf', 'component_type': 'input', 'reaction_role': 'REACTANT', 'compound_name': None, 'smiles': 'CC1=CN=C(C=C1)N'}
{'component_id': 8801, 'reaction_id': 'ord-7e752aaa3e064b9982580b386ed1bacf', 'component_type': 'input', 'reaction_role': 'REACTANT', 'compound_name': None, 'smiles': '[C-]#[N+]C1CCCCC1'}
{'component_id': 8802, 'reaction_id': 'ord-7e752aaa3e064b9982580b386ed1bacf', 'component_type': 'input', 'reaction_role': 'CATALYST', 'compound_name': 'trifluoroacetic acid', 'smiles': 'O=C(O)C(F)(F)F'}
{'component_id': 8803, 'reaction_id': 'ord-7e752aaa3e064b9982580b386ed1bacf', 'component_type': 'input', 'reaction_role': 'SOLVENT', 'compound_name': 'isopropylalcohol', 'smiles': 'CC(C)O'}
{'component_id': 8804, 'reaction_id': 'ord-7e752aaa3e064b9982580b386ed1bacf', 'component_type': 'input', 'reaction_role': 'REACTANT', 'compound_name': None, 'smiles': 'C(c1c(ccc2ccccc12)O)=O'}

In [2]:
def test_ord_reaction_query():
    reaction = (
        "[O][=C][C][=C][C][Branch1][=Branch1][N+1][=Branch1][C][=O][O-1][=C][Branch1][C][F][C][=C][Ring1][#Branch2][F].[C][C][C][O][C][Ring1][Branch1].[Cl].[BH4-1].[Na+1]"
    )

    details, output = fetch_reaction_conditions_unified(
        reaction_smiles=reaction,
        limit=5,
    )

    print(output)

    assert isinstance(details, list)
    assert isinstance(output, str)


if __name__ == "__main__":
    test_ord_reaction_query()

# Reaction Conditions Search Results

## Query: `[O][=C][C][=C][C][Branch1][=Branch1][N+1][=Branch1][C][=O][O-1][=C][Branch1][C][F][C][=C][Ring1][#Branch2][F].[C][C][C][O][C][Ring1][Branch1].[Cl].[BH4-1].[Na+1]`

### Input Standardization Log:
**Reactants Resolution:**
**Decoded SELFIES:** `O=CC1=CC([N+1](=O)[O-1])=C(F)C=C1F`
**Decoded SELFIES:** `C1CCOC1`

---

*[Fuzzy Fallback] Found related records via fuzzy string scan (Slow Match):* `O=Cc1cc([N+](=O)[O-])c(F)cc1F`

### Found 1 matching records

**Record 1**
- **Reaction ID:** ord-80136ac3aec04c958d9cd3cebb668e3a
- **Full Reaction SMILES:** `[F:1][C:2]1[CH:9]=[C:8]([F:10])[C:7]([N+:11]([O-:13])=[O:12])=[CH:6][C:3]=1[CH:4]=[O:5].[BH4-].[Na+].Cl>O1CCCC1>[F:1][C:2]1[CH:9]=[C:8]([F:10])[C:7]([N+:11]([O-:13])=[O:12])=[CH:6][C:3]=1[CH2:4][OH:5] |f:1.2|`
- **Reactants SMILES:** `Cl.O=Cc1cc([N+](=O)[O-])c(F)cc1F.[BH4-].[Na+]`
- **Target Product SMILES:** `FC1=C(CO)C=C(C(=C1)F)[N+](=O)[O-]`
- **Target Product SELFIES:** `[F][C][=C][Branch1][Ring1][C][O][C][=C][Branch1][Branch2][C][=Branch1][Ring2][=C][Ring1][Branch2][F][N+1][=Branch1][C][=O][O-1]`
- **Yield:** 75.2%
- **Time:** 5.00 hours
- **Solvents:** tetrahydrofuran
- **Reagents/Catalysts:** tetrahydrofuran (SOLVENT)

In [ ]:
import selfies as sf
from rdkit import Chem
from rdkit.Chem import AllChem
from pyscf import gto, scf

def calculate_lumo_from_selfies(selfies_str):
    # 1. 格式转换：SELFIES -> SMILES
    smiles = sf.decoder(selfies_str)
    
    # 2. RDKit 生成 3D 坐标
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol) # 必须加氢原子才能进行量子计算
    
    # 嵌入 3D 坐标并进行分子力场初步优化 (MMFF94)
    AllChem.EmbedMolecule(mol, randomSeed=42)
    AllChem.MMFFOptimizeMolecule(mol)
    
    # 3. 将 RDKit 的坐标提取为 PySCF 能读懂的格式
    xyz = []
    for atom in mol.GetAtoms():
        pos = mol.GetConformer().GetAtomPosition(atom.GetIdx())
        xyz.append(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    pyscf_geom = "\n".join(xyz)
    
    # 4. PySCF 密度泛函理论 (DFT) 计算
    # 这里我们使用 B3LYP 泛函和 6-31G* 基组 (与 QM9 类似)
    print("开始运行 DFT 计算，请稍候...")
    pyscf_mol = gto.M(atom=pyscf_geom, basis='6-31g*', verbose=0)
    mf = scf.RKS(pyscf_mol)
    mf.xc = 'b3lyp'
    mf.kernel() # 执行自洽场计算
    
    # 5. 提取 LUMO 能量
    # 分子轨道按能量排序，寻找刚好没有电子填充的那个轨道
    lumo_idx = pyscf_mol.nelectron // 2  
    lumo_energy = mf.mo_energy[lumo_idx] # 单位: Hartree
    
    return lumo_energy

# 测试你提问过的分子
test_selfies = "[C][C][=Branch1][C][=O][N][C][=Branch1][C][=O][O][C][O][Ring1][=Branch2]"
print("计算出的 LUMO (Hartree):", calculate_lumo_from_selfies(test_selfies))

开始运行 DFT 计算，请稍候...

计算出的 LUMO (Hartree): 0.8594666575449955

In [ ]:
from rdkit import Chem
from rdkit.Chem import rdmolfiles

smiles = "CC1C2C3NC3(C#C)C12"

mol = Chem.MolFromSmiles(smiles)
if mol is None:
    raise ValueError("Invalid SMILES")

molH = Chem.AddHs(mol)
Chem.SanitizeMol(molH)

ranks = rdmolfiles.CanonicalRankAtoms(molH, breakTies=False)

hydrogen_environments = {
    ranks[atom.GetIdx()]
    for atom in molH.GetAtoms()
    if atom.GetAtomicNum() == 1
}

print(len(hydrogen_environments))

7

In [4]:
import re

STOPWORDS = {
    "a", "an", "the", "is", "are", "was", "were", "be", "been",
    "being", "of", "for", "to", "in", "on", "at", "by", "with",
    "and", "or", "as", "it", "its", "this", "that", "these",
    "those", "which", "who", "both", "from", "into", "their",
    "acts", "act", "plays", "play", "role",
}

# 可持续扩充的常见生物医学同义表达
SYNONYMS = {
    "metallopeptidase": "metalloprotease",
    "metallopeptidases": "metalloprotease",
    "metalloproteases": "metalloprotease",
}


def normalize(text: str) -> str:
    text = text.lower()

    # 统一常见格式
    text = re.sub(r"\batp[-\s]+dependent\b", "atp dependent", text)
    text = re.sub(r"\bzinc[-\s]+dependent\b", "zinc dependent", text)

    # 统一已知同义词
    for source, target in SYNONYMS.items():
        text = re.sub(
            rf"\b{re.escape(source)}\b",
            target,
            text,
        )

    return text


def content_tokens(text: str) -> set[str]:
    tokens = re.findall(r"\b[a-z0-9]+\b", normalize(text))

    result = set()
    for token in tokens:
        if token in STOPWORDS or len(token) <= 1:
            continue

        # 简单处理名词复数
        if token.endswith("ies") and len(token) > 4:
            token = token[:-3] + "y"
        elif token.endswith("s") and len(token) > 4 and not token.endswith("ss"):
            token = token[:-1]

        result.add(token)

    return result


def protein_reward(prediction: str, reference: str,
                   threshold: float = 0.85) -> dict:
    """Binary reward with reference-content coverage diagnostics."""

    if not isinstance(reference, str) or not reference.strip():
        return {"reward": 0, "coverage": 0.0, "status": "invalid_gt"}

    if not isinstance(prediction, str) or not prediction.strip():
        return {"reward": 0, "coverage": 0.0, "status": "empty_prediction"}

    pred_norm = normalize(prediction)
    ref_norm = normalize(reference)

    # GT 原文完整出现，直接满分
    if ref_norm in pred_norm:
        return {"reward": 1, "coverage": 1.0, "status": "exact_match"}

    gt_tokens = content_tokens(reference)
    pred_tokens = content_tokens(prediction)

    if not gt_tokens:
        return {"reward": 0, "coverage": 0.0, "status": "empty_gt_tokens"}

    matched = gt_tokens & pred_tokens
    coverage = len(matched) / len(gt_tokens)

    return {
        "reward": int(coverage >= threshold),
        "coverage": round(coverage, 4),
        "status": "pass" if coverage >= threshold else "fail",
        "missing_tokens": sorted(gt_tokens - pred_tokens),
    }

prediction="## Protein feature summary  ### Overall identification The 652-aa sequence is **strongly supported as an FtsH-family ATP-dependent zinc metalloprotease**. Its closest reported reviewed homolog is *Cupriavidus metallidurans* FtsH (UniProt **Q1LLA9**): **62.3% sequence identity**, 92.8% query coverage, and E-value 3.43 × 10⁻²⁶⁸. A *Salmonella* FtsH homolog also shows about 61% identity across most of the sequence. This degree of full-length similarity supports the family assignment, though it is not direct experimental characterization of this exact sequence.  ### Sequence-derived properties | Feature | Estimate | |---|---:| | Length | 652 amino acids | | Molecular mass | 71,515 Da | | Theoretical pI | 5.81 | | GRAVY | −0.176 | | Instability index | 32.49 |  These are sequence-based estimates; they do not account for processing, modifications, ligands, or assembly state.  ### Predicted architecture and likely function - **N-terminal membrane anchor:** The sequence contains two strong hydrophobic segments, approximately around residues **17–39** and **116–139**. This fits the two-pass inner-membrane topology annotated for the close FtsH homologs. The intervening region is expected to face the periplasm; most of the protein after the second membrane span is expected to be cytosolic. These boundaries are approximate, not a topology prediction validated for this query. - **Large cytosolic catalytic region:** The sequence contains an ATPase P-loop-like motif (...GPNGCGKT...) and a downstream metalloprotease-like region. Together with the close FtsH homology, this supports the typical FtsH architecture: an ATPase motor coupled to a zinc-dependent protease. - **Likely role:** Processive degradation of cytoplasmic and membrane proteins, including membrane-protein quality control. ...  ### Limitations The evidence supports a high-confidence **FtsH-family** assignment, but specific substrates, physiological roles, and regulation cannot be assigned from this sequence comparison alone. Pfam scanning was unavailable because the required database was not configured, and the evidence-graph retrieval did not return the recorded entries."
reference="A brief overview of the protein with the provided amino acid sequence is as follows: Acts as a processive, ATP-dependent zinc metallopeptidase for both cytoplasmic and membrane proteins. Plays a role in the quality control of integral membrane proteins."

protein_reward(prediction, reference)

{'reward': 0,
 'coverage': 0.7222,
 'status': 'fail',
 'missing_tokens': ['brief', 'follow', 'integral', 'overview', 'provided']}

In [ ]:
from biodsa.agents import DeepEvidenceAgent
agent = DeepEvidenceAgent(
    model_name="gpt-6-luna",
    api_type="openai",
    api_key="sk-rADrz1UBhHb5NCUdrlSj39g5r3rplLbZh4GIog3rkvK8WHXK",
    base_url="https://api.poixe.com/v1/",
    model_kwargs={
        "max_completion_tokens": 5000,
        "thinking": {"type": "disabled"},
        "reasoning_effort": "none"
    },
    subagent_action_rounds_budget=5, # the number of action rounds for the sub research agents to run
    main_search_rounds_budget=5, # the number of search rounds for the main orchestrator agent to run
    main_action_rounds_budget=10, # the number of action rounds for the main orchestrator agent to run
    light_mode=False, # a light mode agent that does not use the memory graph
    llm_timeout=120,
)

question = """                                                                             
Is metabolic syndrome associated with increased risk of Barrett esophagus : A meta-analysis?
"""

agent_query = (
        f"{question}\n\n"
        f"Please research this question using your tools. "
    )

# run the agent
execution_results = agent.go(
    agent_query,
    knowledge_bases=["pubchem",],
    export_dataset_dir="/home/data4/xiangyu/BioDSA/tutorials/workdir_test", # 自动落盘路径
    sample_id="c=chem_sample_001",                 # 样本文件夹名称
)

2026-10-22 00:20:38,235 - WARNING - Failed to initialize sandbox: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
2026-10-22 00:20:38,236 - WARNING - Tools will fall back to local execution when possible
2026-10-22 00:20:38,238 - WARNING - model_name 'gpt-6-luna' not in llm_config.ALL_SUPPORTED_MODELS; add it to biodsa/agents/llm_config.py if this is a supported model.

initializing openai with base_url: https://api.poixe.com/v1/
====================================================================================================
👤 Human
====================================================================================================

You are an expert in the field of chemistry. I have a chemical reaction SMILES, as shown below. Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.___>CCCCP(C12CC3CC(CC(C3)C1)C2)C12CC3CC(CC(C3)C1)C2.[O
H-].[K+].C1CCOC1>Unknown product.

Please fill in the blank ("___") using the optimal reactant from the CHOICE LIST to maximize the yield of the reaction.
---
CHOICE LIST: (Choose from below!)
> Brc1ccc2ncccc2c1
> O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F
> Ic1ccc2ncccc2c1
Answer: (Choose from the CHOICE LIST!)
You must output your prediction, i.e. valid SMILES, and follow the output format exactly as follows:
{"answer": [" valid SMILES"]}.

Please use your tools to analyze and solve this problem accurately.


Please research this question using your tools.

initializing openai with base_url: https://api.poixe.com/v1/

2026-10-22 00:20:57,471 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current search round (Search Agent calls): 1/5
Current action round (orchestrator calls): 1/10
====================================================================================================
🤖 AI Assistant
====================================================================================================
计划：
1. [ ] 将反应识别为硼酸与卤代杂芳烃的交叉偶联，并检索候选卤素底物的反应证据。
2. [ ] 比较溴代、碘代及磺酸酯候选物与该反应体系的匹配性。
3. [ ] 将检索结果记录并复核证据，确定最可能提升产率的实际反应物。
4. [ ] 按指定 JSON 格式输出唯一有效 SMILES。

📞 Tool Calls (1):
  [1] go_search_agent
      knowledge_bases: ['chemistry']
      search_rounds_budget: 5
      search_target: Determine which choice is the optimal electro ... ide versus iodide versus heteroaryl triflate.

called: search_workflow
initializing openai with base_url: https://api.poixe.com/v1/
====================================================================================================
👤 Human
====================================================================================================
Determine which choice is the optimal electrophilic coupling partner for the reaction: aryl boronic acid Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O with KOH, THF, and a bulky phosphine/palladium-type catalyst represented by CCCC P(... )..., comparing Brc1ccc2ncccc2c1, Ic1ccc2ncccc2c1, and O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F. Identify the likely Suzuki-Miyaura reactant and any evidence favoring bromide versus iodide versus heteroaryl triflate.

2026-10-22 00:21:19,032 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current round of the Search Agent: 1/5
====================================================================================================
🤖 AI Assistant
====================================================================================================

📞 Tool Calls (1):
  [1] fetch_reaction_details
      limit: 5
      reaction_smiles: Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.Brc1ccc2ncccc2c1>>
      task_name: Find Suzuki-Miyaura coupling evidence and con ... the aryl boronic acid with quinolinyl bromide

initializing openai with base_url: https://api.poixe.com/v1/
====================================================================================================
🔧 Tool Response (fetch_reaction_details)
====================================================================================================
### Executed Code:
```python

from biodsa.tools.chemical.chemicals import fetch_reaction_conditions_unified
results, output = fetch_reaction_conditions_unified(reaction_smiles='Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.Brc1ccc2ncccc2c1>>', limit=5, save_path='/home/data4/xiangyu/BioDSA/workdir/Find_Suzuki-Miyaura_coupling_evidence_and_conditions_for_the_aryl_boronic_acid_with_quinolinyl_bromi.json')
print(output)

```

### Output:
# Reaction Conditions Search Results

## Query: `Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.Brc1ccc2ncccc2c1>>`

*[Forward Prediction Match] Found records using core reactant (Index Match):* `Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`

### Found 5 matching records

**Record 1**
- **Reaction ID:** ord-cb757624c570427b958145f6422ac50e
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 78.1%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** CO (SOLVENT), C1CCC(CC1)P(C2CCCCC2)C3CCCCC3 (CATALYST), [Cs+].[Cs+].[O-]C(=O)[O-] (REAGENT), palladium acetate (CATALYST)

**Record 2**
- **Reaction ID:** ord-0b885348c50c4c6fb46d42287c402bf0
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 77.4%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** [K+].CC(=O)[O-] (REAGENT), CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), palladium acetate (CATALYST)

**Record 3**
- **Reaction ID:** ord-2334ac9b0f79474980d4674c776b6a21
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 76.5%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), [Cs+].[Cs+].[O-]C(=O)[O-] (REAGENT), palladium acetate (CATALYST)

**Record 4**
- **Reaction ID:** ord-915547390fa846db9a944e76ada7ebf1
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 76.3%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), [OH-].[K+] (REAGENT), palladium acetate (CATALYST)

**Record 5**
- **Reaction ID:** ord-484930799d61473382ddfd91534191b4
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 76.2%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** O (REAGENT), CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), palladium acetate (CATALYST)



## Tool Call Provenance
tool_name: fetch_reaction_details
tool_call_id: call_O0vYJKcPWdDAzsZALaW2V40T

2026-10-22 00:21:31,656 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current round of the Search Agent: 2/5
====================================================================================================
🤖 AI Assistant
====================================================================================================

📞 Tool Calls (1):
  [1] fetch_reaction_details
      limit: 5
      reaction_smiles: Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.Ic1ccc2ncccc2c1>>
      task_name: Compare Suzuki-Miyaura evidence for the quinolinyl iodide coupling partner

initializing openai with base_url: https://api.poixe.com/v1/
====================================================================================================
🔧 Tool Response (fetch_reaction_details)
====================================================================================================
### Executed Code:
```python

from biodsa.tools.chemical.chemicals import fetch_reaction_conditions_unified
results, output = fetch_reaction_conditions_unified(reaction_smiles='Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.Ic1ccc2ncccc2c1>>', limit=5, save_path='/home/data4/xiangyu/BioDSA/workdir/Compare_Suzuki-Miyaura_evidence_for_the_quinolinyl_iodide_coupling_partner.json')
print(output)

```

### Output:
# Reaction Conditions Search Results

## Query: `Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.Ic1ccc2ncccc2c1>>`

*[Forward Prediction Match] Found records using core reactant (Index Match):* `Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`

### Found 5 matching records

**Record 1**
- **Reaction ID:** ord-cb757624c570427b958145f6422ac50e
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 78.1%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** CO (SOLVENT), C1CCC(CC1)P(C2CCCCC2)C3CCCCC3 (CATALYST), [Cs+].[Cs+].[O-]C(=O)[O-] (REAGENT), palladium acetate (CATALYST)

**Record 2**
- **Reaction ID:** ord-0b885348c50c4c6fb46d42287c402bf0
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 77.4%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** [K+].CC(=O)[O-] (REAGENT), CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), palladium acetate (CATALYST)

**Record 3**
- **Reaction ID:** ord-2334ac9b0f79474980d4674c776b6a21
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 76.5%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), [Cs+].[Cs+].[O-]C(=O)[O-] (REAGENT), palladium acetate (CATALYST)

**Record 4**
- **Reaction ID:** ord-915547390fa846db9a944e76ada7ebf1
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 76.3%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), [OH-].[K+] (REAGENT), palladium acetate (CATALYST)

**Record 5**
- **Reaction ID:** ord-484930799d61473382ddfd91534191b4
- **Full Reaction SMILES:** `Not provided`
- **Reactants SMILES:** `Brc1ccc2ncccc2c1.Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O`
- **Target Product SMILES:** `CC(C=CC1=C2C=NN1C3CCCCO3)=C2C4=CC(C=CC=N5)=C5C=C4`
- **Target Product SELFIES:** `[C][C][Branch2][Ring1][C][C][=C][C][=C][C][=N][N][Ring1][Branch1][C][C][C][C][C][O][Ring1][=Branch1][=C][Ring1][O][C][=C][C][Branch1][Branch1][C][=C][C][=N][=C][Ring1][C][C][=C][Ring1][#Branch2]`
- **Yield:** 76.2%
- **Temperature:** 100.0 °C
- **Time:** 5.00 hours
- **Solvents:** CO
- **Reagents/Catalysts:** O (REAGENT), CO (SOLVENT), c1ccc(cc1)P(c2ccccc2)c3ccccc3 (CATALYST), palladium acetate (CATALYST)



## Tool Call Provenance
tool_name: fetch_reaction_details
tool_call_id: call_0eiObKcsNB91xQJ0wyspgbr5

2026-10-22 00:21:43,015 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current round of the Search Agent: 3/5
====================================================================================================
🤖 AI Assistant
====================================================================================================

📞 Tool Calls (1):
  [1] fetch_reaction_details
      limit: 5
      reaction_smiles: Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F>>
      task_name: Compare evidence for coupling with the heteroaryl triflate electrophile

initializing openai with base_url:====================================================================================================
🔧 Tool Response (fetch_reaction_details)
====================================================================================================
### Executed Code:
```python

from biodsa.tools.chemical.chemicals import fetch_reaction_conditions_unified
results, output = fetch_reaction_conditions_unified(reaction_smiles='Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F>>', limit=5, save_path='/home/data4/xiangyu/BioDSA/workdir/Compare_evidence_for_coupling_with_the_heteroaryl_triflate_electrophile.json')
print(output)

```

### Output:
# Reaction Conditions Search Results

## Query: `Cc1ccc2c(cnn2C2CCCCO2)c1B(O)O.O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F>>`

*[Fuzzy Fallback] Found related records via fuzzy string scan (Slow Match):* `O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F`

### Found 1 matching records

**Record 1**
- **Reaction ID:** ord-870ec54fec4747279735cb4eb54f5b30
- **Full Reaction SMILES:** `FC(F)(F)S(O[C:7]1[CH:8]=[N:9][C:10]2[C:15]([CH:16]=1)=[N:14][CH:13]=[CH:12][CH:11]=2)(=O)=O.FC(F)(F)S(OC1C=[N:27][C:28]2C(C=1)=CC=CC=2)(=O)=O.Cl.[NH2:38]O>>[NH:38]1[C:16]2[C:15]3[N:14]=[CH:13][CH:12]=[CH:11][C:10]=3[N:9]=[CH:8][C:7]=2[N:27]=[CH:28]1 |f:2.3|`
- **Reactants SMILES:** `Cl.NO.O=S(=O)(Oc1cnc2ccccc2c1)C(F)(F)F.O=S(=O)(Oc1cnc2cccnc2c1)C(F)(F)F`
- **Target Product SMILES:** `N1C=NC=2C=NC=3C=CC=NC3C21`
- **Target Product SELFIES:** `[N][C][=N][C][C][=N][C][C][=C][C][=N][C][=Ring1][=Branch1][C][=Ring1][#Branch2][Ring1][=N]`



## Tool Call Provenance
tool_name: fetch_reaction_details
tool_call_id: call_j2TUoKJKPlwJx41wGEJnoz6B

 https://api.poixe.com/v1/

2026-10-22 00:22:14,299 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current round of the Search Agent: 4/5
initializing openai with base_url: https://api.poixe.com/v1/
====================================================================================================
🤖 AI Assistant
====================================================================================================

📞 Tool Calls (1):
  [1] report_key_findings
      key_findings: [{'finding': 'The optimal and database-suppor ... call_id': 'call_j2TUoKJKPlwJx41wGEJnoz6B'}]}]

====================================================================================================
🔧 Tool Response (report_key_findings)
====================================================================================================
Key findings recorded successfully.

## Tool Call Provenance
tool_name: report_key_findings
tool_call_id: call_lsNfJFYLDG1XGwxmD4HKg1Tb

2026-10-22 00:22:32,060 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current round of the Search Agent: 5/5
====================================================================================================
🤖 AI Assistant
====================================================================================================
The optimal electrophilic coupling partner is **Brc1ccc2ncccc2c1**, the quinolinyl **aryl bromide**.

- **Direct Suzuki–Miyaura precedent:** The exact aryl boronic acid paired with this bromide gives the corresponding biaryl product in multiple ORD records, using palladium/phosphine catalysts and base. One record specifically uses **KOH**, with approximately **76–78% yield**, 100 °C, and 5 h.
  *(Evidence: `call_O0vYJKcPWdDAzsZALaW2V40T`)*

- **Iodide comparison:** Although aryl iodides are often intrinsically more reactive than bromides in oxidative addition, the iodide query returned records whose actual reactant was still the **bromide**, not `Ic1ccc2ncccc2c1`. Thus there is no direct database evidence favoring the iodide in this reaction.
  *(Evidence: `call_0eiObKcsNB91xQJ0wyspgbr5`)*

- **Heteroaryl triflate comparison:** The triflate candidate only produced a fuzzy-match record for an unrelated transformation and was not shown coupling with the boronic acid. It is therefore less likely to be the intended Suzuki partner.
  *(Evidence: `call_j2TUoKJKPlwJx41wGEJnoz6B`)*

**Conclusion:** Select **Brc1ccc2ncccc2c1**. The evidence favors it because it is the exact, repeatedly documented Suzuki substrate under Pd/phosphine–base conditions, rather than because bromide is universally more reactive than iodide.

====================================================================================================
🔧 Tool Response (go_search_agent)
====================================================================================================
The optimal electrophilic coupling partner is **Brc1ccc2ncccc2c1**, the quinolinyl **aryl bromide**.

- **Direct Suzuki–Miyaura precedent:** The exact aryl boronic acid paired with this bromide gives the corresponding biaryl product in multiple ORD records, using palladium/phosphine catalysts and base. One record specifically uses **KOH**, with approximately **76–78% yield**, 100 °C, and 5 h.
  *(Evidence: `call_O0vYJKcPWdDAzsZALaW2V40T`)*

- **Iodide comparison:** Although aryl iodides are often intrinsically more reactive than bromides in oxidative addition, the iodide query returned records whose actual reactant was still the **bromide**, not `Ic1ccc2ncccc2c1`. Thus there is no direct database evidence favoring the iodide in this reaction.
  *(Evidence: `call_0eiObKcsNB91xQJ0wyspgbr5`)*

- **Heteroaryl triflate comparison:** The triflate candidate only produced a fuzzy-match record for an unrelated transformation and was not shown coupling with the boronic acid. It is therefore less likely to be the intended Suzuki partner.
  *(Evidence: `call_j2TUoKJKPlwJx41wGEJnoz6B`)*

**Conclusion:** Select **Brc1ccc2ncccc2c1**. The evidence favors it because it is the exact, repeatedly documented Suzuki substrate under Pd/phosphine–base conditions, rather than because bromide is universally more reactive than iodide.

initializing openai with base_url: https://api.poixe.com/v1/

2026-10-22 00:22:57,902 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current search round (Search Agent calls): 1/5
Current action round (orchestrator calls): 2/10
====================================================================================================
🤖 AI Assistant
====================================================================================================
判断：检索结果已明确支持硼酸与喹啉基溴化物进行 Suzuki–Miyaura 偶联，并给出 KOH/Pd-膦体系下的直接产率证据。现在先按证据图协议记录这些结论，再复核图谱信息。计划更新：

1. [✓] 将反应识别为硼酸与卤代杂芳烃的交叉偶联，并检索候选卤素底物的反应证据。
2. [✓] 比较溴代、碘代及磺酸酯候选物与该反应体系的匹配性。
3. [ ] 将检索结果记录并复核证据，确定最可能提升产率的实际反应物。
4. [ ] 按指定 JSON 格式输出唯一有效 SMILES。

📞 Tool Calls (1):
  [1] add_to_graph
      entities: [{'entity_type': 'CHEMICAL / DRUG', 'name': ' ... call_id': 'call_j2TUoKJKPlwJx41wGEJnoz6B'}]}]
      observations: None
      relations: [{'from_entity': 'Brc1ccc2ncccc2c1', 'relatio ...  'to_entity': 'Optimal Suzuki electrophile'}]

====================================================================================================
🔧 Tool Response (add_to_graph)
====================================================================================================
{"success": true, "results": {"entities_created": {"count": 4, "entities": [{"name": "Brc1ccc2ncccc2c1", "entityType": "CHEMICAL / DRUG", "observations": ["Exact quinolinyl aryl bromide supported as the Suzuki\u2013Miyaura electrophile with the supplied aryl boronic acid.", "ORD records report Pd(OAc)2/phosphine and base conditions including KOH, 100 \u00b0C, 5 h, with 76.2\u201378.1% yields."]}, {"name": "Ic1ccc2ncccc2c1", "entityType": "CHEMICAL / DRUG", "observations": ["No direct supporting reaction record was retrieved for this iodide with the supplied boronic acid; queried records resolved to bromide-containing reactions."]}, {"name": "Heteroaryl triflate candidate", "entityType": "CHEMICAL / DRUG", "observations": ["The triflate candidate was not supported as the Suzuki partner; the retrieved fuzzy match represented a different transformation without the supplied boronic acid."]}, {"name": "Optimal Suzuki electrophile", "entityType": "FINDING", "observations": ["For the stated reaction set, the most likely yield-maximizing and database-supported choice is Brc1ccc2ncccc2c1.", "This conclusion reflects exact reaction precedent, not a general claim that bromide is intrinsically more reactive than iodide."]}]}, "relations_created": {"count": 1, "relations": [{"from": "Brc1ccc2ncccc2c1", "to": "Optimal Suzuki electrophile", "relationType": "SUPPORTS"}]}}, "provenance": {"tool_call_id": "call_XWIvdShsEYTX6ytqoIhAYbn4", "tool_name": "add_to_graph", "agent": "orchestrator", "round": 2, "parent_tool_call_id": "call_LwXsMXYVdcZNN4SiLFsSARps"}}

initializing openai with base_url: https://api.poixe.com/v1/

2026-10-22 00:23:10,619 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current search round (Search Agent calls): 1/5
Current action round (orchestrator calls): 3/10
====================================================================================================
🤖 AI Assistant
====================================================================================================
基于已检索的直接反应先例，候选溴代喹啉是唯一有明确匹配的 Suzuki 偶联底物。按证据图协议，我现在复核已记录实体与关系；复核后直接按用户要求输出 JSON。计划更新：

1. [✓] 将反应识别为硼酸与卤代杂芳烃的交叉偶联，并检索候选卤素底物的反应证据。
2. [✓] 比较溴代、碘代及磺酸酯候选物与该反应体系的匹配性。
3. [ ] 将检索结果记录并复核证据，确定最可能提升产率的实际反应物。
4. [ ] 按指定 JSON 格式输出唯一有效 SMILES。

📞 Tool Calls (1):
  [1] retrieve_from_graph
      entity_names: ["Brc1ccc2ncccc2c1","Ic1ccc2ncccc2c1","Heteroaryl triflate candidate","Optimal Suzuki electrophile"]
      get_full_map: False
      max_entities: None
      max_observations_per_entity: 5
      query: None
      top_k: 10

====================================================================================================
🔧 Tool Response (retrieve_from_graph)
====================================================================================================
{"success": true, "requested_entities": ["Brc1ccc2ncccc2c1", "Ic1ccc2ncccc2c1", "Heteroaryl triflate candidate", "Optimal Suzuki electrophile"], "results": {"entities": [{"name": "Brc1ccc2ncccc2c1", "entityType": "CHEMICAL / DRUG", "observations": ["Exact quinolinyl aryl bromide supported as the Suzuki\u2013Miyaura electrophile with the supplied aryl boronic acid.", "ORD records report Pd(OAc)2/phosphine and base conditions including KOH, 100 \u00b0C, 5 h, with 76.2\u201378.1% yields."]}, {"name": "Ic1ccc2ncccc2c1", "entityType": "CHEMICAL / DRUG", "observations": ["No direct supporting reaction record was retrieved for this iodide with the supplied boronic acid; queried records resolved to bromide-containing reactions."]}, {"name": "Heteroaryl triflate candidate", "entityType": "CHEMICAL / DRUG", "observations": ["The triflate candidate was not supported as the Suzuki partner; the retrieved fuzzy match represented a different transformation without the supplied boronic acid."]}, {"name": "Optimal Suzuki electrophile", "entityType": "FINDING", "observations": ["For the stated reaction set, the most likely yield-maximizing and database-supported choice is Brc1ccc2ncccc2c1.", "This conclusion reflects exact reaction precedent, not a general claim that bromide is intrinsically more reactive than iodide."]}], "relations": [{"from": "Brc1ccc2ncccc2c1", "to": "Optimal Suzuki electrophile", "relationType": "SUPPORTS"}]}}

initializing openai with base_url: https://api.poixe.com/v1/

2026-10-22 00:23:15,316 - INFO - HTTP Request: POST https://api.poixe.com/v1/chat/completions "HTTP/1.1 200 OK"

Current search round (Search Agent calls): 1/5
Current action round (orchestrator calls): 4/10
====================================================================================================
🤖 AI Assistant
====================================================================================================
{"answer":["Brc1ccc2ncccc2c1"]}

FileExistsError: Sample directory already exists: /home/data4/xiangyu/BioDSA/tutorials/workdir_test/c=chem_sample_001

In [2]:
import sqlite3

db_path = (
    "/home/data4/xiangyu/dataset/chemistry_knowledgebase/"
    "ORD/ord-data/ord_conditions.db"
)

conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
cur = conn.cursor()

# 1. 查看所有表
cur.execute("""
    SELECT name, sql
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
""")

for name, schema in cur.fetchall():
    print(f"\n{'=' * 80}\nTABLE: {name}\n{schema}")

# 2. 查看 reaction_conditions 的字段
cur.execute("PRAGMA table_info(reaction_conditions)")
columns = cur.fetchall()

print("\n字段列表：")
for col in columns:
    print(col)

# 3. 查看记录总量
cur.execute("SELECT COUNT(*) FROM reaction_conditions")
print("\n记录总数：", cur.fetchone()[0])

conn.close()

================================================================================
TABLE: reaction_conditions
CREATE TABLE reaction_conditions (
            reaction_id TEXT PRIMARY KEY,
            reaction_smiles TEXT,
            temperature_celsius REAL,
            time_hours REAL,
            solvents TEXT
        )

字段列表：
(0, 'reaction_id', 'TEXT', 0, None, 1)
(1, 'reaction_smiles', 'TEXT', 0, None, 0)
(2, 'temperature_celsius', 'REAL', 0, None, 0)
(3, 'time_hours', 'REAL', 0, None, 0)
(4, 'solvents', 'TEXT', 0, None, 0)

记录总数： 2338291

In [ ]:
execution_results.tool_trace

[ToolTraceItem(step=0, agent='orchestrator', tool_name='go_search_agent', tool_call_id='call_s1n26wB6lVObn4v4LCGpzVs1', parent_tool_call_id=None, round=1, tool_input={'knowledge_bases': ['pubmed_papers', 'gene', 'disease'], 'search_rounds_budget': 5, 'search_target': 'Determine whether methylation of the human FGFR2 gene is associated with high birth weight centile or large-for-gestational-age birth. Find human studies that directly measure FGFR2 DNA methylation and report birth weight, birth-weight centile, or large-for-gestational-age outcomes; extract direction, tissue, sample size, statistical significance, and whether evidence is replicated. Distinguish FGFR2 from other genes or nearby loci.'}, status='success', raw_output=None, result_entity_names=[], used_in_final_answer=False),
 ToolTraceItem(step=1, agent='search', tool_name='unified_gene_search', tool_call_id='call_0khP215tdBARd3iO1HKIJcwg', parent_tool_call_id='call_s1n26wB6lVObn4v4LCGpzVs1', round=1, tool_input={'context_tool_call_ids': [], 'include_variants': False, 'limit_per_source': 5, 'search_term': 'FGFR2', 'sources': ['biothings', 'kegg', 'opentargets'], 'task_name': 'FGFR2 search'}, status='success', raw_output="### Executed Code:\n```python\n\nfrom biodsa.tools.genes import search_genes_unified\n\n# Perform unified gene search across multiple sources\nresults, output = search_genes_unified(\n    search_term='FGFR2',\n    limit_per_source=5,\n    sources=['biothings', 'kegg', 'opentargets'],\n    include_variants=False,\n    save_path='/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_search.json',\n)\n\n# Display formatted output\nprint(output)\n\n```\n\n### Output:\n# Unified Gene Search Results\n\n## Search Term: 'FGFR2'\n\n**Total results:** 12 across 3 sources\n\n### Results by Source:\n- **BioThings (MyGene.info):** Found 5 genes (showing 5 of 8 total) in 4ms\n- **KEGG Gene:** Found 5 genes\n- **Open Targets:** Found 2 targets\n\n================================================================================\n\n\n## BIOTHINGS Results\n\nFound 5 genes from BioThings (MyGene.info):\n\n**1. FGFR2** - fibroblast growth factor receptor 2\n  - Gene ID: 2263\n  - Entrez: 2263\n  - Type: protein-coding\n  - Summary: The protein encoded by this gene is a member of the fibroblast growth factor receptor family, where amino acid sequence is highly conserved between members and throughout evolution. FGFR family member...\n  - Aliases: BBDS, BEK, BFR-1, CD332, CEK3, CFD1, ECT1, JWS, K-SAM, KGFR, TK14, TK25...\n\n**2. FGFBP3** - fibroblast growth factor binding protein 3\n  - Gene ID: 143282\n  - Entrez: 143282\n  - Type: protein-coding\n  - Summary: Enables fibroblast growth factor binding activity and heparin binding activity. Acts upstream of or within positive regulation of fibroblast growth factor receptor signaling pathway and positive regul...\n  - Aliases: C10orf13, FGF-BP3...\n\n**3. FGFBP2** - fibroblast growth factor binding protein 2\n  - Gene ID: 83888\n  - Entrez: 83888\n  - Type: protein-coding\n  - Summary: This gene encodes a member of the fibroblast growth factor binding protein family. The encoded protein is a serum protein that is selectively secreted by cytotoxic lymphocytes and may be involved in c...\n  - Aliases: HBP17RP, KSP37...\n\n**4. ESRP2** - epithelial splicing regulatory protein 2\n  - Gene ID: 80004\n  - Entrez: 80004\n  - Type: protein-coding\n  - Summary: ESPR2 is an epithelial cell-type-specific splicing regulator (Warzecha et al., 2009 [PubMed 19285943]).[supplied by OMIM, Aug 2009]....\n  - Aliases: RBM35B...\n\n**5. ESRP1** - epithelial splicing regulatory protein 1\n  - Gene ID: 54845\n  - Entrez: 54845\n  - Type: protein-coding\n  - Summary: ESPR1 is an epithelial cell-type-specific splicing regulator (Warzecha et al., 2009 [PubMed 19285943]).[supplied by OMIM, Aug 2009]....\n  - Aliases: DFNB109, RBM35A, RMB35A...\n\n\n## KEGG Results\n\nFound 5 genes from KEGG:\n\n**1. hsa:2263** - FGFR2, BBDS, BEK, BFR-1, CD332, CEK3, CFD1, ECT1, JWS, K-SAM, KGFR, TK14, TK25; fibroblast growth factor receptor 2 isoform 1 precursor\n\n**2. ptr:466220** - FGFR2; fibroblast growth factor receptor 2 isoform X12\n\n**3. pps:100981139** - FGFR2; fibroblast growth factor receptor 2 isoform X1\n\n**4. ggo:101153046** - FGFR2; fibroblast growth factor receptor 2 isoform X5\n\n**5. pon:100171540** - FGFR2; fibroblast growth factor receptor 2\n\n\n## OPENTARGETS Results\n\nFound 2 therapeutic targets from Open Targets:\n\n**1. FGFR2**\n  - Target ID: ENSG00000066468\n  - Description: fibroblast growth factor receptor 2...\n  - Entity Type: target\n\n**2. BICC1**\n  - Target ID: ENSG00000122870\n  - Description: BicC family RNA binding protein 1...\n  - Entity Type: target\n\n\n================================================================================\n\n## Aggregated Information\n\n**All Gene Symbols Found (11):**\n  - 100171540\n  - 100981139\n  - 101153046\n  - 2263\n  - 466220\n  - BICC1\n  - ESRP1\n  - ESRP2\n  - FGFBP2\n  - FGFBP3\n  - FGFR2\n\n**Cross-Database Identifiers:**\n  - ENTREZ: 143282, 2263, 54845, 80004, 83888\n  - ENSEMBL: ENSG00000066468, ENSG00000122870\n  - KEGG: ggo:101153046, hsa:2263, pon:100171540, pps:100981139, ptr:466220\n  - GENE_ID: 143282, 2263, 54845, 80004, 83888\n  - SYMBOL: BICC1, ESRP1, ESRP2, FGFBP2, FGFBP3\n\n\n**Results saved to:** /home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_search.json\n\n\n*Executed locally (no sandbox)*", result_entity_names=[], used_in_final_answer=False),
 ToolTraceItem(step=2, agent='search', tool_name='search_papers', tool_call_id='call_mwlLvdvFB58OdrCWER0sSBxS', parent_tool_call_id='call_s1n26wB6lVObn4v4LCGpzVs1', round=1, tool_input={'boolean_query_text': 'FGFR2 methylation birth weight', 'relation_query': None, 'task_name': 'FGFR2 birth weight', 'top_k': 50}, status='success', raw_output='### Executed Code:\n```python\n\nfrom biodsa.tools.pubmed.pubtator_api import pubtator_api_search_papers\nfrom biodsa.tools.pubmed.pubmed_api import pubmed_api_search_papers\nimport pandas as pd\n\ndf_list = []\nhas_relation_query = False\n\n# 1. PubMed Search (Best Relevance Sorting)\nif not has_relation_query:\n    pmid_df = pubmed_api_search_papers(\n        boolean_query_text=\'FGFR2 methylation birth weight\',\n        top_k=50,\n    )\n    if pmid_df is not None and not pmid_df.empty:\n        for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:\n            if col not in pmid_df.columns:\n                pmid_df[col] = ""\n        pmid_df = pmid_df[["PMID", "Title", "Journal", "Year", "Abstract"]]\n        df_list.append(pmid_df)\n\n# 2. PubTator3 Search (Entity highlighting, fallback)\npubtator_results = []\nfor page in range(1, 5 + 1):\n    search_results = pubtator_api_search_papers(\n        boolean_query_text=\'FGFR2 methylation birth weight\',\n        relation_query=None,\n        page=page,\n        max_retries=3,\n        max_requests_per_second=3.0\n    )\n    if search_results is not None and not search_results.empty:\n        pubtator_results.append(search_results)\n    else:\n        break\n\nif pubtator_results:\n    pubtator_df = pd.concat(pubtator_results)\n    if "Highlighted_Text" in pubtator_df.columns:\n        pubtator_df = pubtator_df.rename(columns={"Highlighted_Text": "Abstract"})\n    \n    for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:\n        if col not in pubtator_df.columns:\n            pubtator_df[col] = ""\n    pubtator_df = pubtator_df[["PMID", "Title", "Journal", "Year", "Abstract"]]\n    df_list.append(pubtator_df)\n\n# 3. Combine, Deduplicate and Format Clean Output\nif df_list:\n    final_df = pd.concat(df_list).reset_index(drop=True)\n    # Deduplicate by PMID, keeping the first occurrence (which guarantees PubMed relevance is maintained)\n    final_df = final_df.drop_duplicates(subset=["PMID"], keep="first")\n    \n    # Optional: Save to CSV for persistent logging\n    final_df.to_csv(\'/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_birth_weight.csv\', index=False)\n    print(f"The search results are saved at \'/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_birth_weight.csv\'")\n    print(f"Total results found: {len(final_df)}\\n")\n    print("=" * 80)\n    print("TOP RESULTS (Showing up to 15 most relevant):")\n    print("=" * 80)\n    \n    # FORMAT FOR LLM: Clean text layout rather than Markdown table\n    for idx, row in final_df.head(15).iterrows():\n        pmid = row.get(\'PMID\', \'N/A\')\n        title = row.get(\'Title\', \'No Title\')\n        journal = row.get(\'Journal\', \'Unknown\')\n        year = row.get(\'Year\', \'Unknown\')\n        abstract = str(row.get(\'Abstract\', \'No Abstract Available\'))\n        \n        # Clean abstract spaces and truncate at 1200 chars to save context window\n        abstract = " ".join(abstract.split())\n        if len(abstract) > 1200:\n            abstract = abstract[:1200] + " ... [Truncated]"\n            \n        print(f"PMID: {pmid}")\n        print(f"Title: {title}")\n        print(f"Source: {journal} ({year})")\n        print(f"Abstract: {abstract}")\n        print("-" * 80)\nelse:\n    print("No search results found. Please try again with different query. TIP: Try simpler keyword phrases.")\n\n```\n\n### Output:\n```\nThe search results are saved at \'/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_birth_weight.csv\'\nTotal results found: 52\n\n================================================================================\nTOP RESULTS (Showing up to 15 most relevant):\n================================================================================\nPMID: 25431941\nTitle: Methylation of the FGFR2 gene is associated with high birth weight centile in humans.\nSource: Epigenomics (2014)\nAbstract: AIMS: This study examined links between DNA methylation and birth weight centile (BWC), and explored the impact of genetic variation. MATERIALS & METHODS: Using HumanMethylation450 arrays, we examined candidate gene-associated CpGs in cord blood from newborns with low (<15th centile), medium (40-60th centile) and high (>85th centile) BWC (n = 12). Candidates were examined in an investigation cohort (n = 110) using pyrosequencing and genotyping for putative methylation-associated polymorphisms performed using standard PCR. RESULTS: Array analysis identified 314 candidate genes associated with BWC extremes, four of which showed ≥ 4 BWC-linked CpGs. Of these, PM20D1 and MI886 suggested genetically determined methylation levels. However, methylation at three CpGs in FGFR2 remained significantly associated with high BWC (p = 0.004-0.027). CONCLUSION: We identified a novel biologically plausible candidate (FGFR2) for with BWC that merits further study.\n--------------------------------------------------------------------------------\nPMID: 29588807\nTitle: Placental surface area mediates the association between FGFR2 methylation in placenta and full-term low birth weight in girls.\nSource: Clinical epigenetics (2018)\nAbstract: BACKGROUND: Fibroblast growth factor receptor 2 (FGFR2) gene encodes a protein of the fibroblast growth factor receptor family. FGFR2 gene expression is associated with the regulation of implantation process of placenta which plays a vital role in fetal growth. DNA methylation is widely known as a mechanism of fetal growth. However, it is unclear whether and how DNA methylation of FGFR2 gene in the placenta is associated with full-term low birth weight. This case-control study aims to explore the links between FGFR2 methylation in placenta and full-term low birth weight and to further examine the mediation effect of placental surface area on this association. RESULTS: We conducted analyses for each of the five valid CpG sites at FGFR2 in 165 mother-baby pairs (86 FT-LBW vs. 79 FT-NBW) and found that per one standard deviation increase in the DNA methylation of CpG 11 at FGFR2 was associated with 1.64-fold higher risk of full-term low birth weight (OR = 1.64, 95% CI = [1.07, 2.52]) and 0.18 standard deviation decrease in placental surface area (β = - 0.18; standard error = 0.08, p = 0.02). The mediation effect of placental surface area on the association between DNA methylation and  ... [Truncated]\n--------------------------------------------------------------------------------\nPMID: 38534435\nTitle: The "Bad Father": Paternal Role in Biology of Pregnancy and in Birth Outcome\nSource: Biology (Basel) (2024)\nAbstract: Moreover, compared to younger fathers of 25-29 years, paternal age over 45 years increases the risk of @DISEASE_Birth_Weight @DISEASE_MESH:D001724 @@@low <m>birth</m> <m>weight</m>@@@ (@DISEASE_Birth_Weight @DISEASE_MESH:D001724 @@@LBW@@@), PTB, and late @DISEASE_Stillbirth @DISEASE_MESH:D050497 @@@stillbirth@@@.\n--------------------------------------------------------------------------------\nPMID: 37058433\nTitle: High-Dimensional Mediation Analysis: A New Method Applied to Maternal Smoking, Placental DNA Methylation, and Birth Outcomes\nSource: Environ Health Perspect (2023)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 36611709\nTitle: Vascular Distribution and Expression Patterns of Angiogenic Factors in Caruncle during the Early Stage of Pregnancy in Goats (Capra hircus)\nSource: Animals (Basel) (2022)\nAbstract: The molecular <m>weight</m> of CpG 9-, CpG 10-, and CpG 11- containing fragments overlapped, thus, the average of the three CG-containing fragments represented DNA <m>methylation</m> of CpG 9.10.11, similar to CpG 16.17 and CpG 19.20.\n--------------------------------------------------------------------------------\nPMID: 36091392\nTitle: The shared mother-child epigenetic signature of neglect is related to maternal adverse events\nSource: Front Physiol (2022)\nAbstract: In consonance, the neglectful condition has been associated with having a @DISEASE_Premature_Birth @DISEASE_MESH:D047928 @@@preterm <m>birth</m>@@@ with lower <m>birth</m> <m>weight</m> and with developing @DISEASE_Obesity @DISEASE_MESH:D009765 @@@obesity@@@ over the life course.\n--------------------------------------------------------------------------------\nPMID: 37697338\nTitle: Analysis of DNA methylation at birth and in childhood reveals changes associated with season of birth and latitude\nSource: Clin Epigenetics (2023)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 39325622\nTitle: Placenta-derived SOD3 deletion impairs maternal behavior via alterations in FGF/FGFR-prolactin signaling axis\nSource: Cell Rep (2024)\nAbstract: These results indicate that placental @GENE_SOD3 @GENE_6649 @@@Sod3@@@ KO attenuates @GENE_FGFR2 @GENE_2263 @@@<m>FGFR2</m>@@@ and @GENE_FGF1 @GENE_2246 @@@FGF1@@@ expression through TET-@GENE_IDH1 @GENE_15926 @@@IDH@@@ inactivation-induced increases in DNA <m>methylation</m> levels at the promoter of @GENE_FGFR2 @GENE_2263 @@@<m>Fgfr2</m>@@@ and @GENE_FGF1 @GENE_2246 @@@Fgf1@@@ genes.\n--------------------------------------------------------------------------------\nPMID: 34930438\nTitle: The angiogenic properties of human amniotic membrane stem cells are enhanced in gestational diabetes and associate with fetal adiposity\nSource: Stem Cell Res Ther (2021)\nAbstract: Of note, @GENE_FGFR2 @GENE_2263 @@@<m>FGFR2</m>@@@ expression correlated significantly with neonatal sum of skinfolds and placental <m>weight</m>, which accords with a previous report showing a positive relationship between @GENE_FGF2 @GENE_2247 @@@FGF2@@@ and <m>birth</m>-<m>weight</m> and placental size in pregnancies complicated by @DISEASE_Diabetes_Mellitus @DISEASE_MESH:D003920 @@@diabetes@@@ [57].\n--------------------------------------------------------------------------------\nPMID: 39766778\nTitle: Placenta Thickness Mediates the Association Between AKIP1 Methylation in Maternal Peripheral Blood and Full-Term Small for Gestational Age Neonates\nSource: Genes (Basel) (2024)\nAbstract: The mediation effect of placental <m>weight</m> on the association of DNA <m>methylation</m> of CpG4 in @GENE_AKIP1 @GENE_56672 @@@AKIP1@@@ and @CHEMICAL_Tegafur @CHEMICAL_MESH:D005641 @@@FT@@@-SGA.\n--------------------------------------------------------------------------------\nPMID: 36952446\nTitle: Characterization of methylation profiles in spontaneous preterm birth placental villous tissue\nSource: PLoS One (2023)\nAbstract: Characterization of <m>methylation</m> profiles in spontaneous @DISEASE_Premature_Birth @DISEASE_MESH:D047928 @@@preterm <m>birth</m>@@@ placental villous tissue\n--------------------------------------------------------------------------------\nPMID: 34360600\nTitle: Individual DNA Methylation Pattern Shifts in Nanoparticles-Exposed Workers Analyzed in Four Consecutive Years\nSource: Int J Mol Sci (2021)\nAbstract: Many authors investigated and confirmed DNA <m>methylation</m> changes on an individual basis after specific interventions, such as @DISEASE_Weight_Loss @DISEASE_MESH:D015431 @@@<m>weight</m> loss@@@ in a timeframe of up to two years.\n--------------------------------------------------------------------------------\nPMID: 40748883\nTitle: Association of FGF Receptor-2rs2981578 SNP with breast cancer in women at the University of Gondar Comprehensive Specialized Hospital, Ethiopia\nSource: PLoS One (2025)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 33430764\nTitle: Maternal folic acid impacts DNA methylation profile in male rat offspring implicated in neurodevelopment and learning/memory abilities\nSource: Genes Nutr (2021)\nAbstract: A meta-analysis that included 1988 newborns from two European <m>birth</m> cohorts revealed that maternal plasma @CHEMICAL_Folic_Acid @CHEMICAL_MESH:D005492 @@@folate@@@ during pregnancy impacted epigenome-wide DNA <m>methylation</m> in the cord blood.\n--------------------------------------------------------------------------------\nPMID: 36678251\nTitle: Joint Effects of Prenatal Folic Acid Supplement with Prenatal Multivitamin and Iron Supplement on Obesity in Preschoolers Born SGA: Sex Specific Difference\nSource: Nutrients (2023)\nAbstract: Similarly, one of our previous studies found that placenta areas mediated the positive association between DNA <m>methylation</m> of @GENE_FGFR2 @GENE_2263 @@@<m>FGFR2</m>@@@ in placenta and full-term low <m>birth</m> <m>weight</m> only in @SPECIES_9606 @@@girls@@@, but not in boys.\n--------------------------------------------------------------------------------\n\n```\n\n', result_entity_names=[], used_in_final_answer=False),

In [ ]:
execution_results.final_response

'Yes. A human study (PMID:25431941) found that higher methylation at three FGFR2 CpG sites in neonatal cord blood was associated with high birth-weight centile. The association was observed in a discovery sample of 12 newborns and remained statistically significant in a follow-up cohort of 110 participants (p=0.004–0.027).\n\nHowever, the evidence is limited: the follow-up was not clearly an independent external replication, no retrieved study directly assessed large-for-gestational-age status, and another human placental study (PMID:29588807) found higher methylation at one FGFR2 site associated with low birth weight. Thus, the association with high birth-weight centile is supported, but its generalizability and direction across tissues remain uncertain.\n\nFINAL DECISION: YES'

In [ ]:
execution_results.successful_tool_path

[ToolTraceItem(step=0, agent='orchestrator', tool_name='go_search_agent', tool_call_id='call_s1n26wB6lVObn4v4LCGpzVs1', parent_tool_call_id=None, round=1, tool_input={'knowledge_bases': ['pubmed_papers', 'gene', 'disease'], 'search_rounds_budget': 5, 'search_target': 'Determine whether methylation of the human FGFR2 gene is associated with high birth weight centile or large-for-gestational-age birth. Find human studies that directly measure FGFR2 DNA methylation and report birth weight, birth-weight centile, or large-for-gestational-age outcomes; extract direction, tissue, sample size, statistical significance, and whether evidence is replicated. Distinguish FGFR2 from other genes or nearby loci.'}, status='success', raw_output=None, result_entity_names=[], used_in_final_answer=False),
 ToolTraceItem(step=2, agent='search', tool_name='search_papers', tool_call_id='call_mwlLvdvFB58OdrCWER0sSBxS', parent_tool_call_id='call_s1n26wB6lVObn4v4LCGpzVs1', round=1, tool_input={'boolean_query_text': 'FGFR2 methylation birth weight', 'relation_query': None, 'task_name': 'FGFR2 birth weight', 'top_k': 50}, status='success', raw_output='### Executed Code:\n```python\n\nfrom biodsa.tools.pubmed.pubtator_api import pubtator_api_search_papers\nfrom biodsa.tools.pubmed.pubmed_api import pubmed_api_search_papers\nimport pandas as pd\n\ndf_list = []\nhas_relation_query = False\n\n# 1. PubMed Search (Best Relevance Sorting)\nif not has_relation_query:\n    pmid_df = pubmed_api_search_papers(\n        boolean_query_text=\'FGFR2 methylation birth weight\',\n        top_k=50,\n    )\n    if pmid_df is not None and not pmid_df.empty:\n        for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:\n            if col not in pmid_df.columns:\n                pmid_df[col] = ""\n        pmid_df = pmid_df[["PMID", "Title", "Journal", "Year", "Abstract"]]\n        df_list.append(pmid_df)\n\n# 2. PubTator3 Search (Entity highlighting, fallback)\npubtator_results = []\nfor page in range(1, 5 + 1):\n    search_results = pubtator_api_search_papers(\n        boolean_query_text=\'FGFR2 methylation birth weight\',\n        relation_query=None,\n        page=page,\n        max_retries=3,\n        max_requests_per_second=3.0\n    )\n    if search_results is not None and not search_results.empty:\n        pubtator_results.append(search_results)\n    else:\n        break\n\nif pubtator_results:\n    pubtator_df = pd.concat(pubtator_results)\n    if "Highlighted_Text" in pubtator_df.columns:\n        pubtator_df = pubtator_df.rename(columns={"Highlighted_Text": "Abstract"})\n    \n    for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:\n        if col not in pubtator_df.columns:\n            pubtator_df[col] = ""\n    pubtator_df = pubtator_df[["PMID", "Title", "Journal", "Year", "Abstract"]]\n    df_list.append(pubtator_df)\n\n# 3. Combine, Deduplicate and Format Clean Output\nif df_list:\n    final_df = pd.concat(df_list).reset_index(drop=True)\n    # Deduplicate by PMID, keeping the first occurrence (which guarantees PubMed relevance is maintained)\n    final_df = final_df.drop_duplicates(subset=["PMID"], keep="first")\n    \n    # Optional: Save to CSV for persistent logging\n    final_df.to_csv(\'/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_birth_weight.csv\', index=False)\n    print(f"The search results are saved at \'/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_birth_weight.csv\'")\n    print(f"Total results found: {len(final_df)}\\n")\n    print("=" * 80)\n    print("TOP RESULTS (Showing up to 15 most relevant):")\n    print("=" * 80)\n    \n    # FORMAT FOR LLM: Clean text layout rather than Markdown table\n    for idx, row in final_df.head(15).iterrows():\n        pmid = row.get(\'PMID\', \'N/A\')\n        title = row.get(\'Title\', \'No Title\')\n        journal = row.get(\'Journal\', \'Unknown\')\n        year = row.get(\'Year\', \'Unknown\')\n        abstract = str(row.get(\'Abstract\', \'No Abstract Available\'))\n        \n        # Clean abstract spaces and truncate at 1200 chars to save context window\n        abstract = " ".join(abstract.split())\n        if len(abstract) > 1200:\n            abstract = abstract[:1200] + " ... [Truncated]"\n            \n        print(f"PMID: {pmid}")\n        print(f"Title: {title}")\n        print(f"Source: {journal} ({year})")\n        print(f"Abstract: {abstract}")\n        print("-" * 80)\nelse:\n    print("No search results found. Please try again with different query. TIP: Try simpler keyword phrases.")\n\n```\n\n### Output:\n```\nThe search results are saved at \'/home/data4/xiangyu/BioDSA/tutorials/workdir/FGFR2_birth_weight.csv\'\nTotal results found: 52\n\n================================================================================\nTOP RESULTS (Showing up to 15 most relevant):\n================================================================================\nPMID: 25431941\nTitle: Methylation of the FGFR2 gene is associated with high birth weight centile in humans.\nSource: Epigenomics (2014)\nAbstract: AIMS: This study examined links between DNA methylation and birth weight centile (BWC), and explored the impact of genetic variation. MATERIALS & METHODS: Using HumanMethylation450 arrays, we examined candidate gene-associated CpGs in cord blood from newborns with low (<15th centile), medium (40-60th centile) and high (>85th centile) BWC (n = 12). Candidates were examined in an investigation cohort (n = 110) using pyrosequencing and genotyping for putative methylation-associated polymorphisms performed using standard PCR. RESULTS: Array analysis identified 314 candidate genes associated with BWC extremes, four of which showed ≥ 4 BWC-linked CpGs. Of these, PM20D1 and MI886 suggested genetically determined methylation levels. However, methylation at three CpGs in FGFR2 remained significantly associated with high BWC (p = 0.004-0.027). CONCLUSION: We identified a novel biologically plausible candidate (FGFR2) for with BWC that merits further study.\n--------------------------------------------------------------------------------\nPMID: 29588807\nTitle: Placental surface area mediates the association between FGFR2 methylation in placenta and full-term low birth weight in girls.\nSource: Clinical epigenetics (2018)\nAbstract: BACKGROUND: Fibroblast growth factor receptor 2 (FGFR2) gene encodes a protein of the fibroblast growth factor receptor family. FGFR2 gene expression is associated with the regulation of implantation process of placenta which plays a vital role in fetal growth. DNA methylation is widely known as a mechanism of fetal growth. However, it is unclear whether and how DNA methylation of FGFR2 gene in the placenta is associated with full-term low birth weight. This case-control study aims to explore the links between FGFR2 methylation in placenta and full-term low birth weight and to further examine the mediation effect of placental surface area on this association. RESULTS: We conducted analyses for each of the five valid CpG sites at FGFR2 in 165 mother-baby pairs (86 FT-LBW vs. 79 FT-NBW) and found that per one standard deviation increase in the DNA methylation of CpG 11 at FGFR2 was associated with 1.64-fold higher risk of full-term low birth weight (OR = 1.64, 95% CI = [1.07, 2.52]) and 0.18 standard deviation decrease in placental surface area (β = - 0.18; standard error = 0.08, p = 0.02). The mediation effect of placental surface area on the association between DNA methylation and  ... [Truncated]\n--------------------------------------------------------------------------------\nPMID: 38534435\nTitle: The "Bad Father": Paternal Role in Biology of Pregnancy and in Birth Outcome\nSource: Biology (Basel) (2024)\nAbstract: Moreover, compared to younger fathers of 25-29 years, paternal age over 45 years increases the risk of @DISEASE_Birth_Weight @DISEASE_MESH:D001724 @@@low <m>birth</m> <m>weight</m>@@@ (@DISEASE_Birth_Weight @DISEASE_MESH:D001724 @@@LBW@@@), PTB, and late @DISEASE_Stillbirth @DISEASE_MESH:D050497 @@@stillbirth@@@.\n--------------------------------------------------------------------------------\nPMID: 37058433\nTitle: High-Dimensional Mediation Analysis: A New Method Applied to Maternal Smoking, Placental DNA Methylation, and Birth Outcomes\nSource: Environ Health Perspect (2023)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 36611709\nTitle: Vascular Distribution and Expression Patterns of Angiogenic Factors in Caruncle during the Early Stage of Pregnancy in Goats (Capra hircus)\nSource: Animals (Basel) (2022)\nAbstract: The molecular <m>weight</m> of CpG 9-, CpG 10-, and CpG 11- containing fragments overlapped, thus, the average of the three CG-containing fragments represented DNA <m>methylation</m> of CpG 9.10.11, similar to CpG 16.17 and CpG 19.20.\n--------------------------------------------------------------------------------\nPMID: 36091392\nTitle: The shared mother-child epigenetic signature of neglect is related to maternal adverse events\nSource: Front Physiol (2022)\nAbstract: In consonance, the neglectful condition has been associated with having a @DISEASE_Premature_Birth @DISEASE_MESH:D047928 @@@preterm <m>birth</m>@@@ with lower <m>birth</m> <m>weight</m> and with developing @DISEASE_Obesity @DISEASE_MESH:D009765 @@@obesity@@@ over the life course.\n--------------------------------------------------------------------------------\nPMID: 37697338\nTitle: Analysis of DNA methylation at birth and in childhood reveals changes associated with season of birth and latitude\nSource: Clin Epigenetics (2023)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 39325622\nTitle: Placenta-derived SOD3 deletion impairs maternal behavior via alterations in FGF/FGFR-prolactin signaling axis\nSource: Cell Rep (2024)\nAbstract: These results indicate that placental @GENE_SOD3 @GENE_6649 @@@Sod3@@@ KO attenuates @GENE_FGFR2 @GENE_2263 @@@<m>FGFR2</m>@@@ and @GENE_FGF1 @GENE_2246 @@@FGF1@@@ expression through TET-@GENE_IDH1 @GENE_15926 @@@IDH@@@ inactivation-induced increases in DNA <m>methylation</m> levels at the promoter of @GENE_FGFR2 @GENE_2263 @@@<m>Fgfr2</m>@@@ and @GENE_FGF1 @GENE_2246 @@@Fgf1@@@ genes.\n--------------------------------------------------------------------------------\nPMID: 34930438\nTitle: The angiogenic properties of human amniotic membrane stem cells are enhanced in gestational diabetes and associate with fetal adiposity\nSource: Stem Cell Res Ther (2021)\nAbstract: Of note, @GENE_FGFR2 @GENE_2263 @@@<m>FGFR2</m>@@@ expression correlated significantly with neonatal sum of skinfolds and placental <m>weight</m>, which accords with a previous report showing a positive relationship between @GENE_FGF2 @GENE_2247 @@@FGF2@@@ and <m>birth</m>-<m>weight</m> and placental size in pregnancies complicated by @DISEASE_Diabetes_Mellitus @DISEASE_MESH:D003920 @@@diabetes@@@ [57].\n--------------------------------------------------------------------------------\nPMID: 39766778\nTitle: Placenta Thickness Mediates the Association Between AKIP1 Methylation in Maternal Peripheral Blood and Full-Term Small for Gestational Age Neonates\nSource: Genes (Basel) (2024)\nAbstract: The mediation effect of placental <m>weight</m> on the association of DNA <m>methylation</m> of CpG4 in @GENE_AKIP1 @GENE_56672 @@@AKIP1@@@ and @CHEMICAL_Tegafur @CHEMICAL_MESH:D005641 @@@FT@@@-SGA.\n--------------------------------------------------------------------------------\nPMID: 36952446\nTitle: Characterization of methylation profiles in spontaneous preterm birth placental villous tissue\nSource: PLoS One (2023)\nAbstract: Characterization of <m>methylation</m> profiles in spontaneous @DISEASE_Premature_Birth @DISEASE_MESH:D047928 @@@preterm <m>birth</m>@@@ placental villous tissue\n--------------------------------------------------------------------------------\nPMID: 34360600\nTitle: Individual DNA Methylation Pattern Shifts in Nanoparticles-Exposed Workers Analyzed in Four Consecutive Years\nSource: Int J Mol Sci (2021)\nAbstract: Many authors investigated and confirmed DNA <m>methylation</m> changes on an individual basis after specific interventions, such as @DISEASE_Weight_Loss @DISEASE_MESH:D015431 @@@<m>weight</m> loss@@@ in a timeframe of up to two years.\n--------------------------------------------------------------------------------\nPMID: 40748883\nTitle: Association of FGF Receptor-2rs2981578 SNP with breast cancer in women at the University of Gondar Comprehensive Specialized Hospital, Ethiopia\nSource: PLoS One (2025)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 33430764\nTitle: Maternal folic acid impacts DNA methylation profile in male rat offspring implicated in neurodevelopment and learning/memory abilities\nSource: Genes Nutr (2021)\nAbstract: A meta-analysis that included 1988 newborns from two European <m>birth</m> cohorts revealed that maternal plasma @CHEMICAL_Folic_Acid @CHEMICAL_MESH:D005492 @@@folate@@@ during pregnancy impacted epigenome-wide DNA <m>methylation</m> in the cord blood.\n--------------------------------------------------------------------------------\nPMID: 36678251\nTitle: Joint Effects of Prenatal Folic Acid Supplement with Prenatal Multivitamin and Iron Supplement on Obesity in Preschoolers Born SGA: Sex Specific Difference\nSource: Nutrients (2023)\nAbstract: Similarly, one of our previous studies found that placenta areas mediated the positive association between DNA <m>methylation</m> of @GENE_FGFR2 @GENE_2263 @@@<m>FGFR2</m>@@@ in placenta and full-term low <m>birth</m> <m>weight</m> only in @SPECIES_9606 @@@girls@@@, but not in boys.\n--------------------------------------------------------------------------------\n\n```\n\n', result_entity_names=[], used_in_final_answer=False),

In [ ]:
# Generate PDF report following the structured format:
# 1. User query
# 2. Agent exploration trajectories (messages only, no code)
# 3. Final response with embedded artifacts
# 4. Supplementary materials with code blocks and execution results
# execution_results.to_pdf(output_dir="test_artifacts")
agent.clear_workspace()
print("Done!")

2026-09-13 22:41:45,555 - WARNING - Sandbox is not available. Nothing to clear.

Done!

In [1]:
import os
import json
import tempfile
from biodsa.tools.chemical.chemicals import fetch_molecule_profile_fast

# 定义测试用例：涵盖俗名、SMILES、IUPAC名、InChIKey 和 异常边界情况
TEST_CASES = [
    {
        "name": "俗名 (之前报错的案例)",
        "identifier": "minocycline",
        "expect_success": True
    },
    {
        "name": "常见药品俗名",
        "identifier": "aspirin",
        "expect_success": True
    },
    {
        "name": "标准 SMILES",
        "identifier": "CC(=O)Oc1ccccc1C(=O)O",  # 阿司匹林 SMILES
        "expect_success": True
    },
    {
        "name": "IUPAC 名称 (走 OPSIN 解析)",
        "identifier": "2-acetoxybenzoic acid",
        "expect_success": True
    },
    {
        "name": "InChIKey 格式",
        "identifier": "BSYNRYMUTXBXSQ-UHFFFAOYSA-N",  # 柠檬酸 InChIKey
        "expect_success": True
    },
    {
        "name": "无效/不存在的标识符 (测试容错性)",
        "identifier": "invalid_compound_xyz_12345",
        "expect_success": False
    }
]

def run_chemical_profile_tests():
    print("=" * 70)
    print("🚀 开始运行分子 Profile 接口测试...")
    print("=" * 70)
    
    passed_count = 0
    failed_count = 0

    # 使用临时文件保存 JSON 结果
    with tempfile.TemporaryDirectory() as tmpdir:
        for idx, case in enumerate(TEST_CASES, 1):
            name = case["name"]
            identifier = case["identifier"]
            expect_success = case["expect_success"]
            
            save_path = os.path.join(tmpdir, f"test_out_{idx}.json")
            
            print(f"\n[Test {idx}/{len(TEST_CASES)}] {name}")
            print(f"👉 输入标识符: '{identifier}'")
            
            try:
                # 调用核心函数
                details, output = fetch_molecule_profile_fast(
                    identifier=identifier, 
                    save_path=save_path
                )
                
                has_error = "error" in details
                
                if expect_success and not has_error:
                    print("✅ 测试通过！成功解析分子信息。")
                    if "canonical_smiles" in details:
                        print(f"   - SMILES: {details['canonical_smiles']}")
                    if "inchikey" in details:
                        print(f"   - InChIKey: {details['inchikey']}")
                    if "pubchem" in details and "CID" in details["pubchem"]:
                        print(f"   - PubChem CID: {details['pubchem']['CID']}")
                    passed_count += 1
                elif not expect_success and has_error:
                    print("✅ 测试通过！按预期触发错误拦截机制。")
                    print(f"   - 拦截日志: {details.get('error')}")
                    passed_count += 1
                else:
                    print("❌ 测试未通过！结果与预期不符。")
                    print(f"   - 输出日志:\n{output}")
                    failed_count += 1

            except Exception as e:
                print(f"❌ 测试运行抛出异常: {e}")
                failed_count += 1

    print("\n" + "=" * 70)
    print(f"📊 测试总结: 总计 {len(TEST_CASES)} 个测试项 | ✅ 成功: {passed_count} | ❌ 失败: {failed_count}")
    print("=" * 70)

if __name__ == "__main__":
    run_chemical_profile_tests()

======================================================================
🚀 开始运行分子 Profile 接口测试...
======================================================================

[Test 1/6] 俗名 (之前报错的案例)
👉 输入标识符: 'minocycline'
✅ 测试通过！成功解析分子信息。
   - SMILES: CN(C)c1ccc(O)c2c1CC1CC3C(N(C)C)C(=O)C(C(N)=O)=C(O)C3(O)C(=O)C1=C2O
   - InChIKey: FFTVPQUHLQBXQZ-UHFFFAOYSA-N
   - PubChem CID: 54687237

[Test 2/6] 常见药品俗名
👉 输入标识符: 'aspirin'
✅ 测试通过！成功解析分子信息。
   - SMILES: CC(=O)Oc1ccccc1C(=O)O
   - InChIKey: BSYNRYMUTXBXSQ-UHFFFAOYSA-N
   - PubChem CID: 2244

[Test 3/6] 标准 SMILES
👉 输入标识符: 'CC(=O)Oc1ccccc1C(=O)O'
✅ 测试通过！成功解析分子信息。
   - SMILES: CC(=O)Oc1ccccc1C(=O)O
   - InChIKey: BSYNRYMUTXBXSQ-UHFFFAOYSA-N
   - PubChem CID: 2244

[Test 4/6] IUPAC 名称 (走 OPSIN 解析)
👉 输入标识符: '2-acetoxybenzoic acid'
✅ 测试通过！成功解析分子信息。
   - SMILES: CC(=O)Oc1ccccc1C(=O)O
   - InChIKey: BSYNRYMUTXBXSQ-UHFFFAOYSA-N
   - PubChem CID: 2244

[Test 5/6] InChIKey 格式
👉 输入标识符: 'BSYNRYMUTXBXSQ-UHFFFAOYSA-N'
✅ 测试通过！成功解析分子信息。
   - SMILES: CC(=O)Oc1ccccc1C(=O)O
   - InChIKey: BSYNRYMUTXBXSQ-UHFFFAOYSA-N
   - PubChem CID: 2244

[Test 6/6] 无效/不存在的标识符 (测试容错性)
👉 输入标识符: 'invalid_compound_xyz_12345'
✅ 测试通过！按预期触发错误拦截机制。
   - 拦截日志: Unable to parse or resolve input.

======================================================================
📊 测试总结: 总计 6 个测试项 | ✅ 成功: 6 | ❌ 失败: 0
======================================================================

In [5]:
import os
import json
import logging
from typing import List, Dict, Any, Optional

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# 定义需要被拦截并特殊处理的伪工具
PSEUDO_TOOLS = {"add_to_graph", "report_key_findings", "go_search_agent"}

def get_full_tools_schema() -> List[Dict[str, Any]]:
    """
    返回全局完整的 Tools Schema。
    包含了化学、生物（Protein）、医学文献（PubMed/PubTator）、疾病（Disease）和药物（Drug）工具。
    精简了 Description 以节省 Token，并严格定义了所有的输入参数。
    """
    return [
        # ==================== 化学与生物工具 ====================
        {
            "type": "function",
            "function": {
                "name": "fetch_molecule_profile",
                "description": "Calculates physicochemical properties, ADMET descriptors, functional groups, NMR peaks, and GHS safety/hazards. Use for virtual screening, oral availability, or evaluating safety risks.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "Short task description. e.g., 'virtual screening', 'check safety'"},
                        "identifier": {"type": "string", "description": "Molecule identifier (SMILES, SELFIES, or common name)."}
                    },
                    "required": ["task_name", "identifier"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "fetch_bioactivity_and_targets",
                "description": "Queries ChEMBL to find a molecule's biological targets, mechanism of action, and clinical trial phase. Use for 'targets', 'receptors', or 'drug approval status'.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "Short description. e.g., 'find targets', 'clinical phase'"},
                        "identifier": {"type": "string", "description": "Molecule identifier (SMILES, SELFIES, or common name)."}
                    },
                    "required": ["task_name", "identifier"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "compute_quantum_mechanics",
                "description": "Calculates quantum chemical properties like LUMO/HOMO energy and Dipole Moment.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "Short description, e.g., 'lumo calculation'"},
                        "smiles": {"type": "string", "description": "The exact SMILES/SELFIES string or name of the molecule."}
                    },
                    "required": ["task_name", "smiles"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "fetch_reaction_details",
                "description": "Fetches empirical chemical reaction data (conditions, yield, reagents, catalysts) from ORD database. Supports forward prediction and retrosynthesis search.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "Short descriptive name, e.g., 'predict yield', 'find solvents'"},
                        "reaction_smiles": {
                            "type": "string", 
                            "description": "Chemical query (SMILES, SELFIES, InChIKey, or IUPAC name). Modes: 1) Full exact match: 'Reactants>>Products'; 2) Forward prediction: 'Reactants>>' or 'Reactants'; 3) Retrosynthesis/Conditions: '>>Product' or 'Product'."
                        },
                        "limit": {"type": "integer", "description": "Maximum number of reaction records to return.", "default": 5}
                    },
                    "required": ["task_name", "reaction_smiles"]
                }
            }
        },
{
            "type": "function",
            "function": {
                "name": "query_protein",
                "description": "Analyzes a protein from sequence or UniProt accession. Retrieves sequence properties, homologs, annotations, catalytic info, pathways, and GO terms.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "Short description used for output filename, e.g., 'analyze protein'"},
                        "sequence": {"type": "string", "description": "Protein amino-acid sequence or FASTA. Provide exactly one of sequence or accession."},
                        "accession": {"type": "string", "description": "UniProt primary accession. Provide exactly one of sequence or accession."},
                        "query": {"type": "string", "description": "Free-form protein question, e.g., 'identify its function'."}
                    },
                    "required": ["task_name"]
                }
            }
        },

        # ==================== PubMed 与 PubTator 工具 ====================
        {
            "type": "function",
            "function": {
                "name": "get_paper_references",
                "description": "Get paper references (citations) for a list of PubMed IDs.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "A less than three word description of what the search is for."},
                        "pmids": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of PubMed IDs (PMIDs) to get references for."
                        },
                        "batch_size": {"type": "integer", "default": 100},
                        "mini_batch_size": {"type": "integer", "default": 20},
                        "max_workers": {"type": "integer", "default": 4},
                        "rate_limit": {"type": "number", "default": 3.0}
                    },
                    "required": ["task_name", "pmids"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "fetch_paper_content",
                "description": "Fetch and extract specific content from a PubMed paper by PMID using keyword/regex filtering.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "pmid": {"type": "string", "description": "A single PubMed ID (PMID) to fetch content for."},
                        "filter_keywords": {"type": "string", "description": "Keywords or regex pattern to search for and extract from the paper content."}
                    },
                    "required": ["pmid", "filter_keywords"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "fetch_paper_annotations",
                "description": "Fetch biomedical entity annotations from PubTator3 for a list of PubMed IDs.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "pmids": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of PubMed IDs (PMIDs) to fetch annotations for."
                        },
                        "batch_size": {"type": "integer", "default": 50},
                        "max_retries": {"type": "integer", "default": 3},
                        "max_requests_per_second": {"type": "number", "default": 3.0}
                    },
                    "required": ["pmids"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "find_entities",
                "description": "Find and autocomplete biomedical entity names in the PubTator3 database.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query_text": {"type": "string", "description": "A single search term (partial entity name) to find entities."},
                        "concept_type": {
                            "type": "string",
                            "enum": ["GENE", "DISEASE", "CHEMICAL", "VARIANT", "SPECIES", "CELLLINE"],
                            "description": "Optional entity concept type."
                        },
                        "limit": {"type": "integer", "default": 10},
                        "max_retries": {"type": "integer", "default": 3},
                        "max_requests_per_second": {"type": "number", "default": 3.0}
                    },
                    "required": ["query_text"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "search_papers",
                "description": "Search PubMed articles using keywords, boolean queries, or relation queries. TIP: Simple keywords often yield better results.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "A less than three word description of what the search is for."},
                        "boolean_query_text": {"type": "string", "description": "Boolean query or simple natural language text."},
                        "relation_query": {"type": "object", "description": "Relation-based query configuration."},
                        "top_k": {"type": "integer", "default": 100, "description": "Number of top results to return."},
                        "max_retries": {"type": "integer", "default": 3},
                        "max_requests_per_second": {"type": "number", "default": 3.0}
                    },
                    "required": ["task_name"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "find_related_entities",
                "description": "Find entities that have a specific relationship with a target entity using PubTator3 relations API.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "target_entity": {"type": "string", "description": "The target entity to find relations for."},
                        "relation_type": {
                            "type": "string",
                            "enum": [
                                "ASSOCIATE", "CAUSE", "COMPARE", "COTREAT", "DRUG_INTERACT",
                                "INHIBIT", "INTERACT", "NEGATIVE_CORRELATE", "POSITIVE_CORRELATE",
                                "PREVENT", "STIMULATE", "TREAT", "ANY"
                            ],
                            "description": "Type of relation to search for."
                        },
                        "related_entity_type": {"type": "string", "description": "Type or ID of related entities to find."},
                        "limit": {"type": "integer", "default": 100},
                        "max_retries": {"type": "integer", "default": 3},
                        "max_requests_per_second": {"type": "number", "default": 3.0}
                    },
                    "required": ["target_entity", "relation_type", "related_entity_type"]
                }
            }
        },

        # ==================== Disease 疾病信息工具 ====================
        {
            "type": "function",
            "function": {
                "name": "unified_disease_search",
                "description": "Search for diseases across multiple authoritative databases (BioThings, KEGG, Open Targets) with a single search term.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "A less than three word description of what the search is for."},
                        "search_term": {"type": "string", "description": "Disease name, condition, or symptoms."},
                        "limit_per_source": {"type": "integer", "default": 10},
                        "sources": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of sources. Options: 'biothings', 'kegg', 'opentargets'."
                        }
                    },
                    "required": ["task_name", "search_term"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "fetch_disease_details",
                "description": "Fetch comprehensive disease details using any identifier (MONDO, DOID, OMIM, MeSH, KEGG, EFO, or name).",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "A less than three word description of what the fetch is for."},
                        "disease_id": {"type": "string", "description": "Disease identifier or disease name."},
                        "id_type": {"type": "string", "description": "Type of identifier if known. Auto-detected if not specified."},
                        "sources": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of sources. Options: 'biothings', 'kegg', 'opentargets'."
                        }
                    },
                    "required": ["task_name", "disease_id"]
                }
            }
        },

        # ==================== Drug 药物信息工具 ====================
        {
            "type": "function",
            "function": {
                "name": "unified_drug_search",
                "description": "Search for drugs across multiple databases (BioThings, OpenFDA, KEGG, Open Targets). Returns FDA status, labels, and trials.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "A less than three word description of what the search is for."},
                        "search_term": {"type": "string", "description": "Drug name, compound name, condition, or any search term."},
                        "limit_per_source": {"type": "integer", "default": 10},
                        "sources": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'."
                        }
                    },
                    "required": ["task_name", "search_term"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "fetch_drug_details",
                "description": "Fetch comprehensive drug details using any identifier (DrugBank, ChEBI, ChEMBL, PubChem, OpenFDA, KEGG, or name).",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task_name": {"type": "string", "description": "A less than three word description of what the fetch is for."},
                        "drug_id": {"type": "string", "description": "Drug identifier of any type or name."},
                        "id_type": {"type": "string", "description": "Type of identifier if known. Auto-detected if not specified."},
                        "sources": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'."
                        }
                    },
                    "required": ["task_name", "drug_id"]
                }
            }
        },
        # ==================== 代码执行工具 ====================
        {
            "type": "function",
            "function": {
                "name": "code_execution",
                "description": "Execute Python code in a secure sandbox environment. Useful for custom calculations, data manipulation, or using specific libraries (e.g., RDKit, SELFIES, pandas) when predefined tools are insufficient.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string", 
                            "description": "The Python code script to execute."
                        },
                        "language": {
                            "type": "string", 
                            "description": "The programming language to use (e.g., 'python').", 
                            "default": "python"
                        }
                    },
                    "required": ["code"]
                }
            }
        }
    ]

def process_single_sample(sample_dir: str) -> Optional[Dict[str, Any]]:
    meta_path = os.path.join(sample_dir, "meta.json")
    successful_path_file = os.path.join(sample_dir, "successful_tool_path.json")
    final_response_file = os.path.join(sample_dir, "final_response.md")

    if not os.path.exists(successful_path_file) or not os.path.exists(meta_path):
        return None

    try:
        with open(meta_path, "r", encoding="utf-8") as f:
            meta_data = json.load(f)
        user_query = meta_data.get("user_query") or meta_data.get("question")
        if not user_query: return None

        with open(successful_path_file, "r", encoding="utf-8") as f:
            successful_path = json.load(f)

        final_answer = ""
        if os.path.exists(final_response_file):
            with open(final_response_file, "r", encoding="utf-8") as f:
                final_answer = f.read().strip()
    except Exception as e:
        logger.error(f"读取异常 [{sample_dir}]: {e}")
        return None

    # 获取全局全量工具列表
    tools_schema = get_full_tools_schema()
    
    messages = [
        {"role": "user", "content": user_query}
    ]

    for step in successful_path:
        tool_name = step.get("tool_name", "")
        tool_input = step.get("tool_input", {})
        raw_output = step.get("raw_output")

        # ---------------------------------------------------------
        # 核心清洗逻辑：拦截并处理“伪工具”
        # ---------------------------------------------------------
        
        # 1. 废弃采样工具 (完全忽略)
        if tool_name == "add_to_graph":
            continue
            
        # 2. 将任务下发 (go_search_agent) 转化为内部思考/规划
        elif tool_name == "go_search_agent":
            target = tool_input.get("search_target", "")
            if target:
                thought = f"<think>\nPlan: I need to search biomedical literature for the following target: {target}\n</think>"
                messages.append({"role": "assistant", "content": thought})
            continue # 跳过 tool_response
            
        # 3. 将中间总结 (report_key_findings) 转化为内部反思
        elif tool_name == "report_key_findings":
            findings = tool_input.get("key_findings", [])
            findings_text = "\n".join([f"- {f.get('finding', '')}" for f in findings])
            if findings_text:
                thought = f"<think>\nKey Findings Summary:\n{findings_text}\n</think>"
                messages.append({"role": "assistant", "content": thought})
            continue # 跳过 tool_response

        # ---------------------------------------------------------
        # 正常工具调用逻辑
        # ---------------------------------------------------------
        else:
            # === 新增：强制清理 query_protein 的历史冗余参数 ===
            if tool_name == "query_protein":
                allowed_keys = {"task_name", "sequence", "accession", "query"}
                # 只保留白名单内的参数
                tool_input = {k: v for k, v in tool_input.items() if k in allowed_keys}

            tool_call_content = {
                "name": tool_name,
                "arguments": tool_input
            }
            messages.append({
                "role": "tool_call",
                "content": json.dumps(tool_call_content, ensure_ascii=False)
            })

            if raw_output is None:
                raw_output_str = json.dumps({"status": step.get("status", "success")}, ensure_ascii=False)
            else:
                raw_output_str = raw_output if isinstance(raw_output, str) else json.dumps(raw_output, ensure_ascii=False)
                
            messages.append({
                "role": "tool_response",
                "content": raw_output_str
            })

    # 4. 合并连续的 assistant 消息 (避免格式突兀)
    merged_messages = []
    for msg in messages:
        if merged_messages and merged_messages[-1]["role"] == "assistant" and msg["role"] == "assistant":
            merged_messages[-1]["content"] += "\n" + msg["content"]
        else:
            merged_messages.append(msg)

    # 5. 追加最终回复
    if final_answer:
        if merged_messages[-1]["role"] == "assistant":
            merged_messages[-1]["content"] += "\n" + final_answer
        else:
            merged_messages.append({"role": "assistant", "content": final_answer})

    return {
        "tools": json.dumps(tools_schema, ensure_ascii=False),
        "messages": merged_messages
    }

def main_convert_dataset(root_dir: str, output_file: str):
    if not os.path.exists(root_dir): return
    logger.info("开始单进程递归扫描...")
    
    sample_dirs = []
    for current_root, _, files in os.walk(root_dir):
        if "successful_tool_path.json" in files and "meta.json" in files:
            sample_dirs.append(current_root)

    total_samples = len(sample_dirs)
    logger.info(f"匹配到 {total_samples} 个样本目录")

    with open(output_file, "w", encoding="utf-8") as f:
        for idx, s_dir in enumerate(sample_dirs, 1):
            record = process_single_sample(s_dir)
            if record:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
            
            if idx % 500 == 0: logger.info(f"已处理 {idx}/{total_samples} ...")

    logger.info(f"数据集构建完成！路径: {output_file}")


if __name__ == "__main__":
    DATASET_ROOT_DIR = "/home/data4/xiangyu/BioDSA/tutorials/workdir"
    OUTPUT_JSONL = "/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train.jsonl"
    main_convert_dataset(DATASET_ROOT_DIR, OUTPUT_JSONL)

In [11]:
import os
import json

ROOT = "/home/data4/xiangyu/BioDSA/tutorials/workdir"

TARGET = "Do aRDS Subphenotypes Respond Differently to Randomized Fluid Management Strategy?"

for current_root, _, files in os.walk(ROOT):
    if "meta.json" not in files or "successful_tool_path.json" not in files:
        continue

    meta_path = os.path.join(current_root, "meta.json")
    path_file = os.path.join(current_root, "successful_tool_path.json")

    try:
        with open(meta_path, "r", encoding="utf-8") as f:
            meta = json.load(f)

        query = meta.get("user_query") or meta.get("question") or ""
        if TARGET.lower() not in query.lower():
            continue

        with open(path_file, "r", encoding="utf-8") as f:
            path = json.load(f)

        print("\n" + "=" * 100)
        print("Sample directory:", current_root)
        print("Query:", query)
        print("Total path steps:", len(path))

        for i, step in enumerate(path):
            print(f"\n--- Step {i + 1} ---")
            print("tool_name:", step.get("tool_name"))
            print("status:", step.get("status"))
            print("tool_input:")
            print(json.dumps(
                step.get("tool_input"),
                ensure_ascii=False,
                indent=2
            )[:3000])

            output = step.get("raw_output")
            if isinstance(output, (dict, list)):
                output = json.dumps(output, ensure_ascii=False, indent=2)

            print("raw_output:")
            print(str(output)[:2000])

        break

    except Exception as e:
        print("Error:", current_root, repr(e))

====================================================================================================
Sample directory: /home/data4/xiangyu/BioDSA/tutorials/workdir/pubmedqa_sample_409
Query: Do aRDS Subphenotypes Respond Differently to Randomized Fluid Management Strategy?

Please research this question using your tools. You MUST conclude your final response with exactly one of the following lines: 'FINAL DECISION: YES', 'FINAL DECISION: NO', or 'FINAL DECISION: MAYBE'.
Total path steps: 1

--- Step 1 ---
tool_name: add_to_graph
status: success
tool_input:
{
  "entities": [
    {
      "entity_type": "PAPER",
      "name": "PMID:34461969",
      "observations": [
        "A 2021 retrospective analysis identified three clinical ARDS phenotypes and reported phenotype-by-randomized-fluid-management interaction for 60-day mortality (P=0.01); retrieved summary states conservative management benefited phenotype II with opposite direction in phenotype III.",
        "This is a three-clinical-phenotype analysis, not the conventional two-class hypo-/hyperinflammatory latent-subphenotype analysis; subgroup effect estimates were not available in the retrieved evidence."
      ],
      "source_tools": [
        {
          "relevance": "Retrieved literature-search summary for randomized fluid strategy phenotype interaction",
          "tool_call_id": "PMID:34461969"
        }
      ]
    }
  ],
  "observations": null,
  "relations": null
}
raw_output:
{"success": true, "results": {"entities_created": {"count": 1, "entities": [{"name": "PMID:34461969", "entityType": "PAPER", "observations": ["A 2021 retrospective analysis identified three clinical ARDS phenotypes and reported phenotype-by-randomized-fluid-management interaction for 60-day mortality (P=0.01); retrieved summary states conservative management benefited phenotype II with opposite direction in phenotype III.", "This is a three-clinical-phenotype analysis, not the conventional two-class hypo-/hyperinflammatory latent-subphenotype analysis; subgroup effect estimates were not available in the retrieved evidence."]}]}}, "provenance": {"tool_call_id": "call_DgN7Q0H36U0vGf7RqJxcF66S", "tool_name": "add_to_graph", "agent": "orchestrator", "round": 5, "parent_tool_call_id": "call_9feoeYZTXPR0pZ5tNMEjLJwH"}}

In [22]:
import json
from swift import get_processor, get_template

# 1. 配置文件路径与模型名
DATASET_JSONL_PATH = "/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train.jsonl"
MODEL_ID = "/home/data4/xiangyu/models/Qwen3.5-9B"

# 2. 加载 ms-swift 的 Processor 和 Template
print(f"正在加载模型 Processor: {MODEL_ID} ...")
processor = get_processor(MODEL_ID)

# 初始化 Template (指定 agent_template='hermes')
template = get_template(processor, agent_template='hermes')
template.set_mode('train')

print(f"当前使用的 agent_template 为: {template._agent_template}\n")

# 3. 读取 JSONL 格式的 Agent 样本
raw_data = []
with open(DATASET_JSONL_PATH, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            raw_data.append(json.loads(line))

print(f"总计读取到 {len(raw_data)} 条 Agent 样本。")

# 4. 抽取第 1 条数据进行 Encode 校验
if len(raw_data) > 0:
    sample = raw_data[1]
    
    # 打印原始数据的基本结构，确认没有嵌套错误
    print("\n[DEBUG] 样本包含的 Keys:", sample.keys())
    print("[DEBUG] 样本轮数 (Messages length):", len(sample.get("messages", [])))

    # ms-swift 可以直接接收这种包含 'tools' 和 'messages' 的原生字典
    # 所有的角色 (tool_call, tool_response) 都将在这里被 agent_template 自动解析为 XML 和掩码
    encoded = template.encode(sample)

    print("\n" + "=" * 80)
    print("【INPUT_IDS 解码文本 (模型能看到的完整多轮上下文)】:")
    print("=" * 80)
    print(f"{template.safe_decode(encoded['input_ids'])}\n")

    print("=" * 80)
    print("【LABELS 解码文本 (只有非 -100 的 Target/Action Token 会被保留并计算 Loss)】:")
    print("=" * 80)
    # 你会看到 user 的提问、System的工具列表、tool_response (环境返回内容) 全都被掩码掉了 (显示为 [-100 * N])
    # 只有 tool_call (模型决定调用的工具) 和最终的 assistant content 被保留！
    print(f"{template.safe_decode(encoded['labels'])}\n")
    print("=" * 80)

[WARNING:swift] Loading model from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. This will execute custom Python code shipped in the model repository (e.g. configuration_*.py, modeling_*.py, tokenization_*.py). Only proceed if you trust the source of this model.
[INFO:swift] Setting torch_dtype: torch.bfloat16
[WARNING:swift] Loading config from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. Custom Python code from the model repository will be executed. Only use models from sources you trust.
[WARNING:swift] Loading tokenizer/processor from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. Custom Python code from the model repository will be executed. Only use models from sources you trust.

正在加载模型 Processor: /home/data4/xiangyu/models/Qwen3.5-9B ...

[INFO:swift] default_system: None
[INFO:swift] max_length: 262144
[INFO:swift] response_prefix: None
[INFO:swift] agent_template: hermes
[INFO:swift] norm_bbox: norm1000

当前使用的 agent_template 为: hermes

总计读取到 3433 条 Agent 样本。

[DEBUG] 样本包含的 Keys: dict_keys(['tools', 'messages'])
[DEBUG] 样本轮数 (Messages length): 15

================================================================================
【INPUT_IDS 解码文本 (模型能看到的完整多轮上下文)】:
================================================================================
<|im_start|>system


# Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{"type": "function", "function": {"name": "fetch_molecule_profile", "description": "Calculates physicochemical properties, ADMET descriptors, functional groups, NMR peaks, and GHS safety/hazards. Use for virtual screening, oral availability, or evaluating safety risks.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "Short task description. e.g., 'virtual screening', 'check safety'"}, "identifier": {"type": "string", "description": "Molecule identifier (SMILES, SELFIES, or common name)."}}, "required": ["task_name", "identifier"]}}}
{"type": "function", "function": {"name": "fetch_bioactivity_and_targets", "description": "Queries ChEMBL to find a molecule's biological targets, mechanism of action, and clinical trial phase. Use for 'targets', 'receptors', or 'drug approval status'.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "Short description. e.g., 'find targets', 'clinical phase'"}, "identifier": {"type": "string", "description": "Molecule identifier (SMILES, SELFIES, or common name)."}}, "required": ["task_name", "identifier"]}}}
{"type": "function", "function": {"name": "compute_quantum_mechanics", "description": "Calculates quantum chemical properties like LUMO/HOMO energy and Dipole Moment.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "Short description, e.g., 'lumo calculation'"}, "smiles": {"type": "string", "description": "The exact SMILES/SELFIES string or name of the molecule."}}, "required": ["task_name", "smiles"]}}}
{"type": "function", "function": {"name": "fetch_reaction_details", "description": "Fetches empirical chemical reaction data (conditions, yield, reagents, catalysts) from ORD database. Supports forward prediction and retrosynthesis search.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "Short descriptive name, e.g., 'predict yield', 'find solvents'"}, "reaction_smiles": {"type": "string", "description": "Chemical query (SMILES, SELFIES, InChIKey, or IUPAC name). Modes: 1) Full exact match: 'Reactants>>Products'; 2) Forward prediction: 'Reactants>>' or 'Reactants'; 3) Retrosynthesis/Conditions: '>>Product' or 'Product'."}, "limit": {"type": "integer", "description": "Maximum number of reaction records to return.", "default": 5}}, "required": ["task_name", "reaction_smiles"]}}}
{"type": "function", "function": {"name": "query_protein", "description": "Analyzes a protein from sequence or UniProt accession. Retrieves sequence properties, homologs, annotations, catalytic info, pathways, and GO terms.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "Short description used for output filename, e.g., 'analyze protein'"}, "sequence": {"type": "string", "description": "Protein amino-acid sequence or FASTA. Provide exactly one of sequence or accession."}, "accession": {"type": "string", "description": "UniProt primary accession. Provide exactly one of sequence or accession."}, "query": {"type": "string", "description": "Free-form protein question, e.g., 'identify its function'."}}, "required": ["task_name"]}}}
{"type": "function", "function": {"name": "get_paper_references", "description": "Get paper references (citations) for a list of PubMed IDs.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "A less than three word description of what the search is for."}, "pmids": {"type": "array", "items": {"type": "string"}, "description": "List of PubMed IDs (PMIDs) to get references for."}, "batch_size": {"type": "integer", "default": 100}, "mini_batch_size": {"type": "integer", "default": 20}, "max_workers": {"type": "integer", "default": 4}, "rate_limit": {"type": "number", "default": 3.0}}, "required": ["task_name", "pmids"]}}}
{"type": "function", "function": {"name": "fetch_paper_content", "description": "Fetch and extract specific content from a PubMed paper by PMID using keyword/regex filtering.", "parameters": {"type": "object", "properties": {"pmid": {"type": "string", "description": "A single PubMed ID (PMID) to fetch content for."}, "filter_keywords": {"type": "string", "description": "Keywords or regex pattern to search for and extract from the paper content."}}, "required": ["pmid", "filter_keywords"]}}}
{"type": "function", "function": {"name": "fetch_paper_annotations", "description": "Fetch biomedical entity annotations from PubTator3 for a list of PubMed IDs.", "parameters": {"type": "object", "properties": {"pmids": {"type": "array", "items": {"type": "string"}, "description": "List of PubMed IDs (PMIDs) to fetch annotations for."}, "batch_size": {"type": "integer", "default": 50}, "max_retries": {"type": "integer", "default": 3}, "max_requests_per_second": {"type": "number", "default": 3.0}}, "required": ["pmids"]}}}
{"type": "function", "function": {"name": "find_entities", "description": "Find and autocomplete biomedical entity names in the PubTator3 database.", "parameters": {"type": "object", "properties": {"query_text": {"type": "string", "description": "A single search term (partial entity name) to find entities."}, "concept_type": {"type": "string", "enum": ["GENE", "DISEASE", "CHEMICAL", "VARIANT", "SPECIES", "CELLLINE"], "description": "Optional entity concept type."}, "limit": {"type": "integer", "default": 10}, "max_retries": {"type": "integer", "default": 3}, "max_requests_per_second": {"type": "number", "default": 3.0}}, "required": ["query_text"]}}}
{"type": "function", "function": {"name": "search_papers", "description": "Search PubMed articles using keywords, boolean queries, or relation queries. TIP: Simple keywords often yield better results.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "A less than three word description of what the search is for."}, "boolean_query_text": {"type": "string", "description": "Boolean query or simple natural language text."}, "relation_query": {"type": "object", "description": "Relation-based query configuration."}, "top_k": {"type": "integer", "default": 100, "description": "Number of top results to return."}, "max_retries": {"type": "integer", "default": 3}, "max_requests_per_second": {"type": "number", "default": 3.0}}, "required": ["task_name"]}}}
{"type": "function", "function": {"name": "find_related_entities", "description": "Find entities that have a specific relationship with a target entity using PubTator3 relations API.", "parameters": {"type": "object", "properties": {"target_entity": {"type": "string", "description": "The target entity to find relations for."}, "relation_type": {"type": "string", "enum": ["ASSOCIATE", "CAUSE", "COMPARE", "COTREAT", "DRUG_INTERACT", "INHIBIT", "INTERACT", "NEGATIVE_CORRELATE", "POSITIVE_CORRELATE", "PREVENT", "STIMULATE", "TREAT", "ANY"], "description": "Type of relation to search for."}, "related_entity_type": {"type": "string", "description": "Type or ID of related entities to find."}, "limit": {"type": "integer", "default": 100}, "max_retries": {"type": "integer", "default": 3}, "max_requests_per_second": {"type": "number", "default": 3.0}}, "required": ["target_entity", "relation_type", "related_entity_type"]}}}
{"type": "function", "function": {"name": "unified_disease_search", "description": "Search for diseases across multiple authoritative databases (BioThings, KEGG, Open Targets) with a single search term.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "A less than three word description of what the search is for."}, "search_term": {"type": "string", "description": "Disease name, condition, or symptoms."}, "limit_per_source": {"type": "integer", "default": 10}, "sources": {"type": "array", "items": {"type": "string"}, "description": "List of sources. Options: 'biothings', 'kegg', 'opentargets'."}}, "required": ["task_name", "search_term"]}}}
{"type": "function", "function": {"name": "fetch_disease_details", "description": "Fetch comprehensive disease details using any identifier (MONDO, DOID, OMIM, MeSH, KEGG, EFO, or name).", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "A less than three word description of what the fetch is for."}, "disease_id": {"type": "string", "description": "Disease identifier or disease name."}, "id_type": {"type": "string", "description": "Type of identifier if known. Auto-detected if not specified."}, "sources": {"type": "array", "items": {"type": "string"}, "description": "List of sources. Options: 'biothings', 'kegg', 'opentargets'."}}, "required": ["task_name", "disease_id"]}}}
{"type": "function", "function": {"name": "unified_drug_search", "description": "Search for drugs across multiple databases (BioThings, OpenFDA, KEGG, Open Targets). Returns FDA status, labels, and trials.", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "A less than three word description of what the search is for."}, "search_term": {"type": "string", "description": "Drug name, compound name, condition, or any search term."}, "limit_per_source": {"type": "integer", "default": 10}, "sources": {"type": "array", "items": {"type": "string"}, "description": "List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'."}}, "required": ["task_name", "search_term"]}}}
{"type": "function", "function": {"name": "fetch_drug_details", "description": "Fetch comprehensive drug details using any identifier (DrugBank, ChEBI, ChEMBL, PubChem, OpenFDA, KEGG, or name).", "parameters": {"type": "object", "properties": {"task_name": {"type": "string", "description": "A less than three word description of what the fetch is for."}, "drug_id": {"type": "string", "description": "Drug identifier of any type or name."}, "id_type": {"type": "string", "description": "Type of identifier if known. Auto-detected if not specified."}, "sources": {"type": "array", "items": {"type": "string"}, "description": "List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'."}}, "required": ["task_name", "drug_id"]}}}
{"type": "function", "function": {"name": "code_execution", "description": "Execute Python code in a secure sandbox environment. Useful for custom calculations, data manipulation, or using specific libraries (e.g., RDKit, SELFIES, pandas) when predefined tools are insufficient.", "parameters": {"type": "object", "properties": {"code": {"type": "string", "description": "The Python code script to execute."}, "language": {"type": "string", "description": "The programming language to use (e.g., 'python').", "default": "python"}}, "required": ["code"]}}}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <args-json-object>}
</tool_call><|im_end|>
<|im_start|>user
Does nocturnal hypoxia-induced oxidative stress promote progression of pediatric non-alcoholic fatty liver disease?

Please research this question using your tools. You MUST conclude your final response with exactly one of the following lines: 'FINAL DECISION: YES', 'FINAL DECISION: NO', or 'FINAL DECISION: MAYBE'.<|im_end|>
<|im_start|>assistant
<think>
Plan: I need to search biomedical literature for the following target: Determine whether nocturnal intermittent hypoxia, especially obstructive sleep apnea, promotes progression or greater severity of pediatric non-alcoholic fatty liver disease (NAFLD/MASLD) through oxidative stress. Find pediatric human studies linking OSA/nocturnal hypoxemia to liver steatosis, NASH, fibrosis, ALT/AST, or oxidative-stress biomarkers; summarize direction, strength, confounding by obesity, and mechanistic evidence. Include key PMID or study identifiers where available, and distinguish pediatric from adult evidence.
</think>

<tool_call>
{"name": "search_papers", "arguments": {"boolean_query_text": "children obstructive sleep apnea oxidative stress fatty liver", "task_name": "pediatric OSA oxidative stress", "top_k": 20, "max_requests_per_second": 3, "max_retries": 3}}
</tool_call><|im_end|>
<|im_start|>user
<tool_response>
### Executed Code:
```python

from biodsa.tools.pubmed.pubtator_api import pubtator_api_search_papers
from biodsa.tools.pubmed.pubmed_api import pubmed_api_search_papers
import pandas as pd

df_list = []
has_relation_query = False

# 1. PubMed Search (Best Relevance Sorting)
if not has_relation_query:
    pmid_df = pubmed_api_search_papers(
        boolean_query_text='children obstructive sleep apnea oxidative stress fatty liver',
        top_k=20,
    )
    if pmid_df is not None and not pmid_df.empty:
        for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:
            if col not in pmid_df.columns:
                pmid_df[col] = ""
        pmid_df = pmid_df[["PMID", "Title", "Journal", "Year", "Abstract"]]
        df_list.append(pmid_df)

# 2. PubTator3 Search (Entity highlighting, fallback)
pubtator_results = []
for page in range(1, 2 + 1):
    search_results = pubtator_api_search_papers(
        boolean_query_text='children obstructive sleep apnea oxidative stress fatty liver',
        relation_query=None,
        page=page,
        max_retries=3,
        max_requests_per_second=3
    )
    if search_results is not None and not search_results.empty:
        pubtator_results.append(search_results)
    else:
        break

if pubtator_results:
    pubtator_df = pd.concat(pubtator_results)
    if "Highlighted_Text" in pubtator_df.columns:
        pubtator_df = pubtator_df.rename(columns={"Highlighted_Text": "Abstract"})

    for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:
        if col not in pubtator_df.columns:
            pubtator_df[col] = ""
    pubtator_df = pubtator_df[["PMID", "Title", "Journal", "Year", "Abstract"]]
    df_list.append(pubtator_df)

# 3. Combine, Deduplicate and Format Clean Output
if df_list:
    final_df = pd.concat(df_list).reset_index(drop=True)
    # Deduplicate by PMID, keeping the first occurrence (which guarantees PubMed relevance is maintained)
    final_df = final_df.drop_duplicates(subset=["PMID"], keep="first")

    # Optional: Save to CSV for persistent logging
    final_df.to_csv('/home/data4/xiangyu/BioDSA/workdir/workdir/pediatric_OSA_oxidative_stress.csv', index=False)
    print(f"The search results are saved at '/home/data4/xiangyu/BioDSA/workdir/workdir/pediatric_OSA_oxidative_stress.csv'")
    print(f"Total results found: {len(final_df)}\n")
    print("=" * 80)
    print("TOP RESULTS (Showing up to 15 most relevant):")
    print("=" * 80)

    # FORMAT FOR LLM: Clean text layout rather than Markdown table
    for idx, row in final_df.head(15).iterrows():
        pmid = row.get('PMID', 'N/A')
        title = row.get('Title', 'No Title')
        journal = row.get('Journal', 'Unknown')
        year = row.get('Year', 'Unknown')
        abstract = str(row.get('Abstract', 'No Abstract Available'))

        # Clean abstract spaces and truncate at 1200 chars to save context window
        abstract = " ".join(abstract.split())
        if len(abstract) > 1200:
            abstract = abstract[:1200] + " ... [Truncated]"

        print(f"PMID: {pmid}")
        print(f"Title: {title}")
        print(f"Source: {journal} ({year})")
        print(f"Abstract: {abstract}")
        print("-" * 80)
else:
    print("No search results found. Please try again with different query. TIP: Try simpler keyword phrases.")

```

### Output:
```
The search results are saved at '/home/data4/xiangyu/BioDSA/workdir/workdir/pediatric_OSA_oxidative_stress.csv'
Total results found: 27

================================================================================
TOP RESULTS (Showing up to 15 most relevant):
================================================================================
PMID: 32523319
Title: Association between non-alcoholic fatty liver disease and obstructive sleep apnea.
Source: World journal of gastroenterology (2020)
Abstract: BACKGROUND: Non-alcoholic fatty liver disease (NAFLD) is an emerging liver disease and currently the most common cause of incidental abnormal liver tests. The pathogenesis of NAFLD is multifactorial and many mechanisms that cause fatty liver infiltration, inflammation, oxidative stress and progressive fibrosis have been proposed. Obstructive sleep apnea (OSA) may be linked with the pathogenesis and the severity of NAFLD. AIM: To study the association between NAFLD and OSA considering also the efficacy of continuous positive airway pressure (CPAP) treatment. METHODS: A PubMed search was conducted using the terms "non-alcoholic fatty liver disease AND (obstructive sleep apnea OR obstructive sleep disorders OR sleep apnea)". Research was limited to title/abstract of articles published in English in the last 5 years; animal and child studies, case reports, commentaries, letters, editorials and meeting abstracts were not considered. Data were extracted on a standardized data collection table which included: First author, publication year, country, study design, number of patients involved, diagnosis and severity of OSA, diagnosis of NAFLD, patient characteristics, results of the study.  ... [Truncated]
--------------------------------------------------------------------------------
PMID: 33718398
Title: Oxidative Stress in Non-alcoholic Fatty Liver Disease. An Updated Mini Review.
Source: Frontiers in medicine (2021)
Abstract: Non-alcoholic fatty liver disease (NAFLD) is a challenging disease caused by multiple factors, which may partly explain why it remains still orphan of an adequate therapeutic strategy. Herein we focus on the interplay between oxidative stress (OS) and the other causal pathogenetic factors. Different reactive oxygen species (ROS) generators contribute to NAFLD inflammatory and fibrotic progression, which is quite strictly linked to the lipotoxic liver injury from fatty acids and/or a wide variety of their biologically active metabolites in the context of either a two-hit or a (more recent) multiple parallel hits theory. An antioxidant defense system is usually able to protect hepatic cells from damaging effects caused by ROS, including those produced into the gastrointestinal tract, i.e., by-products generated by usual cellular metabolic processes, normal or dysbiotic microbiota, and/or diet through an enhanced gut-liver axis. Oxidative stress originating from the imbalance between ROS generation and antioxidant defenses is under the influence of individual genetic and epigenetic factors as well. Healthy diet and physical activity have been shown to be effective on NAFLD also with a ... [Truncated]
--------------------------------------------------------------------------------
PMID: 29752170
Title: Treating Obstructive Sleep Apnea and Chronic Intermittent Hypoxia Improves the Severity of Nonalcoholic Fatty Liver Disease in Children.
Source: The Journal of pediatrics (2018)

In [3]:
import importlib.util
import json
from pathlib import Path

plugin_path = Path(
    "/home/data4/xiangyu/skill-learner/ms-swift/examples/train/rlhf/opsd/opsd_plugin.py"
)
data_path = Path(
    "/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train_processed.jsonl"
)

# 1. 导入插件，确保自定义字段已经注册
spec = importlib.util.spec_from_file_location("opsd_plugin_loader_test", plugin_path)
plugin = importlib.util.module_from_spec(spec)
spec.loader.exec_module(plugin)

# 2. 使用真实 loader 加载本地文件
from swift.dataset.loader import load_dataset

train_ds, val_ds = load_dataset(
    datasets=str(data_path),
    num_proc=1,
    streaming=False,
    load_from_cache_file=False,
    shuffle=False,
    split_dataset_ratio=0.0,
)

assert train_ds is not None and len(train_ds) > 0
print("Rows:", len(train_ds))
print("Columns:", train_ds.column_names)

# 3. 检查字段
row = train_ds[0]

for key in ["teacher_prompt", "teacher_tool_trace", "tools"]:
    assert key in row, f"Missing field: {key}"
    print(f"{key}: {type(row[key]).__name__}")

assert isinstance(row["teacher_prompt"], str) and row["teacher_prompt"]

trace = row["teacher_tool_trace"]
if isinstance(trace, str):
    trace = json.loads(trace)

assert isinstance(trace, list) and trace
print("Trace steps:", len(trace))
print("Trace tools:", [step["name"] for step in trace])

tools = row["tools"]
if isinstance(tools, str):
    tools = json.loads(tools)

assert isinstance(tools, list) and tools
print("Tool definitions:", len(tools))

print("\nREAL LOCAL LOADER TEST PASSED")

Generating train split: 3302 examples [00:01, 2717.36 examples/s]
Map (num_proc=1): 100%|██████████| 3302/3302 [00:02<00:00, 1382.19 examples/s]

Rows: 3302
Columns: ['messages', 'tools', 'teacher_prompt', 'teacher_tool_trace', 'dataset']
teacher_prompt: str
teacher_tool_trace: str
tools: list
Trace steps: 2
Trace tools: ['code_execution', 'code_execution']
Tool definitions: 16

REAL LOCAL LOADER TEST PASSED

In [5]:
import json
from pathlib import Path

raw_path = Path("/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train.jsonl")
processed_path = Path("/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train_processed.jsonl")

def load_jsonl(path):
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]

def parse_messages(row):
    messages = row.get("messages", [])
    if isinstance(messages, str):
        messages = json.loads(messages)
    return messages

def get_user_content(row):
    for msg in parse_messages(row):
        if isinstance(msg, dict) and msg.get("role") == "user":
            return msg.get("content")
    return None

raw = load_jsonl(raw_path)
processed = load_jsonl(processed_path)

processed_questions = {
    get_user_content(row)
    for row in processed
}

for idx, row in enumerate(raw):
    question = get_user_content(row)
    if question is None or question not in processed_questions:
        print(f"原始数据行号：{idx + 1}")
        print("过滤候选记录：")
        print(json.dumps(row, ensure_ascii=False, indent=2))
        break
else:
    print("未找到疑似被过滤的数据。")

原始数据行号：6
过滤候选记录：
{
  "tools": "[{\"type\": \"function\", \"function\": {\"name\": \"fetch_molecule_profile\", \"description\": \"Calculates physicochemical properties, ADMET descriptors, functional groups, NMR peaks, and GHS safety/hazards. Use for virtual screening, oral availability, or evaluating safety risks.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short task description. e.g., 'virtual screening', 'check safety'\"}, \"identifier\": {\"type\": \"string\", \"description\": \"Molecule identifier (SMILES, SELFIES, or common name).\"}}, \"required\": [\"task_name\", \"identifier\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_bioactivity_and_targets\", \"description\": \"Queries ChEMBL to find a molecule's biological targets, mechanism of action, and clinical trial phase. Use for 'targets', 'receptors', or 'drug approval status'.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short description. e.g., 'find targets', 'clinical phase'\"}, \"identifier\": {\"type\": \"string\", \"description\": \"Molecule identifier (SMILES, SELFIES, or common name).\"}}, \"required\": [\"task_name\", \"identifier\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"compute_quantum_mechanics\", \"description\": \"Calculates quantum chemical properties like LUMO/HOMO energy and Dipole Moment.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short description, e.g., 'lumo calculation'\"}, \"smiles\": {\"type\": \"string\", \"description\": \"The exact SMILES/SELFIES string or name of the molecule.\"}}, \"required\": [\"task_name\", \"smiles\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_reaction_details\", \"description\": \"Fetches empirical chemical reaction data (conditions, yield, reagents, catalysts) from ORD database. Supports forward prediction and retrosynthesis search.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short descriptive name, e.g., 'predict yield', 'find solvents'\"}, \"reaction_smiles\": {\"type\": \"string\", \"description\": \"Chemical query (SMILES, SELFIES, InChIKey, or IUPAC name). Modes: 1) Full exact match: 'Reactants>>Products'; 2) Forward prediction: 'Reactants>>' or 'Reactants'; 3) Retrosynthesis/Conditions: '>>Product' or 'Product'.\"}, \"limit\": {\"type\": \"integer\", \"description\": \"Maximum number of reaction records to return.\", \"default\": 5}}, \"required\": [\"task_name\", \"reaction_smiles\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"query_protein\", \"description\": \"Analyzes a protein from sequence or UniProt accession. Retrieves sequence properties, homologs, annotations, catalytic info, pathways, and GO terms.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short description used for output filename, e.g., 'analyze protein'\"}, \"sequence\": {\"type\": \"string\", \"description\": \"Protein amino-acid sequence or FASTA. Provide exactly one of sequence or accession.\"}, \"accession\": {\"type\": \"string\", \"description\": \"UniProt primary accession. Provide exactly one of sequence or accession.\"}, \"query\": {\"type\": \"string\", \"description\": \"Free-form protein question, e.g., 'identify its function'.\"}}, \"required\": [\"task_name\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"get_paper_references\", \"description\": \"Get paper references (citations) for a list of PubMed IDs.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"pmids\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of PubMed IDs (PMIDs) to get references for.\"}, \"batch_size\": {\"type\": \"integer\", \"default\": 100}, \"mini_batch_size\": {\"type\": \"integer\", \"default\": 20}, \"max_workers\": {\"type\": \"integer\", \"default\": 4}, \"rate_limit\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"task_name\", \"pmids\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_paper_content\", \"description\": \"Fetch and extract specific content from a PubMed paper by PMID using keyword/regex filtering.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"pmid\": {\"type\": \"string\", \"description\": \"A single PubMed ID (PMID) to fetch content for.\"}, \"filter_keywords\": {\"type\": \"string\", \"description\": \"Keywords or regex pattern to search for and extract from the paper content.\"}}, \"required\": [\"pmid\", \"filter_keywords\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_paper_annotations\", \"description\": \"Fetch biomedical entity annotations from PubTator3 for a list of PubMed IDs.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"pmids\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of PubMed IDs (PMIDs) to fetch annotations for.\"}, \"batch_size\": {\"type\": \"integer\", \"default\": 50}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"pmids\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"find_entities\", \"description\": \"Find and autocomplete biomedical entity names in the PubTator3 database.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"query_text\": {\"type\": \"string\", \"description\": \"A single search term (partial entity name) to find entities.\"}, \"concept_type\": {\"type\": \"string\", \"enum\": [\"GENE\", \"DISEASE\", \"CHEMICAL\", \"VARIANT\", \"SPECIES\", \"CELLLINE\"], \"description\": \"Optional entity concept type.\"}, \"limit\": {\"type\": \"integer\", \"default\": 10}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"query_text\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"search_papers\", \"description\": \"Search PubMed articles using keywords, boolean queries, or relation queries. TIP: Simple keywords often yield better results.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"boolean_query_text\": {\"type\": \"string\", \"description\": \"Boolean query or simple natural language text.\"}, \"relation_query\": {\"type\": \"object\", \"description\": \"Relation-based query configuration.\"}, \"top_k\": {\"type\": \"integer\", \"default\": 100, \"description\": \"Number of top results to return.\"}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"task_name\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"find_related_entities\", \"description\": \"Find entities that have a specific relationship with a target entity using PubTator3 relations API.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"target_entity\": {\"type\": \"string\", \"description\": \"The target entity to find relations for.\"}, \"relation_type\": {\"type\": \"string\", \"enum\": [\"ASSOCIATE\", \"CAUSE\", \"COMPARE\", \"COTREAT\", \"DRUG_INTERACT\", \"INHIBIT\", \"INTERACT\", \"NEGATIVE_CORRELATE\", \"POSITIVE_CORRELATE\", \"PREVENT\", \"STIMULATE\", \"TREAT\", \"ANY\"], \"description\": \"Type of relation to search for.\"}, \"related_entity_type\": {\"type\": \"string\", \"description\": \"Type or ID of related entities to find.\"}, \"limit\": {\"type\": \"integer\", \"default\": 100}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"target_entity\", \"relation_type\", \"related_entity_type\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"unified_disease_search\", \"description\": \"Search for diseases across multiple authoritative databases (BioThings, KEGG, Open Targets) with a single search term.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"search_term\": {\"type\": \"string\", \"description\": \"Disease name, condition, or symptoms.\"}, \"limit_per_source\": {\"type\": \"integer\", \"default\": 10}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"search_term\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_disease_details\", \"description\": \"Fetch comprehensive disease details using any identifier (MONDO, DOID, OMIM, MeSH, KEGG, EFO, or name).\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the fetch is for.\"}, \"disease_id\": {\"type\": \"string\", \"description\": \"Disease identifier or disease name.\"}, \"id_type\": {\"type\": \"string\", \"description\": \"Type of identifier if known. Auto-detected if not specified.\"}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"disease_id\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"unified_drug_search\", \"description\": \"Search for drugs across multiple databases (BioThings, OpenFDA, KEGG, Open Targets). Returns FDA status, labels, and trials.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"search_term\": {\"type\": \"string\", \"description\": \"Drug name, compound name, condition, or any search term.\"}, \"limit_per_source\": {\"type\": \"integer\", \"default\": 10}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"search_term\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_drug_details\", \"description\": \"Fetch comprehensive drug details using any identifier (DrugBank, ChEBI, ChEMBL, PubChem, OpenFDA, KEGG, or name).\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the fetch is for.\"}, \"drug_id\": {\"type\": \"string\", \"description\": \"Drug identifier of any type or name.\"}, \"id_type\": {\"type\": \"string\", \"description\": \"Type of identifier if known. Auto-detected if not specified.\"}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"drug_id\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"code_execution\", \"description\": \"Execute Python code in a secure sandbox environment. Useful for custom calculations, data manipulation, or using specific libraries (e.g., RDKit, SELFIES, pandas) when predefined tools are insufficient.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"code\": {\"type\": \"string\", \"description\": \"The Python code script to execute.\"}, \"language\": {\"type\": \"string\", \"description\": \"The programming language to use (e.g., 'python').\", \"default\": \"python\"}}, \"required\": [\"code\"]}}}]",
  "messages": [
    {
      "role": "user",
      "content": "Do aRDS Subphenotypes Respond Differently to Randomized Fluid Management Strategy?\n\nPlease research this question using your tools. You MUST conclude your final response with exactly one of the following lines: 'FINAL DECISION: YES', 'FINAL DECISION: NO', or 'FINAL DECISION: MAYBE'."
    },
    {
      "role": "assistant",
      "content": "1. [✓] Search randomized fluid-management studies and ARDS subphenotype treatment-interaction analyses.\n2. [✓] Check the available study description, phenotype scheme, outcome, and interaction result.\n3. [✓] Record and review the finding in the knowledge graph.\n4. [✓] Synthesize the evidence and its limitations.\n\n**Yes—there is evidence of differential response, but it is preliminary and phenotype-specific.** A retrospective analysis of randomized-trial data reported an interaction between **three clinical ARDS phenotypes** and fluid-management assignment for **60-day mortality** (*P* = 0.01). The reported direction differed by phenotype: conservative fluid management was associated with improved mortality in phenotype II, while the direction was opposite in phenotype III (PMID: 34461969).\n\nThis does **not** establish that the conventional **hypo- versus hyperinflammatory latent subphenotypes** respond differently: the reported analysis used three clinical phenotypes. The finding is also a secondary analysis, and the evidence retrieved here did not include subgroup effect estimates or detailed replication data. Thus, it supports a possible phenotype-dependent treatment effect, not a settled basis for choosing fluid strategy by subphenotype.\n\nFINAL DECISION: YES"
    }
  ]
}

In [ ]:
import importlib.util
import json
from pathlib import Path

plugin_path = Path(
    "/home/data4/xiangyu/skill-learner/ms-swift/examples/train/rlhf/opsd/opsd_plugin.py"
)
source_path = Path(
    "/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train.jsonl"
)
output_path = Path(
    "/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train_processed.jsonl"
)

spec = importlib.util.spec_from_file_location("opsd_plugin_export", plugin_path)
plugin = importlib.util.module_from_spec(spec)
spec.loader.exec_module(plugin)

preprocessor = plugin.BioDSAOPSDPreprocessor()

total = 0
kept = 0

with source_path.open("r", encoding="utf-8") as src, \
     output_path.open("w", encoding="utf-8") as dst:

    for line in src:
        if not line.strip():
            continue

        total += 1
        raw = json.loads(line)
        result = preprocessor.preprocess(raw)

        if result is None:
            continue

        # Keep each record's schema stable and serialize the nested
        # fields as JSON strings where required.
        result["messages"] = json.dumps(
            result["messages"], ensure_ascii=False
        )
        result["tools"] = (
            result["tools"]
            if isinstance(result["tools"], str)
            else json.dumps(result["tools"], ensure_ascii=False)
        )
        result["teacher_prompt"] = str(result["teacher_prompt"])
        result["teacher_tool_trace"] = (
            result["teacher_tool_trace"]
            if isinstance(result["teacher_tool_trace"], str)
            else json.dumps(
                result["teacher_tool_trace"], ensure_ascii=False
            )
        )

        dst.write(json.dumps(result, ensure_ascii=False) + "\n")
        kept += 1

print("Input rows:", total)
print("Processed rows:", kept)
print("Output:", output_path)
print("Output bytes:", output_path.stat().st_size)

# Validate the exported first row.
with output_path.open("r", encoding="utf-8") as f:
    first = json.loads(next(line for line in f if line.strip()))

print("Output keys:", list(first.keys()))
print("Messages:", len(json.loads(first["messages"])))
print("Tools:", len(json.loads(first["tools"])))
print("Trace steps:", len(json.loads(first["teacher_tool_trace"])))

assert kept > 0
assert all(
    k in first
    for k in (
        "messages",
        "tools",
        "teacher_prompt",
        "teacher_tool_trace",
    )
)
print("PREPROCESS EXPORT PASSED")

Input rows: 3433
Processed rows: 3302
Output: /home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train_processed.jsonl
Output bytes: 124871728
Output keys: ['messages', 'tools', 'teacher_prompt', 'teacher_tool_trace']
Messages: 1
Tools: 16
Trace steps: 2
PREPROCESS EXPORT PASSED

In [10]:
import importlib.util
import json
from pathlib import Path

plugin_path = Path(
    "/home/data4/xiangyu/skill-learner/ms-swift/examples/train/rlhf/opsd/opsd_plugin.py"
)
source_path = Path(
    "/home/data4/xiangyu/skill-learner/sci_tool_agent_opsd_train.jsonl"
)

spec = importlib.util.spec_from_file_location("opsd_plugin_debug", plugin_path)
plugin = importlib.util.module_from_spec(spec)
spec.loader.exec_module(plugin)

preprocessor = plugin.BioDSAOPSDPreprocessor()

with source_path.open("r", encoding="utf-8") as f:
    rows = [json.loads(line) for line in f if line.strip()]

# 第六条数据（Python 下标为 5）
raw = rows[5]

print("=" * 80)
print("第 6 条原始数据")
print("=" * 80)
print(json.dumps(raw, ensure_ascii=False, indent=2))

print("\n" + "=" * 80)
print("预处理结果")
print("=" * 80)

result = preprocessor.preprocess(raw)

if result is None:
    print("结果为 None：该记录被预处理器过滤。")
else:
    print("结果不为 None：该记录本身可以通过预处理。")
    print("输出字段：", list(result.keys()))
    print("学生消息：")
    print(json.dumps(result.get("messages"), ensure_ascii=False, indent=2))
    print("工具轨迹：")
    print(json.dumps(result.get("teacher_tool_trace"), ensure_ascii=False, indent=2))

================================================================================
第 6 条原始数据
================================================================================
{
  "tools": "[{\"type\": \"function\", \"function\": {\"name\": \"fetch_molecule_profile\", \"description\": \"Calculates physicochemical properties, ADMET descriptors, functional groups, NMR peaks, and GHS safety/hazards. Use for virtual screening, oral availability, or evaluating safety risks.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short task description. e.g., 'virtual screening', 'check safety'\"}, \"identifier\": {\"type\": \"string\", \"description\": \"Molecule identifier (SMILES, SELFIES, or common name).\"}}, \"required\": [\"task_name\", \"identifier\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_bioactivity_and_targets\", \"description\": \"Queries ChEMBL to find a molecule's biological targets, mechanism of action, and clinical trial phase. Use for 'targets', 'receptors', or 'drug approval status'.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short description. e.g., 'find targets', 'clinical phase'\"}, \"identifier\": {\"type\": \"string\", \"description\": \"Molecule identifier (SMILES, SELFIES, or common name).\"}}, \"required\": [\"task_name\", \"identifier\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"compute_quantum_mechanics\", \"description\": \"Calculates quantum chemical properties like LUMO/HOMO energy and Dipole Moment.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short description, e.g., 'lumo calculation'\"}, \"smiles\": {\"type\": \"string\", \"description\": \"The exact SMILES/SELFIES string or name of the molecule.\"}}, \"required\": [\"task_name\", \"smiles\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_reaction_details\", \"description\": \"Fetches empirical chemical reaction data (conditions, yield, reagents, catalysts) from ORD database. Supports forward prediction and retrosynthesis search.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short descriptive name, e.g., 'predict yield', 'find solvents'\"}, \"reaction_smiles\": {\"type\": \"string\", \"description\": \"Chemical query (SMILES, SELFIES, InChIKey, or IUPAC name). Modes: 1) Full exact match: 'Reactants>>Products'; 2) Forward prediction: 'Reactants>>' or 'Reactants'; 3) Retrosynthesis/Conditions: '>>Product' or 'Product'.\"}, \"limit\": {\"type\": \"integer\", \"description\": \"Maximum number of reaction records to return.\", \"default\": 5}}, \"required\": [\"task_name\", \"reaction_smiles\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"query_protein\", \"description\": \"Analyzes a protein from sequence or UniProt accession. Retrieves sequence properties, homologs, annotations, catalytic info, pathways, and GO terms.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"Short description used for output filename, e.g., 'analyze protein'\"}, \"sequence\": {\"type\": \"string\", \"description\": \"Protein amino-acid sequence or FASTA. Provide exactly one of sequence or accession.\"}, \"accession\": {\"type\": \"string\", \"description\": \"UniProt primary accession. Provide exactly one of sequence or accession.\"}, \"query\": {\"type\": \"string\", \"description\": \"Free-form protein question, e.g., 'identify its function'.\"}}, \"required\": [\"task_name\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"get_paper_references\", \"description\": \"Get paper references (citations) for a list of PubMed IDs.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"pmids\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of PubMed IDs (PMIDs) to get references for.\"}, \"batch_size\": {\"type\": \"integer\", \"default\": 100}, \"mini_batch_size\": {\"type\": \"integer\", \"default\": 20}, \"max_workers\": {\"type\": \"integer\", \"default\": 4}, \"rate_limit\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"task_name\", \"pmids\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_paper_content\", \"description\": \"Fetch and extract specific content from a PubMed paper by PMID using keyword/regex filtering.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"pmid\": {\"type\": \"string\", \"description\": \"A single PubMed ID (PMID) to fetch content for.\"}, \"filter_keywords\": {\"type\": \"string\", \"description\": \"Keywords or regex pattern to search for and extract from the paper content.\"}}, \"required\": [\"pmid\", \"filter_keywords\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_paper_annotations\", \"description\": \"Fetch biomedical entity annotations from PubTator3 for a list of PubMed IDs.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"pmids\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of PubMed IDs (PMIDs) to fetch annotations for.\"}, \"batch_size\": {\"type\": \"integer\", \"default\": 50}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"pmids\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"find_entities\", \"description\": \"Find and autocomplete biomedical entity names in the PubTator3 database.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"query_text\": {\"type\": \"string\", \"description\": \"A single search term (partial entity name) to find entities.\"}, \"concept_type\": {\"type\": \"string\", \"enum\": [\"GENE\", \"DISEASE\", \"CHEMICAL\", \"VARIANT\", \"SPECIES\", \"CELLLINE\"], \"description\": \"Optional entity concept type.\"}, \"limit\": {\"type\": \"integer\", \"default\": 10}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"query_text\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"search_papers\", \"description\": \"Search PubMed articles using keywords, boolean queries, or relation queries. TIP: Simple keywords often yield better results.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"boolean_query_text\": {\"type\": \"string\", \"description\": \"Boolean query or simple natural language text.\"}, \"relation_query\": {\"type\": \"object\", \"description\": \"Relation-based query configuration.\"}, \"top_k\": {\"type\": \"integer\", \"default\": 100, \"description\": \"Number of top results to return.\"}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"task_name\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"find_related_entities\", \"description\": \"Find entities that have a specific relationship with a target entity using PubTator3 relations API.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"target_entity\": {\"type\": \"string\", \"description\": \"The target entity to find relations for.\"}, \"relation_type\": {\"type\": \"string\", \"enum\": [\"ASSOCIATE\", \"CAUSE\", \"COMPARE\", \"COTREAT\", \"DRUG_INTERACT\", \"INHIBIT\", \"INTERACT\", \"NEGATIVE_CORRELATE\", \"POSITIVE_CORRELATE\", \"PREVENT\", \"STIMULATE\", \"TREAT\", \"ANY\"], \"description\": \"Type of relation to search for.\"}, \"related_entity_type\": {\"type\": \"string\", \"description\": \"Type or ID of related entities to find.\"}, \"limit\": {\"type\": \"integer\", \"default\": 100}, \"max_retries\": {\"type\": \"integer\", \"default\": 3}, \"max_requests_per_second\": {\"type\": \"number\", \"default\": 3.0}}, \"required\": [\"target_entity\", \"relation_type\", \"related_entity_type\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"unified_disease_search\", \"description\": \"Search for diseases across multiple authoritative databases (BioThings, KEGG, Open Targets) with a single search term.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"search_term\": {\"type\": \"string\", \"description\": \"Disease name, condition, or symptoms.\"}, \"limit_per_source\": {\"type\": \"integer\", \"default\": 10}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"search_term\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_disease_details\", \"description\": \"Fetch comprehensive disease details using any identifier (MONDO, DOID, OMIM, MeSH, KEGG, EFO, or name).\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the fetch is for.\"}, \"disease_id\": {\"type\": \"string\", \"description\": \"Disease identifier or disease name.\"}, \"id_type\": {\"type\": \"string\", \"description\": \"Type of identifier if known. Auto-detected if not specified.\"}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"disease_id\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"unified_drug_search\", \"description\": \"Search for drugs across multiple databases (BioThings, OpenFDA, KEGG, Open Targets). Returns FDA status, labels, and trials.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the search is for.\"}, \"search_term\": {\"type\": \"string\", \"description\": \"Drug name, compound name, condition, or any search term.\"}, \"limit_per_source\": {\"type\": \"integer\", \"default\": 10}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"search_term\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"fetch_drug_details\", \"description\": \"Fetch comprehensive drug details using any identifier (DrugBank, ChEBI, ChEMBL, PubChem, OpenFDA, KEGG, or name).\", \"parameters\": {\"type\": \"object\", \"properties\": {\"task_name\": {\"type\": \"string\", \"description\": \"A less than three word description of what the fetch is for.\"}, \"drug_id\": {\"type\": \"string\", \"description\": \"Drug identifier of any type or name.\"}, \"id_type\": {\"type\": \"string\", \"description\": \"Type of identifier if known. Auto-detected if not specified.\"}, \"sources\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'.\"}}, \"required\": [\"task_name\", \"drug_id\"]}}}, {\"type\": \"function\", \"function\": {\"name\": \"code_execution\", \"description\": \"Execute Python code in a secure sandbox environment. Useful for custom calculations, data manipulation, or using specific libraries (e.g., RDKit, SELFIES, pandas) when predefined tools are insufficient.\", \"parameters\": {\"type\": \"object\", \"properties\": {\"code\": {\"type\": \"string\", \"description\": \"The Python code script to execute.\"}, \"language\": {\"type\": \"string\", \"description\": \"The programming language to use (e.g., 'python').\", \"default\": \"python\"}}, \"required\": [\"code\"]}}}]",
  "messages": [
    {
      "role": "user",
      "content": "Do aRDS Subphenotypes Respond Differently to Randomized Fluid Management Strategy?\n\nPlease research this question using your tools. You MUST conclude your final response with exactly one of the following lines: 'FINAL DECISION: YES', 'FINAL DECISION: NO', or 'FINAL DECISION: MAYBE'."
    },
    {
      "role": "assistant",
      "content": "1. [✓] Search randomized fluid-management studies and ARDS subphenotype treatment-interaction analyses.\n2. [✓] Check the available study description, phenotype scheme, outcome, and interaction result.\n3. [✓] Record and review the finding in the knowledge graph.\n4. [✓] Synthesize the evidence and its limitations.\n\n**Yes—there is evidence of differential response, but it is preliminary and phenotype-specific.** A retrospective analysis of randomized-trial data reported an interaction between **three clinical ARDS phenotypes** and fluid-management assignment for **60-day mortality** (*P* = 0.01). The reported direction differed by phenotype: conservative fluid management was associated with improved mortality in phenotype II, while the direction was opposite in phenotype III (PMID: 34461969).\n\nThis does **not** establish that the conventional **hypo- versus hyperinflammatory latent subphenotypes** respond differently: the reported analysis used three clinical phenotypes. The finding is also a secondary analysis, and the evidence retrieved here did not include subgroup effect estimates or detailed replication data. Thus, it supports a possible phenotype-dependent treatment effect, not a settled basis for choosing fluid strategy by subphenotype.\n\nFINAL DECISION: YES"
    }
  ]
}

================================================================================
预处理结果
================================================================================
结果为 None：该记录被预处理器过滤。

In [4]:
# Copyright (c) ModelScope Contributors. All rights reserved.
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
# os.environ['SWIFT_DEBUG'] = '1'


def infer(engine: 'InferEngine', infer_request: 'InferRequest'):
    stop = [engine.template.agent_template.keyword.observation]  # compat react_en
    request_config = RequestConfig(max_tokens=512, temperature=0, stop=stop)
    resp_list = engine.infer([infer_request], request_config)
    query = infer_request.messages[0]['content']
    response = resp_list[0].choices[0].message.content
    print(f'query: {query}')
    print(f'response: {response}')
    print(f'tool_calls: {resp_list[0].choices[0].message.tool_calls}')

    tool =  "### Executed Code:\n```python\n\nfrom biodsa.tools.pubmed.pubtator_api import pubtator_api_search_papers\nfrom biodsa.tools.pubmed.pubmed_api import pubmed_api_search_papers\nimport pandas as pd\n\ndf_list = []\nhas_relation_query = False\n\n# 1. PubMed Search (Best Relevance Sorting)\nif not has_relation_query:\n    pmid_df = pubmed_api_search_papers(\n        boolean_query_text='craniosynostosis diagnosis referral imaging sagittal synostosis infant clinical guideline',\n        top_k=10,\n    )\n    if pmid_df is not None and not pmid_df.empty:\n        for col in [\"PMID\", \"Title\", \"Journal\", \"Year\", \"Abstract\"]:\n            if col not in pmid_df.columns:\n                pmid_df[col] = \"\"\n        pmid_df = pmid_df[[\"PMID\", \"Title\", \"Journal\", \"Year\", \"Abstract\"]]\n        df_list.append(pmid_df)\n\n# 2. PubTator3 Search (Entity highlighting, fallback)\npubtator_results = []\nfor page in range(1, 1 + 1):\n    search_results = pubtator_api_search_papers(\n        boolean_query_text='craniosynostosis diagnosis referral imaging sagittal synostosis infant clinical guideline',\n        relation_query=None,\n        page=page,\n        max_retries=3,\n        max_requests_per_second=3\n    )\n    if search_results is not None and not search_results.empty:\n        pubtator_results.append(search_results)\n    else:\n        break\n\nif pubtator_results:\n    pubtator_df = pd.concat(pubtator_results)\n    if \"Highlighted_Text\" in pubtator_df.columns:\n        pubtator_df = pubtator_df.rename(columns={\"Highlighted_Text\": \"Abstract\"})\n    \n    for col in [\"PMID\", \"Title\", \"Journal\", \"Year\", \"Abstract\"]:\n        if col not in pubtator_df.columns:\n            pubtator_df[col] = \"\"\n    pubtator_df = pubtator_df[[\"PMID\", \"Title\", \"Journal\", \"Year\", \"Abstract\"]]\n    df_list.append(pubtator_df)\n\n# 3. Combine, Deduplicate and Format Clean Output\nif df_list:\n    final_df = pd.concat(df_list).reset_index(drop=True)\n    # Deduplicate by PMID, keeping the first occurrence (which guarantees PubMed relevance is maintained)\n    final_df = final_df.drop_duplicates(subset=[\"PMID\"], keep=\"first\")\n    \n    # Optional: Save to CSV for persistent logging\n    final_df.to_csv('/home/data4/xiangyu/BioDSA/workdir/craniosynostosis_guidance.csv', index=False)\n    print(f\"The search results are saved at '/home/data4/xiangyu/BioDSA/workdir/craniosynostosis_guidance.csv'\")\n    print(f\"Total results found: {len(final_df)}\\n\")\n    print(\"=\" * 80)\n    print(\"TOP RESULTS (Showing up to 15 most relevant):\")\n    print(\"=\" * 80)\n    \n    # FORMAT FOR LLM: Clean text layout rather than Markdown table\n    for idx, row in final_df.head(15).iterrows():\n        pmid = row.get('PMID', 'N/A')\n        title = row.get('Title', 'No Title')\n        journal = row.get('Journal', 'Unknown')\n        year = row.get('Year', 'Unknown')\n        abstract = str(row.get('Abstract', 'No Abstract Available'))\n        \n        # Clean abstract spaces and truncate at 1200 chars to save context window\n        abstract = \" \".join(abstract.split())\n        if len(abstract) > 1200:\n            abstract = abstract[:1200] + \" ... [Truncated]\"\n            \n        print(f\"PMID: {pmid}\")\n        print(f\"Title: {title}\")\n        print(f\"Source: {journal} ({year})\")\n        print(f\"Abstract: {abstract}\")\n        print(\"-\" * 80)\nelse:\n    print(\"No search results found. Please try again with different query. TIP: Try simpler keyword phrases.\")\n\n```\n\n### Output:\n```\nThe search results are saved at '/home/data4/xiangyu/BioDSA/workdir/craniosynostosis_guidance.csv'\nTotal results found: 10\n\n================================================================================\nTOP RESULTS (Showing up to 15 most relevant):\n================================================================================\nPMID: 40820202\nTitle: Developments in diagnostic and surgical techniques in children with sagittal suture craniosynostosis: a systematic review spanning the last 30 years\nSource: Orphanet J Rare Dis (2025)\nAbstract: In 2021 Ravindra et al. investigates the necessity of preoperative CT <m>imaging</m> in <m>infants</m> with yet <m>clinically</m> <m>diagnosed</m> single suture @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@, including @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>sagittal</m> <m>craniosynostosis</m>@@@.\n--------------------------------------------------------------------------------\nPMID: 33156164\nTitle: Updated Guideline on Treatment and Management of Craniosynostosis\nSource: J Craniofac Surg (2021)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 37206061\nTitle: Minimally invasive craniectomy and postoperative cranial remolding orthotic treatment in infants with craniosynostosis: A multicenter prospective study\nSource: World Neurosurg X (2023)\nAbstract: In this study, for <m>imaging</m> of the @SPECIES_9606 @@@patients@@@' skull, we followed the \"<m>Guideline</m> for Care of @SPECIES_9606 @@@Patients@@@ with the <m>Diagnoses</m> of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>Craniosynostosis</m>@@@\".\n--------------------------------------------------------------------------------\nPMID: 35110924\nTitle: Intraoperative Measurement of Intracranial Pressure During Cranial Vault Remodeling in Children with Craniosynostosis\nSource: J Neurosci Rural Pract (2022)\nAbstract: Half of the children in our series were older than 1 year of age. It is due to the <m>referral</m> pattern. In our country, the awareness about @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@ is still low.\n--------------------------------------------------------------------------------\nPMID: 33575503\nTitle: Evaluation of the Molding Helmet Therapy for Japanese Infants with Deformational Plagiocephaly\nSource: JMA J (2021)\nAbstract: Ten @SPECIES_9606 @@@patients@@@ were strongly suspected of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@ after X-ray and/or CT (four @SPECIES_9606 @@@patients@@@ were definitively <m>diagnosed</m> as @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@, one @SPECIES_9606 @@@patient@@@ was sent back for further evaluation to the <m>referring</m> hospital, another @SPECIES_9606 @@@patient@@@ was lost to follow-up before further evaluation, and four @SPECIES_9606 @@@patients@@@ were ruled out of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@ but declined helmet therapy).\n--------------------------------------------------------------------------------\nPMID: 36484829\nTitle: 48th Annual Meeting of the International Society for Pediatric Neurosurgery\nSource: Childs Nerv Syst (2022)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 34716771\nTitle: ISPN 2021 Virtual Meeting of the International Society for Pediatric Neurosurgery\nSource: Childs Nerv Syst (2021)\nAbstract: None\n--------------------------------------------------------------------------------\nPMID: 39960858\nTitle: X-Linked Hypophosphatemia Management in Children: An International Working Group Clinical Practice Guideline\nSource: J Clin Endocrinol Metab (2025)\nAbstract: @DISEASE_Familial_Hypophosphatemic_Rickets @DISEASE_MESH:D053098 @@@X-Linked Hypophosphatemia@@@ Management in Children: An International Working Group <m>Clinical</m> Practice <m>Guideline</m>\n--------------------------------------------------------------------------------\nPMID: 27256993\nTitle: Diagnosis of infant synostotic and nonsynostotic cranial deformities: a review for pediatricians\nSource: Rev Paul Pediatr (2016)\nAbstract: We included the anatomy and physiology of normal skull development of children, discussing nuances related to nomenclature, epidemiology, etiology, and treatment of the most common forms of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@nonsyndromic <m>craniosynostosis</m>@@@. The <m>clinical</m> criteria for the differential <m>diagnosis</m> between @DISEASE_Musculoskeletal_Diseases @DISEASE_MESH:D009140 @@@positional deformities@@@ and @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@nonsyndromic <m>craniosynostosis</m>@@@ were also discussed, giving to the pediatrician subsidies for a quick and safe <m>clinical</m> <m>diagnosis</m>.\n--------------------------------------------------------------------------------\nPMID: 26355968\nTitle: Guideline for Care of Patients With the Diagnoses of Craniosynostosis: Working Group on Craniosynostosis\nSource: J Craniofac Surg (2015)\nAbstract: <m>Guideline</m> for Care of @SPECIES_9606 @@@Patients@@@ With the <m>Diagnoses</m> of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>Craniosynostosis</m>@@@: Working Group on @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>Craniosynostosis</m>@@@\n--------------------------------------------------------------------------------\n\n```\n\n"
    print(f'tool_response: {tool}')
    infer_request.messages += [{'role': 'assistant', 'content': response}, {'role': 'tool', 'content': tool}]
    resp_list = engine.infer([infer_request], request_config)
    response2 = resp_list[0].choices[0].message.content
    print(f'response2: {response2}')

    tool2= "Key Findings Summary:\n- The described elongated, narrow skull with prominent occiput and broad forehead is more concerning for sagittal craniosynostosis (scaphocephaly) than for typical positional plagiocephaly, although diagnosis is clinical and requires examination for a sagittal ridge, restricted biparietal width, fontanelle/suture findings, and 3-D head shape. A pediatric craniofacial/neurosurgical referral is appropriate if this shape is persistent or suspicious; imaging should generally be obtained only when the clinical examination is equivocal or requested by the specialist, rather than as routine screening CT.\n- Positional plagiocephaly/brachycephaly is managed initially with conservative measures: supervised prone tummy time while awake, alternating head position, reducing prolonged pressure on the occiput, and addressing torticollis if present. It usually has positional occipital flattening rather than a uniformly long narrow skull and does not require imaging when the examination is typical; referral is considered for atypical, progressive, severe, or treatment-resistant deformity.\n- A head circumference rising from the 50th to 90th percentile is not by itself diagnostic of hydrocephalus or pathologic macrocephaly. Repeat accurate serial measurements, review the growth curve, and measure both parents' head circumferences; normal development/examination and familial macrocephaly support observation. The macrocephaly literature notes that many mildly macrocephalic children have normal development and familial recurrence.\n- Hydrocephalus becomes more likely with rapidly accelerating head growth plus signs of raised intracranial pressure or neurologic compromise—progressive vomiting, irritability/lethargy, poor feeding, bulging fontanelle, separated sutures, abnormal eye movements/sunset gaze, seizures, or developmental/regression findings. In their absence, urgent neuroimaging is not indicated solely for a percentile change, but any red flags warrant prompt assessment and imaging/referral."
    infer_request.messages += [{'role': 'assistant', 'content': response}, {'role': 'tool', 'content': tool2}]
    resp_list = engine.infer([infer_request], request_config)
    response3 = resp_list[0].choices[0].message.content
    print(f'response2: {response3}')
    
def infer_stream(engine: 'InferEngine', infer_request: 'InferRequest'):
    stop = [engine.template.agent_template.keyword.observation]
    request_config = RequestConfig(max_tokens=512, temperature=0, stream=True, stop=stop)
    gen_list = engine.infer([infer_request], request_config)
    query = infer_request.messages[0]['content']
    response = ''
    print(f'query: {query}\nresponse: ', end='')
    for resp in gen_list[0]:
        if resp is None:
            continue
        delta = resp.choices[0].delta.content
        response += delta
        print(delta, end='', flush=True)
    print()
    print(f'tool_calls: {resp.choices[0].delta.tool_calls}')

    tool = '{"temperature": 32, "condition": "Sunny", "humidity": 50}'
    print(f'tool_response: {tool}\nresponse2: ', end='')
    infer_request.messages += [{'role': 'assistant', 'content': response}, {'role': 'tool', 'content': tool}]
    gen_list = engine.infer([infer_request], request_config)
    for resp in gen_list[0]:
        if resp is None:
            continue
        print(resp.choices[0].delta.content, end='', flush=True)
    print()


def get_infer_request():
    return InferRequest(
        messages=[{
            'role': 'user',
            'content': "A 2-month-old male infant is brought in for a routine health maintenance visit. His growth and development are on track, with height and weight at the 50th percentile, consistent with prior growth measurements. However, his head circumference has increased to the 90th percentile from the 50th percentile noted at his newborn visit. The head appears elongated and narrow, with a prominent occiput and broad forehead. There are no facial dysmorphic features, and the rest of the physical exam is unremarkable. What is the most appropriate initial management for this infant?\nAnswer Choices: (A) Increased time in the prone position while awake and monitored (B) Measurement of parental head circumferences to assess for familial macrocephaly (C) Referral to a physical therapist to address positional head shape deformities (D) Cranial ultrasound to assess for hydrocephalus (E) MRI of the brain to evaluate intracranial structures (F) Observation with no further intervention unless symptoms worsen (G) Reevaluation of head circumference in one month (H) Referral to a pediatric endocrinologist for evaluation of growth abnormalities (I) Referral to craniofacial specialists (J) Referral for genetic testing\n\nPlease research this clinical scenario using your tools. You MUST conclude your final response with the exact string 'FINAL ANSWER: [Letter]', for example: FINAL ANSWER: A."
        }],
        tools = [
    {
        'name': 'fetch_molecule_profile',
        'description': 'Calculates physicochemical properties, ADMET descriptors, functional groups, NMR peaks, and GHS safety/hazards. Use for virtual screening, oral availability, or evaluating safety risks.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': "Short task description. e.g., 'virtual screening', 'check safety'"
                },
                'identifier': {
                    'type': 'string',
                    'description': 'Molecule identifier (SMILES, SELFIES, or common name).'
                }
            },
            'required': ['task_name', 'identifier']
        }
    },
    {
        'name': 'fetch_bioactivity_and_targets',
        'description': "Queries ChEMBL to find a molecule's biological targets, mechanism of action, and clinical trial phase. Use for 'targets', 'receptors', or 'drug approval status'.",
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': "Short description. e.g., 'find targets', 'clinical phase'"
                },
                'identifier': {
                    'type': 'string',
                    'description': 'Molecule identifier (SMILES, SELFIES, or common name).'
                }
            },
            'required': ['task_name', 'identifier']
        }
    },
    {
        'name': 'compute_quantum_mechanics',
        'description': 'Calculates quantum chemical properties like LUMO/HOMO energy and Dipole Moment.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': "Short description, e.g., 'lumo calculation'"
                },
                'smiles': {
                    'type': 'string',
                    'description': 'The exact SMILES/SELFIES string or name of the molecule.'
                }
            },
            'required': ['task_name', 'smiles']
        }
    },
    {
        'name': 'fetch_reaction_details',
        'description': 'Fetches empirical chemical reaction data (conditions, yield, reagents, catalysts) from ORD database. Supports forward prediction and retrosynthesis search.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': "Short descriptive name, e.g., 'predict yield', 'find solvents'"
                },
                'reaction_smiles': {
                    'type': 'string',
                    'description': "Chemical query (SMILES, SELFIES, InChIKey, or IUPAC name). Modes: 1) Full exact match: 'Reactants>>Products'; 2) Forward prediction: 'Reactants>>' or 'Reactants'; 3) Retrosynthesis/Conditions: '>>Product' or 'Product'."
                },
                'limit': {
                    'type': 'integer',
                    'description': 'Maximum number of reaction records to return.',
                    'default': 5
                }
            },
            'required': ['task_name', 'reaction_smiles']
        }
    },
    {
        'name': 'query_protein',
        'description': 'Analyzes a protein from sequence or UniProt accession. Retrieves sequence properties, homologs, annotations, catalytic info, pathways, and GO terms.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': "Short description used for output filename, e.g., 'analyze protein'"
                },
                'sequence': {
                    'type': 'string',
                    'description': 'Protein amino-acid sequence or FASTA. Provide exactly one of sequence or accession.'
                },
                'accession': {
                    'type': 'string',
                    'description': 'UniProt primary accession. Provide exactly one of sequence or accession.'
                },
                'query': {
                    'type': 'string',
                    'description': "Free-form protein question, e.g., 'identify its function'."
                }
            },
            'required': ['task_name']
        }
    },
    {
        'name': 'get_paper_references',
        'description': 'Get paper references (citations) for a list of PubMed IDs.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': 'A less than three word description of what the search is for.'
                },
                'pmids': {
                    'type': 'array',
                    'items': {'type': 'string'},
                    'description': 'List of PubMed IDs (PMIDs) to get references for.'
                },
                'batch_size': {'type': 'integer', 'default': 100},
                'mini_batch_size': {'type': 'integer', 'default': 20},
                'max_workers': {'type': 'integer', 'default': 4},
                'rate_limit': {'type': 'number', 'default': 3.0}
            },
            'required': ['task_name', 'pmids']
        }
    },
    {
        'name': 'fetch_paper_content',
        'description': 'Fetch and extract specific content from a PubMed paper by PMID using keyword/regex filtering.',
        'parameters': {
            'type': 'object',
            'properties': {
                'pmid': {
                    'type': 'string',
                    'description': 'A single PubMed ID (PMID) to fetch content for.'
                },
                'filter_keywords': {
                    'type': 'string',
                    'description': 'Keywords or regex pattern to search for and extract from the paper content.'
                }
            },
            'required': ['pmid', 'filter_keywords']
        }
    },
    {
        'name': 'fetch_paper_annotations',
        'description': 'Fetch biomedical entity annotations from PubTator3 for a list of PubMed IDs.',
        'parameters': {
            'type': 'object',
            'properties': {
                'pmids': {
                    'type': 'array',
                    'items': {'type': 'string'},
                    'description': 'List of PubMed IDs (PMIDs) to fetch annotations for.'
                },
                'batch_size': {'type': 'integer', 'default': 50},
                'max_retries': {'type': 'integer', 'default': 3},
                'max_requests_per_second': {'type': 'number', 'default': 3.0}
            },
            'required': ['pmids']
        }
    },
    {
        'name': 'find_entities',
        'description': 'Find and autocomplete biomedical entity names in the PubTator3 database.',
        'parameters': {
            'type': 'object',
            'properties': {
                'query_text': {
                    'type': 'string',
                    'description': 'A single search term (partial entity name) to find entities.'
                },
                'concept_type': {
                    'type': 'string',
                    'enum': ['GENE', 'DISEASE', 'CHEMICAL', 'VARIANT', 'SPECIES', 'CELLLINE'],
                    'description': 'Optional entity concept type.'
                },
                'limit': {'type': 'integer', 'default': 10},
                'max_retries': {'type': 'integer', 'default': 3},
                'max_requests_per_second': {'type': 'number', 'default': 3.0}
            },
            'required': ['query_text']
        }
    },
    {
        'name': 'search_papers',
        'description': 'Search PubMed articles using keywords, boolean queries, or relation queries. TIP: Simple keywords often yield better results.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': 'A less than three word description of what the search is for.'
                },
                'boolean_query_text': {
                    'type': 'string',
                    'description': 'Boolean query or simple natural language text.'
                },
                'relation_query': {
                    'type': 'object',
                    'description': 'Relation-based query configuration.'
                },
                'top_k': {
                    'type': 'integer',
                    'default': 100,
                    'description': 'Number of top results to return.'
                },
                'max_retries': {'type': 'integer', 'default': 3},
                'max_requests_per_second': {'type': 'number', 'default': 3.0}
            },
            'required': ['task_name']
        }
    },
    {
        'name': 'find_related_entities',
        'description': 'Find entities that have a specific relationship with a target entity using PubTator3 relations API.',
        'parameters': {
            'type': 'object',
            'properties': {
                'target_entity': {
                    'type': 'string',
                    'description': 'The target entity to find relations for.'
                },
                'relation_type': {
                    'type': 'string',
                    'enum': [
                        'ASSOCIATE', 'CAUSE', 'COMPARE', 'COTREAT',
                        'DRUG_INTERACT', 'INHIBIT', 'INTERACT',
                        'NEGATIVE_CORRELATE', 'POSITIVE_CORRELATE',
                        'PREVENT', 'STIMULATE', 'TREAT', 'ANY'
                    ],
                    'description': 'Type of relation to search for.'
                },
                'related_entity_type': {
                    'type': 'string',
                    'description': 'Type or ID of related entities to find.'
                },
                'limit': {'type': 'integer', 'default': 100},
                'max_retries': {'type': 'integer', 'default': 3},
                'max_requests_per_second': {'type': 'number', 'default': 3.0}
            },
            'required': ['target_entity', 'relation_type', 'related_entity_type']
        }
    },
    {
        'name': 'unified_disease_search',
        'description': 'Search for diseases across multiple authoritative databases (BioThings, KEGG, Open Targets) with a single search term.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': 'A less than three word description of what the search is for.'
                },
                'search_term': {
                    'type': 'string',
                    'description': 'Disease name, condition, or symptoms.'
                },
                'limit_per_source': {'type': 'integer', 'default': 10},
                'sources': {
                    'type': 'array',
                    'items': {'type': 'string'},
                    'description': "List of sources. Options: 'biothings', 'kegg', 'opentargets'."
                }
            },
            'required': ['task_name', 'search_term']
        }
    },
    {
        'name': 'fetch_disease_details',
        'description': 'Fetch comprehensive disease details using any identifier (MONDO, DOID, OMIM, MeSH, KEGG, EFO, or name).',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': 'A less than three word description of what the fetch is for.'
                },
                'disease_id': {
                    'type': 'string',
                    'description': 'Disease identifier or disease name.'
                },
                'id_type': {
                    'type': 'string',
                    'description': 'Type of identifier if known. Auto-detected if not specified.'
                },
                'sources': {
                    'type': 'array',
                    'items': {'type': 'string'},
                    'description': "List of sources. Options: 'biothings', 'kegg', 'opentargets'."
                }
            },
            'required': ['task_name', 'disease_id']
        }
    },
    {
        'name': 'unified_drug_search',
        'description': 'Search for drugs across multiple databases (BioThings, OpenFDA, KEGG, Open Targets). Returns FDA status, labels, and trials.',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': 'A less than three word description of what the search is for.'
                },
                'search_term': {
                    'type': 'string',
                    'description': 'Drug name, compound name, condition, or any search term.'
                },
                'limit_per_source': {'type': 'integer', 'default': 10},
                'sources': {
                    'type': 'array',
                    'items': {'type': 'string'},
                    'description': "List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'."
                }
            },
            'required': ['task_name', 'search_term']
        }
    },
    {
        'name': 'fetch_drug_details',
        'description': 'Fetch comprehensive drug details using any identifier (DrugBank, ChEBI, ChEMBL, PubChem, OpenFDA, KEGG, or name).',
        'parameters': {
            'type': 'object',
            'properties': {
                'task_name': {
                    'type': 'string',
                    'description': 'A less than three word description of what the fetch is for.'
                },
                'drug_id': {
                    'type': 'string',
                    'description': 'Drug identifier of any type or name.'
                },
                'id_type': {
                    'type': 'string',
                    'description': 'Type of identifier if known. Auto-detected if not specified.'
                },
                'sources': {
                    'type': 'array',
                    'items': {'type': 'string'},
                    'description': "List of sources. Options: 'biothings', 'openfda_approval', 'openfda_label', 'kegg', 'opentargets'."
                }
            },
            'required': ['task_name', 'drug_id']
        }
    },
    {
        'name': 'code_execution',
        'description': 'Execute Python code in a secure sandbox environment. Useful for custom calculations, data manipulation, or using specific libraries (e.g., RDKit, SELFIES, pandas) when predefined tools are insufficient.',
        'parameters': {
            'type': 'object',
            'properties': {
                'code': {
                    'type': 'string',
                    'description': 'The Python code script to execute.'
                },
                'language': {
                    'type': 'string',
                    'description': "The programming language to use (e.g., 'python').",
                    'default': 'python'
                }
            },
            'required': ['code']
        }
    }
])


if __name__ == '__main__':
    from swift.agent_template import agent_template_map
    from swift.infer_engine import InferEngine, InferRequest, RequestConfig, TransformersEngine
    model = '/home/data4/xiangyu/models/Qwen3.5-9B'
    adapters = ['/home/data4/xiangyu/skill-learner/outputs/qwen35-9b-sft-lora-r64-1epoch/v0-20261019-171035/last-checkpoint']
    engine = TransformersEngine(model, adapters=adapters, max_batch_size=8)

    # engine.template._agent_template = 'hermes'  # react_en/qwen_en/qwen_en_parallel

    infer(engine, get_infer_request())
    infer_stream(engine, get_infer_request())

[WARNING:swift] Loading model from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. This will execute custom Python code shipped in the model repository (e.g. configuration_*.py, modeling_*.py, tokenization_*.py). Only proceed if you trust the source of this model.
[INFO:swift] Setting torch_dtype: torch.bfloat16
[WARNING:swift] Loading config from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. Custom Python code from the model repository will be executed. Only use models from sources you trust.
[WARNING:swift] Loading tokenizer/processor from '/home/data4/xiangyu/models/Qwen3.5-9B' with trust_remote_code=True. Custom Python code from the model repository will be executed. Only use models from sources you trust.

[INFO:swift] model_kwargs: {'device_map': 'cuda:0', 'dtype': torch.bfloat16}
Loading weights: 100%|██████████| 760/760 [00:05<00:00, 144.71it/s]
[INFO:swift] Create the template for the infer_engine
[INFO:swift] Successfully loaded /home/data4/xiangyu/skill-learner/outputs/qwen35-9b-sft-lora-r64-1epoch/v0-20261019-171035/last-checkpoint/args.json.
[INFO:swift] default_system: None
[INFO:swift] max_length: 262144
[INFO:swift] response_prefix: None
[INFO:swift] agent_template: hermes
[INFO:swift] norm_bbox: norm1000

query: A 2-month-old male infant is brought in for a routine health maintenance visit. His growth and development are on track, with height and weight at the 50th percentile, consistent with prior growth measurements. However, his head circumference has increased to the 90th percentile from the 50th percentile noted at his newborn visit. The head appears elongated and narrow, with a prominent occiput and broad forehead. There are no facial dysmorphic features, and the rest of the physical exam is unremarkable. What is the most appropriate initial management for this infant?
Answer Choices: (A) Increased time in the prone position while awake and monitored (B) Measurement of parental head circumferences to assess for familial macrocephaly (C) Referral to a physical therapist to address positional head shape deformities (D) Cranial ultrasound to assess for hydrocephalus (E) MRI of the brain to evaluate intracranial structures (F) Observation with no further intervention unless symptoms worsen (G) Reevaluation of head circumference in one month (H) Referral to a pediatric endocrinologist for evaluation of growth abnormalities (I) Referral to craniofacial specialists (J) Referral for genetic testing

Please research this clinical scenario using your tools. You MUST conclude your final response with the exact string 'FINAL ANSWER: [Letter]', for example: FINAL ANSWER: A.
response: <think>

</think>

<tool_call>
{"name": "search_papers", "arguments": {"task_name": "infant macrocephaly management", "boolean_query_text": "infant macrocephaly head circumference rapid increase positional plagiocephaly hydrocephalus cranial ultrasound", "top_k": 20}}
</tool_call>
tool_calls: [ChatCompletionMessageToolCall(function=Function(name='search_papers', arguments='{"task_name": "infant macrocephaly management", "boolean_query_text": "infant macrocephaly head circumference rapid increase positional plagiocephaly hydrocephalus cranial ultrasound", "top_k": 20}'), type='function', id='toolcall-55cdcb229329403a8f1d60b7c75daa88')]
tool_response: ### Executed Code:
```python

from biodsa.tools.pubmed.pubtator_api import pubtator_api_search_papers
from biodsa.tools.pubmed.pubmed_api import pubmed_api_search_papers
import pandas as pd

df_list = []
has_relation_query = False

# 1. PubMed Search (Best Relevance Sorting)
if not has_relation_query:
    pmid_df = pubmed_api_search_papers(
        boolean_query_text='craniosynostosis diagnosis referral imaging sagittal synostosis infant clinical guideline',
        top_k=10,
    )
    if pmid_df is not None and not pmid_df.empty:
        for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:
            if col not in pmid_df.columns:
                pmid_df[col] = ""
        pmid_df = pmid_df[["PMID", "Title", "Journal", "Year", "Abstract"]]
        df_list.append(pmid_df)

# 2. PubTator3 Search (Entity highlighting, fallback)
pubtator_results = []
for page in range(1, 1 + 1):
    search_results = pubtator_api_search_papers(
        boolean_query_text='craniosynostosis diagnosis referral imaging sagittal synostosis infant clinical guideline',
        relation_query=None,
        page=page,
        max_retries=3,
        max_requests_per_second=3
    )
    if search_results is not None and not search_results.empty:
        pubtator_results.append(search_results)
    else:
        break

if pubtator_results:
    pubtator_df = pd.concat(pubtator_results)
    if "Highlighted_Text" in pubtator_df.columns:
        pubtator_df = pubtator_df.rename(columns={"Highlighted_Text": "Abstract"})

    for col in ["PMID", "Title", "Journal", "Year", "Abstract"]:
        if col not in pubtator_df.columns:
            pubtator_df[col] = ""
    pubtator_df = pubtator_df[["PMID", "Title", "Journal", "Year", "Abstract"]]
    df_list.append(pubtator_df)

# 3. Combine, Deduplicate and Format Clean Output
if df_list:
    final_df = pd.concat(df_list).reset_index(drop=True)
    # Deduplicate by PMID, keeping the first occurrence (which guarantees PubMed relevance is maintained)
    final_df = final_df.drop_duplicates(subset=["PMID"], keep="first")

    # Optional: Save to CSV for persistent logging
    final_df.to_csv('/home/data4/xiangyu/BioDSA/workdir/craniosynostosis_guidance.csv', index=False)
    print(f"The search results are saved at '/home/data4/xiangyu/BioDSA/workdir/craniosynostosis_guidance.csv'")
    print(f"Total results found: {len(final_df)}\n")
    print("=" * 80)
    print("TOP RESULTS (Showing up to 15 most relevant):")
    print("=" * 80)

    # FORMAT FOR LLM: Clean text layout rather than Markdown table
    for idx, row in final_df.head(15).iterrows():
        pmid = row.get('PMID', 'N/A')
        title = row.get('Title', 'No Title')
        journal = row.get('Journal', 'Unknown')
        year = row.get('Year', 'Unknown')
        abstract = str(row.get('Abstract', 'No Abstract Available'))

        # Clean abstract spaces and truncate at 1200 chars to save context window
        abstract = " ".join(abstract.split())
        if len(abstract) > 1200:
            abstract = abstract[:1200] + " ... [Truncated]"

        print(f"PMID: {pmid}")
        print(f"Title: {title}")
        print(f"Source: {journal} ({year})")
        print(f"Abstract: {abstract}")
        print("-" * 80)
else:
    print("No search results found. Please try again with different query. TIP: Try simpler keyword phrases.")

```

### Output:
```
The search results are saved at '/home/data4/xiangyu/BioDSA/workdir/craniosynostosis_guidance.csv'
Total results found: 10

================================================================================
TOP RESULTS (Showing up to 15 most relevant):
================================================================================
PMID: 40820202
Title: Developments in diagnostic and surgical techniques in children with sagittal suture craniosynostosis: a systematic review spanning the last 30 years
Source: Orphanet J Rare Dis (2025)
Abstract: In 2021 Ravindra et al. investigates the necessity of preoperative CT <m>imaging</m> in <m>infants</m> with yet <m>clinically</m> <m>diagnosed</m> single suture @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@, including @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>sagittal</m> <m>craniosynostosis</m>@@@.
--------------------------------------------------------------------------------
PMID: 33156164
Title: Updated Guideline on Treatment and Management of Craniosynostosis
Source: J Craniofac Surg (2021)
Abstract: None
--------------------------------------------------------------------------------
PMID: 37206061
Title: Minimally invasive craniectomy and postoperative cranial remolding orthotic treatment in infants with craniosynostosis: A multicenter prospective study
Source: World Neurosurg X (2023)
Abstract: In this study, for <m>imaging</m> of the @SPECIES_9606 @@@patients@@@' skull, we followed the "<m>Guideline</m> for Care of @SPECIES_9606 @@@Patients@@@ with the <m>Diagnoses</m> of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>Craniosynostosis</m>@@@".
--------------------------------------------------------------------------------
PMID: 35110924
Title: Intraoperative Measurement of Intracranial Pressure During Cranial Vault Remodeling in Children with Craniosynostosis
Source: J Neurosci Rural Pract (2022)
Abstract: Half of the children in our series were older than 1 year of age. It is due to the <m>referral</m> pattern. In our country, the awareness about @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@ is still low.
--------------------------------------------------------------------------------
PMID: 33575503
Title: Evaluation of the Molding Helmet Therapy for Japanese Infants with Deformational Plagiocephaly
Source: JMA J (2021)
Abstract: Ten @SPECIES_9606 @@@patients@@@ were strongly suspected of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@ after X-ray and/or CT (four @SPECIES_9606 @@@patients@@@ were definitively <m>diagnosed</m> as @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@, one @SPECIES_9606 @@@patient@@@ was sent back for further evaluation to the <m>referring</m> hospital, another @SPECIES_9606 @@@patient@@@ was lost to follow-up before further evaluation, and four @SPECIES_9606 @@@patients@@@ were ruled out of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>craniosynostosis</m>@@@ but declined helmet therapy).
--------------------------------------------------------------------------------
PMID: 36484829
Title: 48th Annual Meeting of the International Society for Pediatric Neurosurgery
Source: Childs Nerv Syst (2022)
Abstract: None
--------------------------------------------------------------------------------
PMID: 34716771
Title: ISPN 2021 Virtual Meeting of the International Society for Pediatric Neurosurgery
Source: Childs Nerv Syst (2021)
Abstract: None
--------------------------------------------------------------------------------
PMID: 39960858
Title: X-Linked Hypophosphatemia Management in Children: An International Working Group Clinical Practice Guideline
Source: J Clin Endocrinol Metab (2025)
Abstract: @DISEASE_Familial_Hypophosphatemic_Rickets @DISEASE_MESH:D053098 @@@X-Linked Hypophosphatemia@@@ Management in Children: An International Working Group <m>Clinical</m> Practice <m>Guideline</m>
--------------------------------------------------------------------------------
PMID: 27256993
Title: Diagnosis of infant synostotic and nonsynostotic cranial deformities: a review for pediatricians
Source: Rev Paul Pediatr (2016)
Abstract: We included the anatomy and physiology of normal skull development of children, discussing nuances related to nomenclature, epidemiology, etiology, and treatment of the most common forms of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@nonsyndromic <m>craniosynostosis</m>@@@. The <m>clinical</m> criteria for the differential <m>diagnosis</m> between @DISEASE_Musculoskeletal_Diseases @DISEASE_MESH:D009140 @@@positional deformities@@@ and @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@nonsyndromic <m>craniosynostosis</m>@@@ were also discussed, giving to the pediatrician subsidies for a quick and safe <m>clinical</m> <m>diagnosis</m>.
--------------------------------------------------------------------------------
PMID: 26355968
Title: Guideline for Care of Patients With the Diagnoses of Craniosynostosis: Working Group on Craniosynostosis
Source: J Craniofac Surg (2015)
Abstract: <m>Guideline</m> for Care of @SPECIES_9606 @@@Patients@@@ With the <m>Diagnoses</m> of @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>Craniosynostosis</m>@@@: Working Group on @DISEASE_Craniosynostoses @DISEASE_MESH:D003398 @@@<m>Craniosynostosis</m>@@@
--------------------------------------------------------------------------------

```


response2: <think>

</think>

<tool_call>
{"name": "fetch_paper_content", "arguments": {"filter_keywords": "positional deformities | craniosynostosis | imaging | referral | cranial ultrasound | MRI", "pmid": "27256993"}}
</tool_call>
response2: <think>

</think>

This infant’s head shape—elongated and narrow with a prominent occiput and broad forehead—is more suggestive of **sagittal craniosynostosis (scaphocephaly)** than typical positional plagiocephaly. The rapid increase in head circumference also warrants evaluation for intracranial pathology.

The most appropriate initial management is **cranial ultrasound to assess for hydrocephalus**, especially because the infant is young and the fontanelle is likely open. Ultrasound is a low-risk first-line imaging test. If the ultrasound is normal and the clinical picture remains suspicious, a craniofacial/neurosurgical specialist should evaluate for suture synostosis; MRI may be used later if intracranial structural abnormalities are suspected.

**Answer: (D) Cranial ultrasound to assess for hydrocephalus.**

FINAL ANSWER: D
query: A 2-month-old male infant is brought in for a routine health maintenance visit. His growth and development are on track, with height and weight at the 50th percentile, consistent with prior growth measurements. However, his head circumference has increased to the 90th percentile from the 50th percentile noted at his newborn visit. The head appears elongated and narrow, with a prominent occiput and broad forehead. There are no facial dysmorphic features, and the rest of the physical exam is unremarkable. What is the most appropriate initial management for this infant?
Answer Choices: (A) Increased time in the prone position while awake and monitored (B) Measurement of parental head circumferences to assess for familial macrocephaly (C) Referral to a physical therapist to address positional head shape deformities (D) Cranial ultrasound to assess for hydrocephalus (E) MRI of the brain to evaluate intracranial structures (F) Observation with no further intervention unless symptoms worsen (G) Reevaluation of head circumference in one month (H) Referral to a pediatric endocrinologist for evaluation of growth abnormalities (I) Referral to craniofacial specialists (J) Referral for genetic testing

Please research this clinical scenario using your tools. You MUST conclude your final response with the exact string 'FINAL ANSWER: [Letter]', for example: FINAL ANSWER: A.
response: <think>

</think>

<tool_call>
{"name": "search_papers", "arguments": {"task_name": "infant macrocephaly management", "boolean_query_text": "infant macrocephaly head circumference rapid increase positional plagiocephaly hydrocephalus cranial ultrasound", "top_k": 20}}
</tool_call>
tool_calls: [ChatCompletionMessageToolCall(function=Function(name='search_papers', arguments='{"task_name": "infant macrocephaly management", "boolean_query_text": "infant macrocephaly head circumference rapid increase positional plagiocephaly hydrocephalus cranial ultrasound", "top_k": 20}'), type='function', id='toolcall-c493088f886c40dfb285cf18f2cd763e')]
tool_response: {"temperature": 32, "condition": "Sunny", "humidity": 50}
response2: <think>

</think>

<tool_call>
{"name": "search_papers", "arguments": {"task_name": "infant macrocephaly management", "boolean_query_text": "infant macrocephaly head circumference rapid increase positional plagiocephaly hydrocephalus cranial ultrasound", "top_k": 20}}
</tool_call>

In [7]:
from Bio.Seq import Seq

sequence = "GATTTACCTGATGAGTTCAGAGAAAAACCTTCTGCCCAATGAAGTACAGGCCTATTGCTGGACACTGTTCCGAGTCGCGAGTCCTCGCACAGCCGGCTATTTAAATCGATCCTACCTCTATATTATACAGCCGCCTAGTGAGGACATCGACAGATTAGTGGTTGAATGAAAACGACGTCTTACTAGGTCTCAGTCCTGGCCCGTGGGGCCGTTAGACTATTCCGTCAAGGAAAGAGACCCGTGTAAGCTGTATACTTATTAAATAAATGTCACCACATGGTAGTTACCCACCCACTTCCGGCGGGGGCCGGCGGTCGTCTCCGCGATCGCCCGGATACGGCCGACTTTCAAGGTGTTCTCGTTAAGTGTTCCTTTACGACAATGATAACGCGAACGTGCCCGCATTCAAGAGGTCTCGAAAAATGACGGGACGGTAGGTTCATACTCTCAGAATACGCATACGTTTTAAGCGAGTAAGTTAGATGAGAAGGTACACGAAATATTACAACACAGGGCACGTCACGGCTGATCGGTATGCGTATTTTGCGGAGCTTATACTTAGATTTCGGAAGCCTAACTGGTTTGTCTTTCAGACGGTTCGATGCCCCCCGACTACCCGTACGTGGGGGGCTCGATGTAGCTAGACGTGGAAATTTCATCCTCCTAGCCCGCGTGCTGCCGGTGGGTGAGAAGATAATAAAGTATGGCCTACCCACAAACCGGATACATAACAACCTGGAATTCTCGAACACTCCCTCGTCGCGAACGTGCATTCTGGTTTGTTTTCTCGACATATCCCGACGTATAATTTCAAACCGTAGAGCATACCAAACCAAAGCATCTGGTCGGTCAGTCAAGGGGAAGTTTTGCTCACAACTACCGGCTTTACGTAAATGACGGAATGTAGCATCTCGGACTACGTTACTGCCGTTGCAACCTTTAGGCCGAGGATTACAC"
min_aa_length = 70

# 1. 修正了带有错误大括号的 Seq 实例化操作
seq = Seq(sequence.replace('U', 'T'))
orfs = []

for strand, nuc in [(+1, seq), (-1, seq.reverse_complement())]:
    for frame in range(3):
        # 裁剪掉末尾非 3 的倍数的碱基，避免 Biopython 抛出 Partial Codon 警告
        valid_length = len(nuc) - frame
        valid_length -= valid_length % 3
        valid_nuc = nuc[frame : frame + valid_length]
        
        trans = str(valid_nuc.translate())
        trans_len = len(trans)
        aa_start = 0
        
        while aa_start < trans_len:
            aa_end = trans.find('*', aa_start)
            if aa_end == -1:
                aa_end = trans_len
            
            # 2. 移除了变量周围多余的 { }
            if aa_end - aa_start >= min_aa_length:
                m_start = trans.find('M', aa_start, aa_end)
                if m_start != -1:
                    orf_seq = trans[m_start:aa_end]
                    
                    if len(orf_seq) >= min_aa_length:
                        # 3. 修正了向列表添加字典时多余的双大括号 {{ }}
                        orfs.append({
                            'strand': strand, 
                            'frame': frame, 
                            'length': len(orf_seq), 
                            'aa_seq': orf_seq
                        })
            aa_start = aa_end + 1

# 按长度降序排序
orfs.sort(key=lambda x: x['length'], reverse=True)

# 4. 修正了 f-string 中的变量解析语法，去除了转义用的 {{ }}
print(f"Total ORFs found >= {min_aa_length} AAs: {len(orfs)}")
if orfs:
    longest = orfs[0]
    print(f"Longest ORF length: {longest['length']}")
    print(f"Longest ORF AA sequence: {longest['aa_seq']}")
    if len(longest['aa_seq']) >= 2:
        print(f"Amino acid at position 2 of longest ORF: {longest['aa_seq'][1]}")

Total ORFs found >= 70 AAs: 2
Longest ORF length: 148
Longest ORF AA sequence: MSRKQTRMHVRDEGVFENSRLLCIRFVGRPYFIIFSPTGSTRARRMKFPRLATSSPPRTGSRGASNRLKDKPVRLPKSKYKLRKIRIPISRDVPCVVIFRVPSHLTYSLKTYAYSESMNLPSRHFSRPLECGHVRVIIVVKEHLTRTP
Amino acid at position 2 of longest ORF: S